# 🌑 Dark Hours of India
## Notebook 1 — Data Cleaning & Exploration

**Objective:** Load all 64 NCRB ADSI CSV files (2015-2022), 
understand their structure, clean them, and prepare for analysis.

**Tables in this notebook:**
- Table 1.2 — State/UT wise Accidental Deaths
- Table 1.4 — Age & Gender wise Deaths
- Table 1.9 / 1.10 — Cause wise Deaths
- Table 1.11 / 1.12 — Fire Accidents
- Table 1A.1 — Traffic Accidents Overview
- Table 1A.2 — Traffic Injuries & Deaths
- Table 1A.5 — Month wise Traffic Accidents
- Table 1A.6 — Time wise Traffic Accidents

In [1]:
# Importing all required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import glob

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.width', 1000)

print("✅ All libraries imported successfully!")
print(f"Pandas version: {pd.__version__}")
print(f"Numpy version: {np.__version__}")

Matplotlib is building the font cache; this may take a moment.

✅ All libraries imported successfully!
Pandas version: 3.0.2
Numpy version: 2.4.4

In [2]:
# Setting up data path
import os

# Path to raw data
RAW_DATA_PATH = "../data/raw/"

# List all files
all_files = sorted(os.listdir(RAW_DATA_PATH))
print(f"✅ Total files found: {len(all_files)}")
print("\n📁 All files:")
for f in all_files:
    print(f"  {f}")

✅ Total files found: 64

📁 All files:
  ADSI_2015_Table_1.11.csv
  ADSI_2015_Table_1.2.csv
  ADSI_2015_Table_1.4.csv
  ADSI_2015_Table_1.9.csv
  ADSI_2015_Table_1A.1.csv
  ADSI_2015_Table_1A.2.csv
  ADSI_2015_Table_1A.5.csv
  ADSI_2015_Table_1A.6.csv
  ADSI_2016_Table_1.11.csv
  ADSI_2016_Table_1.2.csv
  ADSI_2016_Table_1.4.csv
  ADSI_2016_Table_1.9.csv
  ADSI_2016_Table_1A.1.csv
  ADSI_2016_Table_1A.2.csv
  ADSI_2016_Table_1A.5.csv
  ADSI_2016_Table_1A.6.csv
  ADSI_2017_Table_1.11.csv
  ADSI_2017_Table_1.2.csv
  ADSI_2017_Table_1.4.csv
  ADSI_2017_Table_1.9.csv
  ADSI_2017_Table_1A.1.csv
  ADSI_2017_Table_1A.2.csv
  ADSI_2017_Table_1A.5.csv
  ADSI_2017_Table_1A.6.csv
  ADSI_2018_Table_1.11.csv
  ADSI_2018_Table_1.2.csv
  ADSI_2018_Table_1.4.csv
  ADSI_2018_Table_1.9.csv
  ADSI_2018_Table_1A.1.csv
  ADSI_2018_Table_1A.2.csv
  ADSI_2018_Table_1A.5.csv
  ADSI_2018_Table_1A.6.csv
  ADSI_2019_Table_1.11.csv
  ADSI_2019_Table_1.2.csv
  ADSI_2019_Table_1.4.csv
  ADSI_2019_Table_1.9.csv
  ADSI_2019_Table_1A.1.csv
  ADSI_2019_Table_1A.2.csv
  ADSI_2019_Table_1A.5.csv
  ADSI_2019_Table_1A.6.csv
  ADSI_2020_Table_1.10.csv
  ADSI_2020_Table_1.12.csv
  ADSI_2020_Table_1.2.csv
  ADSI_2020_Table_1.4.csv
  ADSI_2020_Table_1A.1.csv
  ADSI_2020_Table_1A.2.csv
  ADSI_2020_Table_1A.5.csv
  ADSI_2020_Table_1A.6.csv
  ADSI_2021_Table_1.10.csv
  ADSI_2021_Table_1.12.csv
  ADSI_2021_Table_1.2.csv
  ADSI_2021_Table_1.4.csv
  ADSI_2021_Table_1A.1.csv
  ADSI_2021_Table_1A.2.csv
  ADSI_2021_Table_1A.5.csv
  ADSI_2021_Table_1A.6.csv
  ADSI_2022_Table_1.10.csv
  ADSI_2022_Table_1.12.csv
  ADSI_2022_Table_1.2.csv
  ADSI_2022_Table_1.4.csv
  ADSI_2022_Table_1A.1.csv
  ADSI_2022_Table_1A.2.csv
  ADSI_2022_Table_1A.5.csv
  ADSI_2022_Table_1A.6.csv

In [3]:
# Pehli file explore karte hain - Table 1.2 (State wise deaths) 2015
df = pd.read_csv(RAW_DATA_PATH + "ADSI_2015_Table_1.2.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

Shape: (93, 10)

Columns:
['Sl. No. (Col.1)', 'Category (Col.2)', 'State/UT/City (Col.3)', 'Total Number of Accidental Deaths - Natural (Col.4)', 'Total Number of Accidental Deaths - Un-natural (Col.5)', 'Total Number of Accidental Deaths - Others (Col.6)', 'Total Number of Accidental Deaths - Total (Col.7)', 'Percentage Share in Total deaths (Col.8)', 'Projected Mid-Year Population* (In Lakh+) (Col.9)', 'Rate of Accidental Deaths (Col.10) = Col.7/Col.9']

First 5 rows:

  Sl. No. (Col.1) Category (Col.2) State/UT/City (Col.3)  Total Number of Accidental Deaths - Natural (Col.4)  Total Number of Accidental Deaths - Un-natural (Col.5)  Total Number of Accidental Deaths - Others (Col.6)  Total Number of Accidental Deaths - Total (Col.7)  Percentage Share in Total deaths (Col.8)  Projected Mid-Year Population* (In Lakh+) (Col.9)  Rate of Accidental Deaths (Col.10) = Col.7/Col.9
0               1            State        ANDHRA PRADESH                                                771                                                15320                                                    1321                                               17412                                       4.2                                              513.4                                              33.9
1               2            State     ARUNACHAL PRADESH                                                 27                                                  319                                                      23                                                 369                                       0.1                                               13.0                                              28.3
2               3            State                 ASSAM                                                236                                                 3910                                                     185                                                4331                                       1.0                                              322.0                                              13.5
3               4            State                 BIHAR                                                417                                                 9470                                                     481                                               10368                                       2.5                                             1031.4                                              10.1
4               5            State          CHHATTISGARH                                                261                                                14333                                                    4679                                               19273                                       4.7                                              256.6                                              75.1

In [4]:
print("Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nUnique Categories:")
print(df['Category\n(Col.2)'].unique())

Shape: (93, 10)

Data Types:
Sl. No. (Col.1)                                               str
Category (Col.2)                                              str
State/UT/City (Col.3)                                         str
Total Number of Accidental Deaths - Natural (Col.4)         int64
Total Number of Accidental Deaths - Un-natural (Col.5)      int64
Total Number of Accidental Deaths - Others (Col.6)          int64
Total Number of Accidental Deaths - Total (Col.7)           int64
Percentage Share in Total deaths (Col.8)                  float64
Projected Mid-Year Population* (In Lakh+) (Col.9)         float64
Rate of Accidental Deaths (Col.10) = Col.7/Col.9          float64
dtype: object

Missing Values:
Sl. No. (Col.1)                                           0
Category (Col.2)                                          0
State/UT/City (Col.3)                                     0
Total Number of Accidental Deaths - Natural (Col.4)       0
Total Number of Accidental Deaths - Un-natural (Col.5)    0
Total Number of Accidental Deaths - Others (Col.6)        0
Total Number of Accidental Deaths - Total (Col.7)         0
Percentage Share in Total deaths (Col.8)                  0
Projected Mid-Year Population* (In Lakh+) (Col.9)         0
Rate of Accidental Deaths (Col.10) = Col.7/Col.9          0
dtype: int64

Unique Categories:

KeyError: 'Category\n(Col.2)'

In [5]:
# Exact column names dekhte hain
for col in df.columns:
    print(repr(col))

'Sl. No. (Col.1)'
'Category (Col.2)'
'State/UT/City (Col.3)'
'Total Number of Accidental Deaths - Natural (Col.4)'
'Total Number of Accidental Deaths - Un-natural (Col.5)'
'Total Number of Accidental Deaths - Others (Col.6)'
'Total Number of Accidental Deaths - Total (Col.7)'
'Percentage Share in Total deaths (Col.8)'
'Projected Mid-Year Population* (In Lakh+) (Col.9)'
'Rate of Accidental Deaths (Col.10) = Col.7/Col.9'

In [6]:
# Unique categories dekhte hain
print("Unique Categories:")
print(df['Category (Col.2)'].unique())

print("\nTotal rows:", len(df))
print("\nState wise rows:", len(df[df['Category (Col.2)'] == 'State']))
print("UT wise rows:", len(df[df['Category (Col.2)'] == 'UT']))
print("City wise rows:", len(df[df['Category (Col.2)'] == 'City']))

Unique Categories:
<StringArray>
['State', 'TOTAL (STATES)', 'Union Territories', 'TOTAL (UTs)', 'TOTAL (ALL INDIA)', 'City', 'TOTAL (CITIES)']
Length: 7, dtype: str

Total rows: 93

State wise rows: 29
UT wise rows: 0
City wise rows: 53

In [7]:
# Column names clean karte hain
df.columns = [
    'sl_no', 'category', 'state_ut_city',
    'deaths_natural', 'deaths_unnatural', 'deaths_others',
    'deaths_total', 'pct_share', 'population_lakh', 'death_rate'
]

# Sirf State level data filter karte hain
df_states = df[df['category'] == 'State'].copy()

print("State level data shape:", df_states.shape)
print("\nStates list:")
print(df_states['state_ut_city'].tolist())

State level data shape: (29, 10)

States list:
['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL']

In [8]:
# Year column add karo
df_states['year'] = 2015

# Final clean dataframe dekhte hain
print("Final shape:", df_states.shape)
df_states.head()

Final shape: (29, 11)

  sl_no category      state_ut_city  deaths_natural  deaths_unnatural  deaths_others  deaths_total  pct_share  population_lakh  death_rate  year
0     1    State     ANDHRA PRADESH             771             15320           1321         17412        4.2            513.4        33.9  2015
1     2    State  ARUNACHAL PRADESH              27               319             23           369        0.1             13.0        28.3  2015
2     3    State              ASSAM             236              3910            185          4331        1.0            322.0        13.5  2015
3     4    State              BIHAR             417              9470            481         10368        2.5           1031.4        10.1  2015
4     5    State       CHHATTISGARH             261             14333           4679         19273        4.7            256.6        75.1  2015

In [9]:
# Function banate hain jo har year ki Table 1.2 file load aur clean kare
def load_table_1_2(year):
    # 2020 aur uske baad table number alag hai
    if year >= 2020:
        filename = f"ADSI_{year}_Table_1.2.csv"
    else:
        filename = f"ADSI_{year}_Table_1.2.csv"
    
    filepath = RAW_DATA_PATH + filename
    df = pd.read_csv(filepath)
    
    # Column names clean karo
    df.columns = [
        'sl_no', 'category', 'state_ut_city',
        'deaths_natural', 'deaths_unnatural', 'deaths_others',
        'deaths_total', 'pct_share', 'population_lakh', 'death_rate'
    ]
    
    # Sirf State data
    df = df[df['category'] == 'State'].copy()
    
    # Year add karo
    df['year'] = year
    
    return df

# Saare years ke liye load karo aur merge karo
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_data = []

for year in years:
    try:
        df = load_table_1_2(year)
        all_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Sab merge karo
df_deaths = pd.concat(all_data, ignore_index=True)
print(f"\n✅ Final merged shape: {df_deaths.shape}")

✅ 2015 loaded — 29 states
❌ 2016 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements
❌ 2017 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements
❌ 2018 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements
❌ 2019 error — Length mismatch: Expected axis has 8 elements, new values have 10 elements
❌ 2020 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements
❌ 2021 error — Length mismatch: Expected axis has 8 elements, new values have 10 elements
❌ 2022 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements

✅ Final merged shape: (29, 11)

In [10]:
# Har year ki file ke columns dekhte hain
for year in years:
    filename = f"ADSI_{year}_Table_1.2.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    print(f"\n{year} — {len(df_temp.columns)} columns:")
    for col in df_temp.columns:
        print(f"  {repr(col)}")

2015 — 10 columns:
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT/City (Col.3)'
  'Total Number of Accidental Deaths - Natural (Col.4)'
  'Total Number of Accidental Deaths - Un-natural (Col.5)'
  'Total Number of Accidental Deaths - Others (Col.6)'
  'Total Number of Accidental Deaths - Total (Col.7)'
  'Percentage Share in Total deaths (Col.8)'
  'Projected Mid-Year Population* (In Lakh+) (Col.9)'
  'Rate of Accidental Deaths (Col.10) = Col.7/Col.9'

2016 — 9 columns:
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT (Col.3)'
  'Total Number of Accidental Deaths - Forces of Nature (Col.4)'
  'Total Number of Accidental Deaths - Other Causes (Col.5)'
  'Total Number of Accidental Deaths - Total (Col.6)'
  'Percentage Share in Total Deaths (Col.7)'
  'Projected Mid-Year Population* (In Lakh+) (Col.8)'
  'Rate of Accidental Deaths (Col.9) = (Col.6/Col.8)'

2017 — 9 columns:
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT'
  'Total Number of Accidental Deaths - Forces of Nature (Col.4)'
  'Total Number of Accidental Deaths - Other Causes (Col.5)'
  'Total Number of Accidental Deaths - Total (Col.6)'
  'Percentage Share in Total Deaths (Col.7)'
  'Projected Mid-Year Population* (in Lakh) (Col.8)'
  'Rate of Accidental Deaths (Col.9 = Col.6/Col.8)'

2018 — 9 columns:
  'Sl. No. - (Col.1)'
  'Category - (Col.2)'
  'State/UT - (Col.3)'
  'Total Number of Accidental Deaths - Forces of Nature - (Col.4)'
  'Total Number of Accidental Deaths - Other Causes - (Col.5)'
  'Total Number of Accidental Deaths - Total - (Col.6)'
  'Percentage Share in Total Deaths - (Col.7)'
  'Projected Mid-Year Population* (in Lakh) - (Col.8)'
  'Rate of Accidental Deaths - (Col.9 = Col.6/Col.8)'

2019 — 8 columns:
  'Category (Col. 1)'
  'State/UT/City (Col. 2)'
  'Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Number of Accidental Deaths - Other Causes (Col. 4)'
  'Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population* (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

2020 — 9 columns:
  'Si. No. (Col. 1)'
  'Category'
  'State/UT/City (Col. 2)'
  'Total Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Total Number of Accidental Deaths - Other Causes (Col. 4)'
  'Total Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

2021 — 8 columns:
  'Category (Col. 1)'
  'State/UT/City (Col. 2)'
  'Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Number of Accidental Deaths - Other Causes (Col. 4)'
  'Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

2022 — 9 columns:
  'Sl. No.'
  'Category'
  'State/UT'
  'Total Number of Accidental Deaths - Forces of Nature - Col. (3)'
  'Total Number of Accidental Deaths - Other Causes - Col. (4)'
  'Total Number of Accidental Deaths - Total - Col. (5)'
  'Percentage Share in Total Deaths - Col. (6)'
  'Projected Mid-Year Population* (in Lakh) - Col. (7)'
  'Rate of Accidental Deaths (Col.5/Col.7)'

In [11]:
def load_table_1_2_smart(year):
    filename = f"ADSI_{year}_Table_1.2.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # Common columns jo hamesha chahiye
    result = pd.DataFrame()
    
    if year == 2015:
        # 2015 mein 3 death columns hain
        cat_col = [c for c in df.columns if 'Category' in c][0]
        state_col = [c for c in df.columns if 'State' in c][0]
        nat_col = [c for c in df.columns if 'Natural' in c and 'Un' not in c][0]
        unnat_col = [c for c in df.columns if 'Un-natural' in c][0]
        other_col = [c for c in df.columns if 'Others' in c][0]
        total_col = [c for c in df.columns if 'Total' in c][0]
        pop_col = [c for c in df.columns if 'Population' in c][0]
        rate_col = [c for c in df.columns if 'Rate' in c][0]
        
        df = df[df[cat_col] == 'State'].copy()
        result['category'] = df[cat_col]
        result['state_ut_city'] = df[state_col]
        result['deaths_nature'] = df[nat_col]
        result['deaths_unnatural'] = df[unnat_col]
        result['deaths_others'] = df[other_col]
        result['deaths_total'] = df[total_col]
        result['population_lakh'] = df[pop_col]
        result['death_rate'] = df[rate_col]
        
    else:
        # 2016-2022 mein 2 death columns hain
        cat_col = [c for c in df.columns if 'Category' in c or c.strip() == 'Category'][0]
        state_col = [c for c in df.columns if 'State' in c][0]
        nature_col = [c for c in df.columns if 'Nature' in c or 'Forces' in c][0]
        other_col = [c for c in df.columns if 'Other' in c][0]
        total_col = [c for c in df.columns if 'Total' in c][0]
        pop_col = [c for c in df.columns if 'Population' in c][0]
        rate_col = [c for c in df.columns if 'Rate' in c][0]
        
        df = df[df[cat_col].astype(str).str.strip() == 'State'].copy()
        result['category'] = df[cat_col]
        result['state_ut_city'] = df[state_col]
        result['deaths_nature'] = df[nature_col]
        result['deaths_unnatural'] = None
        result['deaths_others'] = None
        result['deaths_total'] = df[total_col]
        result['population_lakh'] = df[pop_col]
        result['death_rate'] = df[rate_col]
    
    result['year'] = year
    return result

# Test karte hain saare years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_data = []

for year in years:
    try:
        df = load_table_1_2_smart(year)
        all_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Merge karo
df_deaths = pd.concat(all_data, ignore_index=True)
print(f"\n✅ Final merged shape: {df_deaths.shape}")
df_deaths.head()

✅ 2015 loaded — 29 states
✅ 2016 loaded — 30 states
✅ 2017 loaded — 30 states
✅ 2018 loaded — 30 states
✅ 2019 loaded — 30 states
✅ 2020 loaded — 28 states
✅ 2021 loaded — 28 states
✅ 2022 loaded — 28 states

✅ Final merged shape: (233, 9)

  category      state_ut_city  deaths_nature deaths_unnatural deaths_others  deaths_total  population_lakh  death_rate  year
0    State     ANDHRA PRADESH            771            15320          1321           771            513.4        33.9  2015
1    State  ARUNACHAL PRADESH             27              319            23            27             13.0        28.3  2015
2    State              ASSAM            236             3910           185           236            322.0        13.5  2015
3    State              BIHAR            417             9470           481           417           1031.4        10.1  2015
4    State       CHHATTISGARH            261            14333          4679           261            256.6        75.1  2015

In [12]:
# Har year mein kitne states hain
print("Year wise state count:")
print(df_deaths.groupby('year')['state_ut_city'].count())

print("\n2015 states jo baad mein nahi hain:")
states_2015 = set(df_deaths[df_deaths['year']==2015]['state_ut_city'])
states_2022 = set(df_deaths[df_deaths['year']==2022]['state_ut_city'])
print(states_2015 - states_2022)

print("\n2022 mein naye states:")
print(states_2022 - states_2015)

Year wise state count:
year
2015    29
2016    30
2017    30
2018    30
2019    30
2020    28
2021    28
2022    28
Name: state_ut_city, dtype: int64

2015 states jo baad mein nahi hain:
{'TRIPURA', 'ASSAM', 'ANDHRA PRADESH', 'MIZORAM', 'UTTARAKHAND', 'MADHYA PRADESH', 'TELANGANA', 'BIHAR', 'JAMMU & KASHMIR', 'RAJASTHAN', 'MAHARASHTRA', 'NAGALAND', 'HIMACHAL PRADESH', 'UTTAR PRADESH', 'MEGHALAYA', 'HARYANA', 'KARNATAKA', 'MANIPUR', 'WEST BENGAL', 'CHHATTISGARH', 'GOA', 'PUNJAB', 'JHARKHAND', 'GUJARAT', 'TAMIL NADU', 'ODISHA', 'ARUNACHAL PRADESH', 'KERALA', 'SIKKIM'}

2022 mein naye states:
{'Jharkhand', 'Odisha', 'Sikkim', 'West Bengal', 'Gujarat', 'Goa', 'Bihar', 'Karnataka', 'Rajasthan', 'Haryana', 'Mizoram', 'Punjab', 'Madhya Pradesh', 'Assam', 'Chhattisgarh', 'Andhra Pradesh', 'Maharashtra', 'Tamil Nadu', 'Manipur', 'Himachal Pradesh', 'Tripura', 'Arunachal Pradesh', 'Telangana', 'Uttar Pradesh', 'Nagaland', 'Kerala', 'Uttarakhand', 'Meghalaya'}

In [13]:
# Saare state names uppercase kar do — consistency ke liye
df_deaths['state_ut_city'] = df_deaths['state_ut_city'].str.strip().str.upper()

# Ab check karo
print("Year wise state count:")
print(df_deaths.groupby('year')['state_ut_city'].count())

print("\n2015 vs 2022 difference:")
states_2015 = set(df_deaths[df_deaths['year']==2015]['state_ut_city'])
states_2022 = set(df_deaths[df_deaths['year']==2022]['state_ut_city'])
print("2015 mein hai, 2022 mein nahi:", states_2015 - states_2022)
print("2022 mein hai, 2015 mein nahi:", states_2022 - states_2015)

Year wise state count:
year
2015    29
2016    30
2017    30
2018    30
2019    30
2020    28
2021    28
2022    28
Name: state_ut_city, dtype: int64

2015 vs 2022 difference:
2015 mein hai, 2022 mein nahi: {'JAMMU & KASHMIR'}
2022 mein hai, 2015 mein nahi: set()

In [14]:
# Check - 2016 mein kaun sa extra state tha
states_2016 = set(df_deaths[df_deaths['year']==2016]['state_ut_city'])
print("Extra state in 2016 vs 2015:")
print(states_2016 - states_2015)

# J&K ko 2020 ke baad data mein note karo
print("\nJ&K data availability:")
jk = df_deaths[df_deaths['state_ut_city'] == 'JAMMU & KASHMIR']
print(jk[['year', 'state_ut_city', 'deaths_total']])

Extra state in 2016 vs 2015:
{'TOTAL (STATES)'}

J&K data availability:
     year    state_ut_city  deaths_total
9    2015  JAMMU & KASHMIR           387
38   2016  JAMMU & KASHMIR           280
68   2017  JAMMU & KASHMIR           127
98   2018  JAMMU & KASHMIR           131
128  2019  JAMMU & KASHMIR          1451

In [15]:
# Remove TOTAL rows jo filter mein ghus gayi hain
df_deaths = df_deaths[~df_deaths['state_ut_city'].str.contains('TOTAL')].copy()

# Reset index
df_deaths = df_deaths.reset_index(drop=True)

# Final check
print("Final shape:", df_deaths.shape)
print("\nYear wise state count after fix:")
print(df_deaths.groupby('year')['state_ut_city'].count())

Final shape: (229, 9)

Year wise state count after fix:
year
2015    29
2016    29
2017    29
2018    29
2019    29
2020    28
2021    28
2022    28
Name: state_ut_city, dtype: int64

In [16]:
# Save cleaned data
output_path = "../data/processed/state_deaths_2015_2022.csv"
df_deaths.to_csv(output_path, index=False)

print("✅ Data saved successfully!")
print(f"Location: {output_path}")
print(f"Shape: {df_deaths.shape}")
print("\nSample data:")
df_deaths.head()

✅ Data saved successfully!
Location: ../data/processed/state_deaths_2015_2022.csv
Shape: (229, 9)

Sample data:

  category      state_ut_city  deaths_nature deaths_unnatural deaths_others  deaths_total  population_lakh  death_rate  year
0    State     ANDHRA PRADESH            771            15320          1321           771            513.4        33.9  2015
1    State  ARUNACHAL PRADESH             27              319            23            27             13.0        28.3  2015
2    State              ASSAM            236             3910           185           236            322.0        13.5  2015
3    State              BIHAR            417             9470           481           417           1031.4        10.1  2015
4    State       CHHATTISGARH            261            14333          4679           261            256.6        75.1  2015

In [17]:
# Explore Table 1A.5 - Month wise Traffic Accidents 2015
df_month = pd.read_csv(RAW_DATA_PATH + "ADSI_2015_Table_1A.5.csv")

print("Shape:", df_month.shape)
print("\nColumns:")
for col in df_month.columns:
    print(f"  {repr(col)}")
print("\nFirst 3 rows:")
df_month.head(3)

Shape: (93, 55)

Columns:
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Jan.'
  'Road Accidents - Feb.'
  'Road Accidents - Mar.'
  'Road Accidents - Apr.'
  'Road Accidents - May'
  'Road Accidents - Jun.'
  'Road Accidents - Jul.'
  'Road Accidents - Aug.'
  'Road Accidents - Sep.'
  'Road Accidents - Oct.'
  'Road Accidents - Nov.'
  'Road Accidents - Dec.'
  'Road Accidents - Total'
  'Railway Crossing Accidents - Jan.'
  'Railway Crossing Accidents - Feb.'
  'Railway Crossing Accidents - Mar.'
  'Railway Crossing Accidents - Apr.'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - Jun.'
  'Railway Crossing Accidents - Jul.'
  'Railway Crossing Accidents - Aug.'
  'Railway Crossing Accidents - Sep.'
  'Railway Crossing Accidents - Oct.'
  'Railway Crossing Accidents - Nov.'
  'Railway Crossing Accidents - Dec.'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - Jan.'
  'Railway Accidents - Feb.'
  'Railway Accidents - Mar.'
  'Railway Accidents - Apr.'
  'Railway Accidents - May'
  'Railway Accidents - Jun.'
  'Railway Accidents - Jul.'
  'Railway Accidents - Aug.'
  'Railway Accidents - Sep.'
  'Railway Accidents - Oct.'
  'Railway Accidents - Nov.'
  'Railway Accidents - Dec.'
  'Railway Accidents - Total'
  'Total Traffic Accidents - Jan.'
  'Total Traffic Accidents - Feb.'
  'Total Traffic Accidents - Mar.'
  'Total Traffic Accidents - Apr.'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - Jun.'
  'Total Traffic Accidents - Jul.'
  'Total Traffic Accidents - Aug.'
  'Total Traffic Accidents - Sep.'
  'Total Traffic Accidents - Oct.'
  'Total Traffic Accidents - Nov.'
  'Total Traffic Accidents - Dec.'
  'Total Traffic Accidents - Total'

First 3 rows:

,Sl. No.,Category,State/UT/City,Road Accidents - Jan.,Road Accidents - Feb.,Road Accidents - Mar.,Road Accidents - Apr.,Road Accidents - May,Road Accidents - Jun.,Road Accidents - Jul.,Road Accidents - Aug.,Road Accidents - Sep.,Road Accidents - Oct.,Road Accidents - Nov.,Road Accidents - Dec.,Road Accidents - Total,Railway Crossing Accidents - Jan.,Railway Crossing Accidents - Feb.,Railway Crossing Accidents - Mar.,Railway Crossing Accidents - Apr.,Railway Crossing Accidents - May,Railway Crossing Accidents - Jun.,Railway Crossing Accidents - Jul.,Railway Crossing Accidents - Aug.,Railway Crossing Accidents - Sep.,Railway Crossing Accidents - Oct.,Railway Crossing Accidents - Nov.,Railway Crossing Accidents - Dec.,Railway Crossing Accidents - Total,Railway Accidents - Jan.,Railway Accidents - Feb.,Railway Accidents - Mar.,Railway Accidents - Apr.,Railway Accidents - May,Railway Accidents - Jun.,Railway Accidents - Jul.,Railway Accidents - Aug.,Railway Accidents - Sep.,Railway Accidents - Oct.,Railway Accidents - Nov.,Railway Accidents - Dec.,Railway Accidents - Total,Total Traffic Accidents - Jan.,Total Traffic Accidents - Feb.,Total Traffic Accidents - Mar.,Total Traffic Accidents - Apr.,Total Traffic Accidents - May,Total Traffic Accidents - Jun.,Total Traffic Accidents - Jul.,Total Traffic Accidents - Aug.,Total Traffic Accidents - Sep.,Total Traffic Accidents - Oct.,Total Traffic Accidents - Nov.,Total Traffic Accidents - Dec.,Total Traffic Accidents - Total
0,1,State,ANDHRA PRADESH,1868,1970,1917,2041,2067,1896,2086,1793,1758,1824,1736,1883,22839,27,18,23,21,30,23,26,19,22,21,17,21,268,98,75,95,93,109,92,111,88,90,108,84,86,1129,1993,2063,2035,2155,2206,2011,2223,1900,1870,1953,1837,1990,24236
1,2,State,ARUNACHAL PRADESH,26,28,26,15,12,14,23,24,24,22,40,30,284,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,26,28,26,15,12,14,24,24,24,22,40,30,285
2,3,State,ASSAM,764,670,658,551,546,544,511,524,508,609,520,554,6959,3,1,0,2,0,0,0,0,0,2,1,1,10,52,44,42,55,38,72,55,54,80,58,64,50,664,819,715,700,608,584,616,566,578,588,669,585,605,7633

In [18]:
# Filter State level data - saare columns
df_month_filtered = df_month[
    df_month['Category'] == 'State'
].copy()

# State names uppercase
df_month_filtered['State/UT/City'] = df_month_filtered['State/UT/City'].str.strip().str.upper()

# Year add karo
df_month_filtered['year'] = 2015

print("Shape:", df_month_filtered.shape)
print("\nStates:", df_month_filtered['State/UT/City'].tolist())
df_month_filtered.head(3)

Shape: (29, 56)

States: ['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL']

,Sl. No.,Category,State/UT/City,Road Accidents - Jan.,Road Accidents - Feb.,Road Accidents - Mar.,Road Accidents - Apr.,Road Accidents - May,Road Accidents - Jun.,Road Accidents - Jul.,Road Accidents - Aug.,Road Accidents - Sep.,Road Accidents - Oct.,Road Accidents - Nov.,Road Accidents - Dec.,Road Accidents - Total,Railway Crossing Accidents - Jan.,Railway Crossing Accidents - Feb.,Railway Crossing Accidents - Mar.,Railway Crossing Accidents - Apr.,Railway Crossing Accidents - May,Railway Crossing Accidents - Jun.,Railway Crossing Accidents - Jul.,Railway Crossing Accidents - Aug.,Railway Crossing Accidents - Sep.,Railway Crossing Accidents - Oct.,Railway Crossing Accidents - Nov.,Railway Crossing Accidents - Dec.,Railway Crossing Accidents - Total,Railway Accidents - Jan.,Railway Accidents - Feb.,Railway Accidents - Mar.,Railway Accidents - Apr.,Railway Accidents - May,Railway Accidents - Jun.,Railway Accidents - Jul.,Railway Accidents - Aug.,Railway Accidents - Sep.,Railway Accidents - Oct.,Railway Accidents - Nov.,Railway Accidents - Dec.,Railway Accidents - Total,Total Traffic Accidents - Jan.,Total Traffic Accidents - Feb.,Total Traffic Accidents - Mar.,Total Traffic Accidents - Apr.,Total Traffic Accidents - May,Total Traffic Accidents - Jun.,Total Traffic Accidents - Jul.,Total Traffic Accidents - Aug.,Total Traffic Accidents - Sep.,Total Traffic Accidents - Oct.,Total Traffic Accidents - Nov.,Total Traffic Accidents - Dec.,Total Traffic Accidents - Total,year
0,1,State,ANDHRA PRADESH,1868,1970,1917,2041,2067,1896,2086,1793,1758,1824,1736,1883,22839,27,18,23,21,30,23,26,19,22,21,17,21,268,98,75,95,93,109,92,111,88,90,108,84,86,1129,1993,2063,2035,2155,2206,2011,2223,1900,1870,1953,1837,1990,24236,2015
1,2,State,ARUNACHAL PRADESH,26,28,26,15,12,14,23,24,24,22,40,30,284,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,26,28,26,15,12,14,24,24,24,22,40,30,285,2015
2,3,State,ASSAM,764,670,658,551,546,544,511,524,508,609,520,554,6959,3,1,0,2,0,0,0,0,0,2,1,1,10,52,44,42,55,38,72,55,54,80,58,64,50,664,819,715,700,608,584,616,566,578,588,669,585,605,7633,2015

In [19]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # Find category column
    cat_col = [c for c in df.columns if 'Category' in c or c.strip() == 'Category'][0]
    state_col = [c for c in df.columns if 'State' in c][0]
    
    # Sirf State level
    df = df[df[cat_col].astype(str).str.strip() == 'State'].copy()
    
    # State names uppercase
    df[state_col] = df[state_col].str.strip().str.upper()
    
    # Rename common columns
    df = df.rename(columns={
        cat_col: 'category',
        state_col: 'state_ut_city'
    })
    
    # Remove TOTAL rows
    df = df[~df['state_ut_city'].str.contains('TOTAL')].copy()
    
    # Year add karo
    df['year'] = year
    
    # Reset index
    df = df.reset_index(drop=True)
    
    return df

# Load all years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_month_data = []

for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states, {len(df.columns)} columns")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 loaded — 29 states, 56 columns
✅ 2016 loaded — 29 states, 56 columns
✅ 2017 loaded — 29 states, 56 columns
✅ 2018 loaded — 29 states, 56 columns
✅ 2019 loaded — 29 states, 55 columns
✅ 2020 loaded — 28 states, 56 columns
✅ 2021 loaded — 28 states, 55 columns
❌ 2022 error — list index out of range

In [20]:
# 2022 columns dekhte hain
df_2022 = pd.read_csv(RAW_DATA_PATH + "ADSI_2022_Table_1A.5.csv")
print("2022 columns:")
for col in df_2022.columns:
    print(f"  {repr(col)}")
print("\nCategory unique values:")
cat_col = [c for c in df_2022.columns if 'Category' in c or c.strip() == 'Category']
print(cat_col)

2022 columns:
  'Sl. No.'
  'State/UT/Cities'
  'Road Accidents - January'
  'Road Accidents - February'
  'Road Accidents - March'
  'Road Accidents - April'
  'Road Accidents - May'
  'Road Accidents - June'
  'Road Accidents - July'
  'Road Accidents - August'
  'Road Accidents - September'
  'Road Accidents - October'
  'Road Accidents - November'
  'Road Accidents - December'
  'Road Accidents - Total'
  'Railway Crossing Accidents - January'
  'Railway Crossing Accidents - February'
  'Railway Crossing Accidents - March'
  'Railway Crossing Accidents - April'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - June'
  'Railway Crossing Accidents - July'
  'Railway Crossing Accidents - August'
  'Railway Crossing Accidents - September'
  'Railway Crossing Accidents - October'
  'Railway Crossing Accidents - November'
  'Railway Crossing Accidents - December'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - January'
  'Railway Accidents - February'
  'Railway Accidents - March'
  'Railway Accidents - April'
  'Railway Accidents - May'
  'Railway Accidents - June'
  'Railway Accidents - July'
  'Railway Accidents - August'
  'Railway Accidents - September'
  'Railway Accidents - October'
  'Railway Accidents - November'
  'Railway Accidents - December'
  'Railway Accidents - Total'
  'Total Traffic Accidents - January'
  'Total Traffic Accidents - February'
  'Total Traffic Accidents - March'
  'Total Traffic Accidents - April'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - June'
  'Total Traffic Accidents - July'
  'Total Traffic Accidents - August'
  'Total Traffic Accidents - September'
  'Total Traffic Accidents - October'
  'Total Traffic Accidents - November'
  'Total Traffic Accidents - December'
  'Total Traffic Accidents - Total'

Category unique values:
[]

In [21]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # Category column dhundho
    cat_cols = [c for c in df.columns if 'Category' in c or c.strip() == 'Category']
    state_cols = [c for c in df.columns if 'State' in c]
    
    if len(cat_cols) > 0:
        # Category column hai — filter karo
        cat_col = cat_cols[0]
        state_col = state_cols[0]
        df = df[df[cat_col].astype(str).str.strip() == 'State'].copy()
        df = df.rename(columns={cat_col: 'category', state_col: 'state_ut_city'})
    else:
        # 2022 jaisa — Category nahi hai
        state_col = state_cols[0]
        df['category'] = 'State'
        df = df.rename(columns={state_col: 'state_ut_city'})
    
    # State names uppercase
    df['state_ut_city'] = df['state_ut_city'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['state_ut_city'].str.contains('TOTAL')].copy()
    
    # Year add karo
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_month_data = []

for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states, {len(df.columns)} columns")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 loaded — 29 states, 56 columns
✅ 2016 loaded — 29 states, 56 columns
✅ 2017 loaded — 29 states, 56 columns
✅ 2018 loaded — 29 states, 56 columns
✅ 2019 loaded — 29 states, 55 columns
✅ 2020 loaded — 28 states, 56 columns
✅ 2021 loaded — 28 states, 55 columns
✅ 2022 loaded — 89 states, 56 columns

In [22]:
# Check 2022 data structure
df_2022 = pd.read_csv(RAW_DATA_PATH + "ADSI_2022_Table_1A.5.csv")
print("Total rows:", len(df_2022))
print("\nFirst 10 State/UT/Cities values:")
print(df_2022['State/UT/Cities'].head(10).tolist())

Total rows: 93

First 10 State/UT/Cities values:
['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand']

In [23]:
# Check all unique values to identify states vs cities vs UTs
print("All values in State/UT/Cities column:")
print(df_2022['State/UT/Cities'].tolist())

All values in State/UT/Cities column:
['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Total (States)', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi (UT)', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry', 'Total (UTs)', 'Total (All India)', 'Agra', 'Ahmedabad', 'Amritsar', 'Asansol', 'Aurangabad', 'Bengaluru', 'Bhopal', 'Chandigarh (City)', 'Chennai', 'Coimbatore', 'Delhi (City)', 'Dhanbad', 'Durg Bhilainagar', 'Faridabad', 'Ghaziabad', 'Gwalior', 'Hyderabad', 'Indore', 'Jabalpur', 'Jaipur', 'Jamshedpur', 'Jodhpur', 'Kannur', 'Kanpur', 'Kochi', 'Kolkata', 'Kollam', 'Kota', 'Kozhikode', 'Lucknow', 'Ludhiana', 'Madurai', 'Malappuram', 'Meerut', 'Mumbai', 'Nagpur', 'Nasik', 'Patna', 'Prayagraj +', 'Pune', 'Raipur', 'Rajkot', 'Ranchi', 'Srinagar', 'Surat', 'Thiruvananthapuram', 'Thrissur', 'Tiruchirappalli', 'Vadodara', 'Varanasi', 'Vasai Virar', 'Vijayawada', 'Vishakhapatnam', 'Total (Cities)']

In [24]:
# For 2022 - extract only states (before 'Total (States)')
state_list_2022 = []
for val in df_2022['State/UT/Cities'].tolist():
    if val == 'Total (States)':
        break
    state_list_2022.append(val)

print("States found:", len(state_list_2022))
print(state_list_2022)

States found: 28
['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [25]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # Category column dhundho
    cat_cols = [c for c in df.columns if 'Category' in c or c.strip() == 'Category']
    state_cols = [c for c in df.columns if 'State' in c]
    
    if len(cat_cols) > 0:
        # Category column hai — filter karo
        cat_col = cat_cols[0]
        state_col = state_cols[0]
        df = df[df[cat_col].astype(str).str.strip() == 'State'].copy()
        df = df.rename(columns={cat_col: 'category', state_col: 'state_ut_city'})
    else:
        # 2022 — No category column, extract states before Total (States)
        state_col = state_cols[0]
        state_list = []
        for val in df[state_col].tolist():
            if 'Total' in str(val):
                break
            state_list.append(val)
        df = df[df[state_col].isin(state_list)].copy()
        df['category'] = 'State'
        df = df.rename(columns={state_col: 'state_ut_city'})
    
    # State names uppercase
    df['state_ut_city'] = df['state_ut_city'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['state_ut_city'].str.contains('TOTAL')].copy()
    
    # Year add karo
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_month_data = []

for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states, {len(df.columns)} columns")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 loaded — 29 states, 56 columns
✅ 2016 loaded — 29 states, 56 columns
✅ 2017 loaded — 29 states, 56 columns
✅ 2018 loaded — 29 states, 56 columns
✅ 2019 loaded — 29 states, 55 columns
✅ 2020 loaded — 28 states, 56 columns
✅ 2021 loaded — 28 states, 55 columns
✅ 2022 loaded — 28 states, 56 columns

In [26]:
# Check 2015 UT values
df_2015 = pd.read_csv(RAW_DATA_PATH + "ADSI_2015_Table_1A.5.csv")
print("All categories in 2015:")
print(df_2015['Category'].unique())
print("\nUT rows:")
print(df_2015[df_2015['Category'] == 'Union Territories']['State/UT/City'].tolist())

All categories in 2015:
<StringArray>
['State', 'TOTAL(STATES)', 'Union Territories', 'TOTAL (UTs)', 'TOTAL (ALL INDIA)', 'City', 'TOTAL (CITIES)']
Length: 7, dtype: str

UT rows:
['A & N ISLANDS', 'CHANDIGARH', 'D & N HAVELI', 'DAMAN & DIU', 'DELHI (UT)', 'LAKSHADWEEP', 'PUDUCHERRY']

In [27]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # Category column dhundho
    cat_cols = [c for c in df.columns if 'Category' in c or c.strip() == 'Category']
    state_cols = [c for c in df.columns if 'State' in c]
    
    if len(cat_cols) > 0:
        cat_col = cat_cols[0]
        state_col = state_cols[0]
        
        # States AND UTs dono lo
        df = df[df[cat_col].astype(str).str.strip().isin(['State', 'Union Territories'])].copy()
        df = df.rename(columns={cat_col: 'category', state_col: 'state_ut_city'})
    else:
        # 2022 — No category column
        state_col = state_cols[0]
        # Extract before Total (Cities)
        valid_list = []
        for val in df[state_col].tolist():
            if 'Total (Cities)' in str(val) or 'Total (All India)' in str(val):
                break
            if 'Total' not in str(val) and 'City' not in str(val):
                valid_list.append(val)
        df = df[df[state_col].isin(valid_list)].copy()
        df['category'] = 'State/UT'
        df = df.rename(columns={state_col: 'state_ut_city'})
    
    # State names uppercase
    df['state_ut_city'] = df['state_ut_city'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['state_ut_city'].str.contains('TOTAL')].copy()
    
    # Year add karo
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_month_data = []

for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states/UTs, {len(df.columns)} columns")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 loaded — 36 states/UTs, 56 columns
✅ 2016 loaded — 29 states/UTs, 56 columns
✅ 2017 loaded — 29 states/UTs, 56 columns
✅ 2018 loaded — 29 states/UTs, 56 columns
✅ 2019 loaded — 29 states/UTs, 55 columns
✅ 2020 loaded — 36 states/UTs, 56 columns
✅ 2021 loaded — 28 states/UTs, 55 columns
✅ 2022 loaded — 36 states/UTs, 56 columns

In [28]:
# Check 2016 categories
df_2016 = pd.read_csv(RAW_DATA_PATH + "ADSI_2016_Table_1A.5.csv")
cat_col = [c for c in df_2016.columns if 'Category' in c][0]
print("2016 unique categories:")
print(df_2016[cat_col].unique())

2016 unique categories:
<StringArray>
['State', 'Union Territory', 'Total (All India)', 'City']
Length: 4, dtype: str

In [29]:
# Check all years category names
for year in years:
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    cat_cols = [c for c in df_temp.columns if 'Category' in c or c.strip() == 'Category']
    if len(cat_cols) > 0:
        cat_col = cat_cols[0]
        print(f"{year}: {df_temp[cat_col].unique().tolist()}")
    else:
        print(f"{year}: No category column")

2015: ['State', 'TOTAL(STATES)', 'Union Territories', 'TOTAL (UTs)', 'TOTAL (ALL INDIA)', 'City', 'TOTAL (CITIES)']
2016: ['State', 'Union Territory', 'Total (All India)', 'City']
2017: ['State', 'Union Territory', 'Total (All India)', 'City']
2018: ['State', 'Union Territory', 'Total (All India)', 'City']
2019: ['State', 'UT', 'TOTAL (ALL INDIA)', 'City']
2020: ['State', 'Total (States)', 'Union Territories', 'Total (UTs)', 'Total (All India)', 'City', 'Total (Cities)']
2021: ['State', 'UT', 'Total (All India)', 'City']
2022: No category column

In [30]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # UT category names — year wise
    ut_names = {
        2015: 'Union Territories',
        2016: 'Union Territory',
        2017: 'Union Territory',
        2018: 'Union Territory',
        2019: 'UT',
        2020: 'Union Territories',
        2021: 'UT',
        2022: None
    }
    
    cat_cols = [c for c in df.columns if 'Category' in c or c.strip() == 'Category']
    state_cols = [c for c in df.columns if 'State' in c]
    
    if len(cat_cols) > 0:
        cat_col = cat_cols[0]
        state_col = state_cols[0]
        
        # States AND UTs dono lo
        valid_categories = ['State', ut_names[year]]
        df = df[df[cat_col].astype(str).str.strip().isin(valid_categories)].copy()
        df = df.rename(columns={cat_col: 'category', state_col: 'state_ut_city'})
    else:
        # 2022 — No category column
        state_col = state_cols[0]
        valid_list = []
        for val in df[state_col].tolist():
            if 'Total' in str(val) and 'Cities' in str(val):
                break
            if 'Total' not in str(val):
                valid_list.append(val)
        df = df[df[state_col].isin(valid_list)].copy()
        df['category'] = 'State/UT'
        df = df.rename(columns={state_col: 'state_ut_city'})
    
    # Uppercase
    df['state_ut_city'] = df['state_ut_city'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['state_ut_city'].str.contains('TOTAL')].copy()
    
    # Year add
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_month_data = []

for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states/UTs, {len(df.columns)} columns")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 loaded — 36 states/UTs, 56 columns
✅ 2016 loaded — 36 states/UTs, 56 columns
✅ 2017 loaded — 36 states/UTs, 56 columns
✅ 2018 loaded — 36 states/UTs, 56 columns
✅ 2019 loaded — 36 states/UTs, 55 columns
✅ 2020 loaded — 36 states/UTs, 56 columns
✅ 2021 loaded — 36 states/UTs, 55 columns
✅ 2022 loaded — 89 states/UTs, 56 columns

In [31]:
# Check 2022 - Cities kahan se start hoti hain
df_2022 = pd.read_csv(RAW_DATA_PATH + "ADSI_2022_Table_1A.5.csv")
print(df_2022['State/UT/Cities'].tolist())

['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Total (States)', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi (UT)', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry', 'Total (UTs)', 'Total (All India)', 'Agra', 'Ahmedabad', 'Amritsar', 'Asansol', 'Aurangabad', 'Bengaluru', 'Bhopal', 'Chandigarh (City)', 'Chennai', 'Coimbatore', 'Delhi (City)', 'Dhanbad', 'Durg Bhilainagar', 'Faridabad', 'Ghaziabad', 'Gwalior', 'Hyderabad', 'Indore', 'Jabalpur', 'Jaipur', 'Jamshedpur', 'Jodhpur', 'Kannur', 'Kanpur', 'Kochi', 'Kolkata', 'Kollam', 'Kota', 'Kozhikode', 'Lucknow', 'Ludhiana', 'Madurai', 'Malappuram', 'Meerut', 'Mumbai', 'Nagpur', 'Nasik', 'Patna', 'Prayagraj +', 'Pune', 'Raipur', 'Rajkot', 'Ranchi', 'Srinagar', 'Surat', 'Thiruvananthapuram', 'Thrissur', 'Tiruchirappalli', 'Vadodara', 'Varanasi', 'Vasai Virar', 'Vijayawada', 'Vishakhapatnam', 'Total (Cities)']

In [32]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    ut_names = {
        2015: 'Union Territories',
        2016: 'Union Territory',
        2017: 'Union Territory',
        2018: 'Union Territory',
        2019: 'UT',
        2020: 'Union Territories',
        2021: 'UT',
        2022: None
    }
    
    cat_cols = [c for c in df.columns if 'Category' in c or c.strip() == 'Category']
    state_cols = [c for c in df.columns if 'State' in c]
    
    if len(cat_cols) > 0:
        cat_col = cat_cols[0]
        state_col = state_cols[0]
        valid_categories = ['State', ut_names[year]]
        df = df[df[cat_col].astype(str).str.strip().isin(valid_categories)].copy()
        df = df.rename(columns={cat_col: 'category', state_col: 'state_ut_city'})
    else:
        # 2022 — stop at Total (UTs)
        state_col = state_cols[0]
        valid_list = []
        for val in df[state_col].tolist():
            if 'Total (UTs)' in str(val) or 'Total (All India)' in str(val):
                break
            if 'Total' not in str(val):
                valid_list.append(val)
        df = df[df[state_col].isin(valid_list)].copy()
        df['category'] = 'State/UT'
        df = df.rename(columns={state_col: 'state_ut_city'})
    
    # Uppercase
    df['state_ut_city'] = df['state_ut_city'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['state_ut_city'].str.contains('TOTAL')].copy()
    
    # Year add
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_month_data = []

for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states/UTs, {len(df.columns)} columns")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 loaded — 36 states/UTs, 56 columns
✅ 2016 loaded — 36 states/UTs, 56 columns
✅ 2017 loaded — 36 states/UTs, 56 columns
✅ 2018 loaded — 36 states/UTs, 56 columns
✅ 2019 loaded — 36 states/UTs, 55 columns
✅ 2020 loaded — 36 states/UTs, 56 columns
✅ 2021 loaded — 36 states/UTs, 55 columns
✅ 2022 loaded — 36 states/UTs, 56 columns

In [33]:
# Check 2019 vs 2015 columns difference
df_2019 = pd.read_csv(RAW_DATA_PATH + "ADSI_2019_Table_1A.5.csv")
df_2015 = pd.read_csv(RAW_DATA_PATH + "ADSI_2015_Table_1A.5.csv")

cols_2015 = set(df_2015.columns)
cols_2019 = set(df_2019.columns)

print("Columns in 2015 but NOT in 2019:")
print(cols_2015 - cols_2019)

print("\nColumns in 2019 but NOT in 2015:")
print(cols_2019 - cols_2015)

Columns in 2015 but NOT in 2019:
{'Road Accidents - Mar.', 'Railway Accidents - May', 'Railway Crossing Accidents - May', 'Total Traffic Accidents - Mar.', 'Railway Accidents - Dec.', 'Railway Crossing Accidents - Jun.', 'Road Accidents - Nov.', 'Railway Accidents - Total', 'Railway Accidents - Oct.', 'Total Traffic Accidents - Nov.', 'Total Traffic Accidents - Oct.', 'Railway Accidents - Jun.', 'Total Traffic Accidents - Feb.', 'Road Accidents - Total', 'Railway Accidents - Mar.', 'Road Accidents - Dec.', 'Total Traffic Accidents - Jul.', 'Railway Crossing Accidents - Apr.', 'Road Accidents - Aug.', 'Railway Accidents - Jul.', 'Sl. No.', 'Railway Crossing Accidents - Oct.', 'Total Traffic Accidents - Aug.', 'Road Accidents - Oct.', 'Railway Crossing Accidents - Aug.', 'Railway Crossing Accidents - Nov.', 'Railway Crossing Accidents - Jul.', 'Road Accidents - Apr.', 'Road Accidents - Jan.', 'Railway Accidents - Apr.', 'Railway Accidents - Feb.', 'Total Traffic Accidents - Jan.', 'Road Accidents - Jul.', 'Total Traffic Accidents - Sep.', 'Total Traffic Accidents - May', 'Road Accidents - Sep.', 'Railway Crossing Accidents - Mar.', 'Railway Accidents - Nov.', 'Railway Crossing Accidents - Sep.', 'Railway Accidents - Aug.', 'Railway Crossing Accidents - Jan.', 'Road Accidents - May', 'Railway Crossing Accidents - Dec.', 'Railway Crossing Accidents - Total', 'Road Accidents - Jun.', 'Railway Accidents - Jan.', 'Railway Crossing Accidents - Feb.', 'Total Traffic Accidents - Jun.', 'Total Traffic Accidents - Total', 'Total Traffic Accidents - Dec.', 'Total Traffic Accidents - Apr.', 'Railway Accidents - Sep.', 'Road Accidents - Feb.'}

Columns in 2019 but NOT in 2015:
{'Railway Crossing Accidents_May', 'Total Traffic Accidents_Aug', 'Road Accidents_Sept', 'Total Traffic Accidents_June', 'Railway Accidents_Dec', 'Total Traffic Accidents_Oct', 'Total Traffic Accidents_Nov', 'Railway Accidents_April', 'Road Accidents_April', 'Railway Crossing Accidents_Jan', 'Railway Accidents_Oct', 'Road Accidents_May', 'Total Traffic Accidents_Feb', 'Railway Crossing Accidents_Dec', 'Railway Crossing Accidents_June', 'Railway Accidents_Aug', 'Railway Crossing Accidents_Feb', 'Road Accidents_Dec', 'Railway Crossing Accidents_Aug', 'Railway Crossing Accidents_Nov', 'Railway Accidents_June', 'Railway Crossing Accidents_Total', 'Railway Accidents_Feb', 'Road Accidents_Jan', 'Road Accidents_Total', 'Railway Crossing Accidents_Mar', 'Road Accidents_Nov', 'Railway Crossing Accidents_July', 'Road Accidents_July', 'Railway Accidents_May', 'Total Traffic Accidents_April', 'Total Traffic Accidents_Sept', 'Total Traffic Accidents_Jan', 'Railway Crossing Accidents_April', 'Road Accidents_Oct', 'Railway Crossing Accidents_Oct', 'Total Traffic Accidents_Mar', 'Total Traffic Accidents_May', 'Road Accidents_Mar', 'Railway Crossing Accidents_Sept', 'Railway Accidents_Jan', 'Road Accidents_Aug', 'Railway Accidents_Sept', 'Railway Accidents_July', 'Total Traffic Accidents_July', 'Road Accidents_Feb', 'Total Traffic Accidents_Total', 'Railway Accidents_Nov', 'Total Traffic Accidents_Dec', 'Railway Accidents_Mar', 'Road Accidents_June', 'Railway Accidents_Total'}

In [34]:
def standardize_columns(df):
    new_cols = {}
    for col in df.columns:
        new_col = col
        # Replace dash with underscore
        new_col = new_col.replace(' - ', '_')
        # Remove dots
        new_col = new_col.replace('.', '')
        # Replace spaces with underscore
        new_col = new_col.replace(' ', '_')
        # Standardize month names
        month_map = {
            'Jan': 'January', 'Feb': 'February', 'Mar': 'March',
            'Apr': 'April', 'Jun': 'June', 'Jul': 'July',
            'Aug': 'August', 'Sep': 'September', 'Sept': 'September',
            'Oct': 'October', 'Nov': 'November', 'Dec': 'December'
        }
        for short, full in month_map.items():
            new_col = new_col.replace(short, full)
        new_cols[col] = new_col
    return df.rename(columns=new_cols)

# Test on 2015 and 2019
df_2015_std = standardize_columns(df_2015)
df_2019_std = standardize_columns(df_2019)

print("2015 columns after standardize:")
print(df_2015_std.columns.tolist())
print("\n2019 columns after standardize:")
print(df_2019_std.columns.tolist())

2015 columns after standardize:
['Sl_No', 'Category', 'State/UT/City', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_Septemberember', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_Septemberember', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_Septemberember', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_Septemberember', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2019 columns after standardize:
['Category', 'State/UT/City', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_Aprilil', 'Road_Accidents_May', 'Road_Accidents_Junee', 'Road_Accidents_Julyy', 'Road_Accidents_August', 'Road_Accidents_Septemberembert', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_Aprilil', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_Junee', 'Railway_Crossing_Accidents_Julyy', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_Septemberembert', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_Aprilil', 'Railway_Accidents_May', 'Railway_Accidents_Junee', 'Railway_Accidents_Julyy', 'Railway_Accidents_August', 'Railway_Accidents_Septemberembert', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_Aprilil', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_Junee', 'Total_Traffic_Accidents_Julyy', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_Septemberembert', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

In [35]:
import re

def standardize_columns(df):
    new_cols = {}
    for col in df.columns:
        new_col = col
        # Replace separators
        new_col = new_col.replace(' - ', '_')
        new_col = new_col.replace('.', '')
        new_col = new_col.replace(' ', '_')
        
        # Standardize month names — exact word match only
        month_map = {
            'Jan': 'January', 'Feb': 'February', 'Mar': 'March',
            'Apr': 'April', 'Jun': 'June', 'Jul': 'July',
            'Aug': 'August', 'Sept': 'September', 'Sep': 'September',
            'Oct': 'October', 'Nov': 'November', 'Dec': 'December'
        }
        for short, full in month_map.items():
            # Exact word match using regex
            new_col = re.sub(r'\b' + short + r'\b', full, new_col)
        
        new_cols[col] = new_col
    return df.rename(columns=new_cols)

# Test again
df_2015_std = standardize_columns(df_2015)
df_2019_std = standardize_columns(df_2019)

print("2015 September column:")
print([c for c in df_2015_std.columns if 'Sep' in c or 'Apr' in c or 'Jun' in c or 'Jul' in c])

print("\n2019 September column:")
print([c for c in df_2019_std.columns if 'Sep' in c or 'Apr' in c or 'Jun' in c or 'Jul' in c])

2015 September column:
['Road_Accidents_Apr', 'Road_Accidents_Jun', 'Road_Accidents_Jul', 'Road_Accidents_Sep', 'Railway_Crossing_Accidents_Apr', 'Railway_Crossing_Accidents_Jun', 'Railway_Crossing_Accidents_Jul', 'Railway_Crossing_Accidents_Sep', 'Railway_Accidents_Apr', 'Railway_Accidents_Jun', 'Railway_Accidents_Jul', 'Railway_Accidents_Sep', 'Total_Traffic_Accidents_Apr', 'Total_Traffic_Accidents_Jun', 'Total_Traffic_Accidents_Jul', 'Total_Traffic_Accidents_Sep']

2019 September column:
['Road_Accidents_April', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_Sept', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_Sept', 'Railway_Accidents_April', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_Sept', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_Sept']

In [36]:
def standardize_columns(df):
    new_cols = {}
    
    # Complete month name mapping
    month_map = {
        '_Jan_': '_January_', '_Feb_': '_February_', 
        '_Mar_': '_March_', '_Apr_': '_April_',
        '_Jun_': '_June_', '_Jul_': '_July_',
        '_Aug_': '_August_', '_Sep_': '_September_',
        '_Sept_': '_September_', '_Oct_': '_October_',
        '_Nov_': '_November_', '_Dec_': '_December_',
        # For end of string
        '_Jan': '_January', '_Feb': '_February',
        '_Mar': '_March', '_Apr': '_April',
        '_Jun': '_June', '_Jul': '_July',
        '_Aug': '_August', '_Sep': '_September',
        '_Sept': '_September', '_Oct': '_October',
        '_Nov': '_November', '_Dec': '_December'
    }
    
    for col in df.columns:
        new_col = col
        new_col = new_col.replace(' - ', '_')
        new_col = new_col.replace('.', '')
        new_col = new_col.replace(' ', '_')
        
        for short, full in month_map.items():
            new_col = new_col.replace(short, full)
        
        new_cols[col] = new_col
    
    return df.rename(columns=new_cols)

# Test
df_2015_std = standardize_columns(df_2015)
df_2019_std = standardize_columns(df_2019)

print("2015 problem columns:")
print([c for c in df_2015_std.columns if any(m in c for m in ['Apr', 'Jun', 'Jul', 'Sep'])])
print("\n2019 problem columns:")
print([c for c in df_2019_std.columns if any(m in c for m in ['Apr', 'Jun', 'Jul', 'Sep'])])

print("\n2015 all columns:")
print(df_2015_std.columns.tolist())

2015 problem columns:
['Road_Accidents_April', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_Septemberember', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_Septemberember', 'Railway_Accidents_April', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_Septemberember', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_Septemberember']

2019 problem columns:
['Road_Accidents_Aprilil', 'Road_Accidents_Junee', 'Road_Accidents_Julyy', 'Road_Accidents_Septemberembert', 'Railway_Crossing_Accidents_Aprilil', 'Railway_Crossing_Accidents_Junee', 'Railway_Crossing_Accidents_Julyy', 'Railway_Crossing_Accidents_Septemberembert', 'Railway_Accidents_Aprilil', 'Railway_Accidents_Junee', 'Railway_Accidents_Julyy', 'Railway_Accidents_Septemberembert', 'Total_Traffic_Accidents_Aprilil', 'Total_Traffic_Accidents_Junee', 'Total_Traffic_Accidents_Julyy', 'Total_Traffic_Accidents_Septemberembert']

2015 all columns:
['Sl_No', 'Category', 'State/UT/City', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_Septemberember', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_Septemberember', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_Septemberember', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_Septemberember', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

In [37]:
import re

def standardize_col_name(col):
    col_work = col.strip()
    
    # Step 1: Replace month patterns FIRST using regex
    month_patterns = [
        (r'\bJan\.', 'January'), (r'\bFeb\.', 'February'),
        (r'\bMar\.', 'March'), (r'\bApr\.', 'April'),
        (r'\bJun\.', 'June'), (r'\bJul\.', 'July'),
        (r'\bAug\.', 'August'), (r'\bSept?\.', 'September'),
        (r'\bOct\.', 'October'), (r'\bNov\.', 'November'),
        (r'\bDec\.', 'December'),
        # Without dots (2019 style)
        (r'\bSept\b', 'September'), (r'\bJune\b', 'June'),
        (r'\bJuly\b', 'July'), (r'\bApril\b', 'April'),
    ]
    for pattern, replacement in month_patterns:
        col_work = re.sub(pattern, replacement, col_work)
    
    # Step 2: General cleanup AFTER month replacement
    col_work = col_work.replace(' - ', '_')
    col_work = col_work.replace('_-_', '_')
    col_work = col_work.replace('.', '')
    col_work = col_work.replace(' ', '_')
    
    return col_work

def standardize_columns(df):
    new_cols = {col: standardize_col_name(col) for col in df.columns}
    return df.rename(columns=new_cols)

# Test
df_2015_std = standardize_columns(df_2015)
df_2019_std = standardize_columns(df_2019)

print("2015 problem columns:")
print([c for c in df_2015_std.columns if any(m in c for m in ['Apr', 'Jun', 'Jul', 'Sep'])])
print("\n2019 problem columns:")
print([c for c in df_2019_std.columns if any(m in c for m in ['Apr', 'Jun', 'Jul', 'Sep'])])

2015 problem columns:
['Road_Accidents_April', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_September', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_September', 'Railway_Accidents_April', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_September', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_September']

2019 problem columns:
['Road_Accidents_April', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_Sept', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_Sept', 'Railway_Accidents_April', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_Sept', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_Sept']

In [39]:
import re

def standardize_col_name(col):
    col_work = col.strip()
    
    # Step 1: Replace separators first
    col_work = col_work.replace(' - ', '_')
    col_work = col_work.replace(' ', '_')
    
    # Step 2: Replace month abbreviations
    month_map = {
        'Jan\\.': 'January', 'Feb\\.': 'February',
        'Mar\\.': 'March', 'Apr\\.': 'April',
        'Jun\\.': 'June', 'Jul\\.': 'July',
        'Aug\\.': 'August', 'Sep\\.': 'September',
        'Sept\\.': 'September', 'Oct\\.': 'October',
        'Nov\\.': 'November', 'Dec\\.': 'December',
        # Without dots
        '_Sept_': '_September_', '_Sept$': '_September',
        'April': 'April', 'June': 'June',
        'July': 'July', 'August': 'August',
    }
    
    # Handle Sept without dot explicitly
    col_work = re.sub(r'_Sept(_|$)', lambda m: '_September' + m.group(1), col_work)
    
    # Handle abbreviated months with dots
    col_work = re.sub(r'_Jan\.', '_January', col_work)
    col_work = re.sub(r'_Feb\.', '_February', col_work)
    col_work = re.sub(r'_Mar\.', '_March', col_work)
    col_work = re.sub(r'_Apr\.', '_April', col_work)
    col_work = re.sub(r'_Jun\.', '_June', col_work)
    col_work = re.sub(r'_Jul\.', '_July', col_work)
    col_work = re.sub(r'_Aug\.', '_August', col_work)
    col_work = re.sub(r'_Sep\.', '_September', col_work)
    col_work = re.sub(r'_Sept\.', '_September', col_work)
    col_work = re.sub(r'_Oct\.', '_October', col_work)
    col_work = re.sub(r'_Nov\.', '_November', col_work)
    col_work = re.sub(r'_Dec\.', '_December', col_work)
    
    # Remove remaining dots
    col_work = col_work.replace('.', '')
    
    return col_work

def standardize_columns(df):
    new_cols = {col: standardize_col_name(col) for col in df.columns}
    return df.rename(columns=new_cols)

# Test
df_2015_std = standardize_columns(df_2015)
df_2019_std = standardize_columns(df_2019)

print("2015 problem columns:")
print([c for c in df_2015_std.columns if 'Sept' in c])
print("\n2019 problem columns:")
print([c for c in df_2019_std.columns if 'Sept' in c])

print("\n2015 all traffic columns:")
print([c for c in df_2015_std.columns if 'Total_Traffic' in c])
print("\n2019 all traffic columns:")
print([c for c in df_2019_std.columns if 'Total_Traffic' in c])

2015 problem columns:
['Road_Accidents_September', 'Railway_Crossing_Accidents_September', 'Railway_Accidents_September', 'Total_Traffic_Accidents_September']

2019 problem columns:
['Road_Accidents_September', 'Railway_Crossing_Accidents_September', 'Railway_Accidents_September', 'Total_Traffic_Accidents_September']

2015 all traffic columns:
['Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2019 all traffic columns:
['Total_Traffic_Accidents_Jan', 'Total_Traffic_Accidents_Feb', 'Total_Traffic_Accidents_Mar', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_Aug', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_Oct', 'Total_Traffic_Accidents_Nov', 'Total_Traffic_Accidents_Dec', 'Total_Traffic_Accidents_Total']

In [40]:
import re

def standardize_col_name(col):
    col_work = col.strip()
    
    # Step 1: Replace separators first
    col_work = col_work.replace(' - ', '_')
    col_work = col_work.replace(' ', '_')
    col_work = col_work.replace('.', '')
    
    # Step 2: Replace ALL month variations using regex word boundary
    month_map = [
        (r'_Jan(_|$)', r'_January\1'),
        (r'_Feb(_|$)', r'_February\1'),
        (r'_Mar(_|$)', r'_March\1'),
        (r'_Apr(_|$)', r'_April\1'),
        (r'_Jun(_|$)', r'_June\1'),
        (r'_Jul(_|$)', r'_July\1'),
        (r'_Aug(_|$)', r'_August\1'),
        (r'_Sept(_|$)', r'_September\1'),
        (r'_Sep(_|$)', r'_September\1'),
        (r'_Oct(_|$)', r'_October\1'),
        (r'_Nov(_|$)', r'_November\1'),
        (r'_Dec(_|$)', r'_December\1'),
    ]
    
    for pattern, replacement in month_map:
        col_work = re.sub(pattern, replacement, col_work)
    
    return col_work

def standardize_columns(df):
    new_cols = {col: standardize_col_name(col) for col in df.columns}
    return df.rename(columns=new_cols)

# Test all years
for year in years:
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    df_temp_std = standardize_columns(df_temp)
    traffic_cols = [c for c in df_temp_std.columns if 'Total_Traffic' in c]
    print(f"\n{year}:")
    print(traffic_cols)

2015:
['Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2016:
['Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2017:
['Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2018:
['Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2019:
['Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2020:
['Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2021:
['Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2022:
['Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

In [41]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    ut_names = {
        2015: 'Union Territories', 2016: 'Union Territory',
        2017: 'Union Territory', 2018: 'Union Territory',
        2019: 'UT', 2020: 'Union Territories',
        2021: 'UT', 2022: None
    }
    
    cat_cols = [c for c in df.columns if 'Category' in c or c.strip() == 'Category']
    state_cols = [c for c in df.columns if 'State' in c]
    
    if len(cat_cols) > 0:
        cat_col = cat_cols[0]
        state_col = state_cols[0]
        valid_categories = ['State', ut_names[year]]
        df = df[df[cat_col].astype(str).str.strip().isin(valid_categories)].copy()
        df = df.rename(columns={cat_col: 'category', state_col: 'state_ut_city'})
    else:
        state_col = state_cols[0]
        valid_list = []
        for val in df[state_col].tolist():
            if 'Total (UTs)' in str(val) or 'Total (All India)' in str(val):
                break
            if 'Total' not in str(val):
                valid_list.append(val)
        df = df[df[state_col].isin(valid_list)].copy()
        df['category'] = 'State/UT'
        df = df.rename(columns={state_col: 'state_ut_city'})
    
    # Standardize columns
    df = standardize_columns(df)
    
    # Uppercase state names
    df['state_ut_city'] = df['state_ut_city'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['state_ut_city'].str.contains('TOTAL')].copy()
    
    # Year add
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_month_data = []

for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states/UTs, {len(df.columns)} columns")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Merge all years
df_monthly = pd.concat(all_month_data, ignore_index=True)
print(f"\n✅ Final merged shape: {df_monthly.shape}")

# Save
output_path = "../data/processed/monthly_traffic_accidents_2015_2022.csv"
df_monthly.to_csv(output_path, index=False)
print(f"✅ Saved to {output_path}")

✅ 2015 loaded — 36 states/UTs, 56 columns
✅ 2016 loaded — 36 states/UTs, 56 columns
✅ 2017 loaded — 36 states/UTs, 56 columns
✅ 2018 loaded — 36 states/UTs, 56 columns
✅ 2019 loaded — 36 states/UTs, 55 columns
✅ 2020 loaded — 36 states/UTs, 56 columns
✅ 2021 loaded — 36 states/UTs, 55 columns
✅ 2022 loaded — 36 states/UTs, 56 columns

✅ Final merged shape: (288, 57)
✅ Saved to ../data/processed/monthly_traffic_accidents_2015_2022.csv

In [42]:
# Check which column is missing in 2019 vs 2015
df_2019_loaded = load_table_1A_5(2019)
df_2015_loaded = load_table_1A_5(2015)

cols_2015 = set(df_2015_loaded.columns)
cols_2019 = set(df_2019_loaded.columns)

print("In 2015 but NOT in 2019:")
print(cols_2015 - cols_2019)

print("\nIn 2019 but NOT in 2015:")
print(cols_2019 - cols_2015)

In 2015 but NOT in 2019:
{'Sl_No'}

In 2019 but NOT in 2015:
set()

In [43]:
# Verify merged data
print("Merged shape:", df_monthly.shape)
print("\nSl_No null check by year:")
print(df_monthly.groupby('year')['Sl_No'].isnull().sum())
print("\nSample data:")
df_monthly.head(3)

Merged shape: (288, 57)

Sl_No null check by year:

AttributeError: 'SeriesGroupBy' object has no attribute 'isnull'

In [44]:
# Verify merged data
print("Merged shape:", df_monthly.shape)
print("\nSl_No null check by year:")
print(df_monthly.groupby('year')['Sl_No'].apply(lambda x: x.isnull().sum()))
print("\nSample data:")
df_monthly.head(3)

Merged shape: (288, 57)

Sl_No null check by year:
year
2015     0
2016     0
2017     0
2018     0
2019    36
2020    36
2021    36
2022     0
Name: Sl_No, dtype: int64

Sample data:

,Sl_No,category,state_ut_city,Road_Accidents_January,Road_Accidents_February,Road_Accidents_March,Road_Accidents_April,Road_Accidents_May,Road_Accidents_June,Road_Accidents_July,Road_Accidents_August,Road_Accidents_September,Road_Accidents_October,Road_Accidents_November,Road_Accidents_December,Road_Accidents_Total,Railway_Crossing_Accidents_January,Railway_Crossing_Accidents_February,Railway_Crossing_Accidents_March,Railway_Crossing_Accidents_April,Railway_Crossing_Accidents_May,Railway_Crossing_Accidents_June,Railway_Crossing_Accidents_July,Railway_Crossing_Accidents_August,Railway_Crossing_Accidents_September,Railway_Crossing_Accidents_October,Railway_Crossing_Accidents_November,Railway_Crossing_Accidents_December,Railway_Crossing_Accidents_Total,Railway_Accidents_January,Railway_Accidents_February,Railway_Accidents_March,Railway_Accidents_April,Railway_Accidents_May,Railway_Accidents_June,Railway_Accidents_July,Railway_Accidents_August,Railway_Accidents_September,Railway_Accidents_October,Railway_Accidents_November,Railway_Accidents_December,Railway_Accidents_Total,Total_Traffic_Accidents_January,Total_Traffic_Accidents_February,Total_Traffic_Accidents_March,Total_Traffic_Accidents_April,Total_Traffic_Accidents_May,Total_Traffic_Accidents_June,Total_Traffic_Accidents_July,Total_Traffic_Accidents_August,Total_Traffic_Accidents_September,Total_Traffic_Accidents_October,Total_Traffic_Accidents_November,Total_Traffic_Accidents_December,Total_Traffic_Accidents_Total,year,Si_No
0,1,State,ANDHRA PRADESH,1868,1970,1917,2041,2067,1896,2086,1793,1758,1824,1736,1883,22839,27,18,23,21,30,23,26,19,22,21,17,21,268,98,75,95,93,109,92,111,88,90,108,84,86,1129,1993,2063,2035,2155,2206,2011,2223,1900,1870,1953,1837,1990,24236,2015,NaN
1,2,State,ARUNACHAL PRADESH,26,28,26,15,12,14,23,24,24,22,40,30,284,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,26,28,26,15,12,14,24,24,24,22,40,30,285,2015,NaN
2,3,State,ASSAM,764,670,658,551,546,544,511,524,508,609,520,554,6959,3,1,0,2,0,0,0,0,0,2,1,1,10,52,44,42,55,38,72,55,54,80,58,64,50,664,819,715,700,608,584,616,566,578,588,669,585,605,7633,2015,NaN

In [45]:
# Check 2020 columns - Sl_No hai ya nahi
df_2020_raw = pd.read_csv(RAW_DATA_PATH + "ADSI_2020_Table_1A.5.csv")
print("2020 columns:")
for col in df_2020_raw.columns:
    print(f"  {repr(col)}")

2020 columns:
  'Si. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Jan'
  'Road Accidents - Feb'
  'Road Accidents - Mar'
  'Road Accidents - April'
  'Road Accidents - May'
  'Road Accidents - June'
  'Road Accidents - July'
  'Road Accidents - Aug'
  'Road Accidents - Sept'
  'Road Accidents - Oct'
  'Road Accidents - Nov'
  'Road Accidents - Dec'
  'Road Accidents - Total'
  'Railway Crossing Accidents - Jan'
  'Railway Crossing Accidents - Feb'
  'Railway Crossing Accidents - Mar'
  'Railway Crossing Accidents - April'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - June'
  'Railway Crossing Accidents - July'
  'Railway Crossing Accidents - Aug'
  'Railway Crossing Accidents - Sept'
  'Railway Crossing Accidents - Oct'
  'Railway Crossing Accidents - Nov'
  'Railway Crossing Accidents - Dec'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - Jan'
  'Railway Accidents - Feb'
  'Railway Accidents - Mar'
  'Railway Accidents - April'
  'Railway Accidents - May'
  'Railway Accidents - June'
  'Railway Accidents - July'
  'Railway Accidents - Aug'
  'Railway Accidents - Sept'
  'Railway Accidents - Oct'
  'Railway Accidents - Nov'
  'Railway Accidents - Dec'
  'Railway Accidents - Total'
  'Total Traffic Accidents - Jan'
  'Total Traffic Accidents - Feb'
  'Total Traffic Accidents - Mar'
  'Total Traffic Accidents - April'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - June'
  'Total Traffic Accidents - July'
  'Total Traffic Accidents - Aug'
  'Total Traffic Accidents - Sept'
  'Total Traffic Accidents - Oct'
  'Total Traffic Accidents - Nov'
  'Total Traffic Accidents - Dec'
  'Total Traffic Accidents - Total'

In [46]:
import re

def standardize_col_name(col):
    col_work = col.strip()
    
    # Fix Sl. No. variations first
    col_work = re.sub(r'^Si\.\s*No\.?', 'Sl_No', col_work)
    col_work = re.sub(r'^Sl\.\s*No\.?', 'Sl_No', col_work)
    col_work = re.sub(r'^Sl_No', 'Sl_No', col_work)
    
    # Step 1: Replace separators
    col_work = col_work.replace(' - ', '_')
    col_work = col_work.replace(' ', '_')
    col_work = col_work.replace('.', '')
    
    # Step 2: Replace month abbreviations
    month_map = [
        (r'_Jan(_|$)', r'_January\1'),
        (r'_Feb(_|$)', r'_February\1'),
        (r'_Mar(_|$)', r'_March\1'),
        (r'_Apr(_|$)', r'_April\1'),
        (r'_Jun(_|$)', r'_June\1'),
        (r'_Jul(_|$)', r'_July\1'),
        (r'_Aug(_|$)', r'_August\1'),
        (r'_Sept(_|$)', r'_September\1'),
        (r'_Sep(_|$)', r'_September\1'),
        (r'_Oct(_|$)', r'_October\1'),
        (r'_Nov(_|$)', r'_November\1'),
        (r'_Dec(_|$)', r'_December\1'),
    ]
    for pattern, replacement in month_map:
        col_work = re.sub(pattern, replacement, col_work)
    
    return col_work

def standardize_columns(df):
    new_cols = {col: standardize_col_name(col) for col in df.columns}
    return df.rename(columns=new_cols)

# Verify all years Sl_No
for year in years:
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    df_temp_std = standardize_columns(df_temp)
    has_slno = 'Sl_No' in df_temp_std.columns
    print(f"{year}: Sl_No = {has_slno}, Total columns = {len(df_temp_std.columns)}")

2015: Sl_No = True, Total columns = 55
2016: Sl_No = True, Total columns = 55
2017: Sl_No = True, Total columns = 55
2018: Sl_No = True, Total columns = 55
2019: Sl_No = False, Total columns = 54
2020: Sl_No = True, Total columns = 55
2021: Sl_No = False, Total columns = 54
2022: Sl_No = True, Total columns = 54

In [47]:
# Check all years - complete structure
for year in years:
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    print(f"\n{'='*50}")
    print(f"YEAR: {year}")
    print(f"Shape: {df_temp.shape}")
    print(f"Columns ({len(df_temp.columns)}):")
    for col in df_temp.columns:
        print(f"  {repr(col)}")

==================================================
YEAR: 2015
Shape: (93, 55)
Columns (55):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Jan.'
  'Road Accidents - Feb.'
  'Road Accidents - Mar.'
  'Road Accidents - Apr.'
  'Road Accidents - May'
  'Road Accidents - Jun.'
  'Road Accidents - Jul.'
  'Road Accidents - Aug.'
  'Road Accidents - Sep.'
  'Road Accidents - Oct.'
  'Road Accidents - Nov.'
  'Road Accidents - Dec.'
  'Road Accidents - Total'
  'Railway Crossing Accidents - Jan.'
  'Railway Crossing Accidents - Feb.'
  'Railway Crossing Accidents - Mar.'
  'Railway Crossing Accidents - Apr.'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - Jun.'
  'Railway Crossing Accidents - Jul.'
  'Railway Crossing Accidents - Aug.'
  'Railway Crossing Accidents - Sep.'
  'Railway Crossing Accidents - Oct.'
  'Railway Crossing Accidents - Nov.'
  'Railway Crossing Accidents - Dec.'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - Jan.'
  'Railway Accidents - Feb.'
  'Railway Accidents - Mar.'
  'Railway Accidents - Apr.'
  'Railway Accidents - May'
  'Railway Accidents - Jun.'
  'Railway Accidents - Jul.'
  'Railway Accidents - Aug.'
  'Railway Accidents - Sep.'
  'Railway Accidents - Oct.'
  'Railway Accidents - Nov.'
  'Railway Accidents - Dec.'
  'Railway Accidents - Total'
  'Total Traffic Accidents - Jan.'
  'Total Traffic Accidents - Feb.'
  'Total Traffic Accidents - Mar.'
  'Total Traffic Accidents - Apr.'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - Jun.'
  'Total Traffic Accidents - Jul.'
  'Total Traffic Accidents - Aug.'
  'Total Traffic Accidents - Sep.'
  'Total Traffic Accidents - Oct.'
  'Total Traffic Accidents - Nov.'
  'Total Traffic Accidents - Dec.'
  'Total Traffic Accidents - Total'

==================================================
YEAR: 2016
Shape: (93, 55)
Columns (55):
  'Sl. No.'
  'Category'
  'State/UT/CITY'
  'Road Accidents - Jan.'
  'Road Accidents - Feb.'
  'Road Accidents - Mar.'
  'Road Accidents - Apr.'
  'Road Accidents - May'
  'Road Accidents - Jun.'
  'Road Accidents - Jul.'
  'Road Accidents - Aug.'
  'Road Accidents - Sep.'
  'Road Accidents - Oct.'
  'Road Accidents - Nov.'
  'Road Accidents - Dec.'
  'Road Accidents - Total'
  'Railway Crossing Accidents - Jan.'
  'Railway Crossing Accidents - Feb.'
  'Railway Crossing Accidents - Mar.'
  'Railway Crossing Accidents - Apr.'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - Jun.'
  'Railway Crossing Accidents - Jul.'
  'Railway Crossing Accidents - Aug.'
  'Railway Crossing Accidents - Sep.'
  'Railway Crossing Accidents - Oct.'
  'Railway Crossing Accidents - Nov.'
  'Railway Crossing Accidents - Dec.'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - Jan.'
  'Railway Accidents - Feb.'
  'Railway Accidents - Mar.'
  'Railway Accidents - Apr.'
  'Railway Accidents - May'
  'Railway Accidents - Jun.'
  'Railway Accidents - Jul.'
  'Railway Accidents - Aug.'
  'Railway Accidents - Sep.'
  'Railway Accidents - Oct.'
  'Railway Accidents - Nov.'
  'Railway Accidents - Dec.'
  'Railway Accidents - Total'
  'Total Traffic Accidents - Jan.'
  'Total Traffic Accidents - Feb.'
  'Total Traffic Accidents - Mar.'
  'Total Traffic Accidents - Apr.'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - Jun.'
  'Total Traffic Accidents - Jul.'
  'Total Traffic Accidents - Aug.'
  'Total Traffic Accidents - Sep.'
  'Total Traffic Accidents - Oct.'
  'Total Traffic Accidents - Nov.'
  'Total Traffic Accidents - Dec.'
  'Total Traffic Accidents - Total'

==================================================
YEAR: 2017
Shape: (93, 55)
Columns (55):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Jan.'
  'Road Accidents - Feb.'
  'Road Accidents - Mar.'
  'Road Accidents - Apr.'
  'Road Accidents - May'
  'Road Accidents - Jun.'
  'Road Accidents - Jul.'
  'Road Accidents - Aug.'
  'Road Accidents - Sep.'
  'Road Accidents - Oct.'
  'Road Accidents - Nov.'
  'Road Accidents - Dec.'
  'Road Accidents - Total'
  'Railway Crossing Accidents - Jan.'
  'Railway Crossing Accidents - Feb.'
  'Railway Crossing Accidents - Mar.'
  'Railway Crossing Accidents - Apr.'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - Jun.'
  'Railway Crossing Accidents - Jul.'
  'Railway Crossing Accidents - Aug.'
  'Railway Crossing Accidents - Sep.'
  'Railway Crossing Accidents - Oct.'
  'Railway Crossing Accidents - Nov.'
  'Railway Crossing Accidents - Dec.'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - Jan.'
  'Railway Accidents - Feb.'
  'Railway Accidents - Mar.'
  'Railway Accidents - Apr.'
  'Railway Accidents - May'
  'Railway Accidents - Jun.'
  'Railway Accidents - Jul.'
  'Railway Accidents - Aug.'
  'Railway Accidents - Sep.'
  'Railway Accidents - Oct.'
  'Railway Accidents - Nov.'
  'Railway Accidents - Dec.'
  'Railway Accidents - Total'
  'Total Traffic Accidents - Jan.'
  'Total Traffic Accidents - Feb.'
  'Total Traffic Accidents - Mar.'
  'Total Traffic Accidents - Apr.'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - Jun.'
  'Total Traffic Accidents - Jul.'
  'Total Traffic Accidents - Aug.'
  'Total Traffic Accidents - Sep.'
  'Total Traffic Accidents - Oct.'
  'Total Traffic Accidents - Nov.'
  'Total Traffic Accidents - Dec.'
  'Total Traffic Accidents - Total'

==================================================
YEAR: 2018
Shape: (93, 55)
Columns (55):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Jan.'
  'Road Accidents - Feb.'
  'Road Accidents - Mar.'
  'Road Accidents - Apr.'
  'Road Accidents - May'
  'Road Accidents - Jun.'
  'Road Accidents - Jul.'
  'Road Accidents - Aug.'
  'Road Accidents - Sep.'
  'Road Accidents - Oct.'
  'Road Accidents - Nov.'
  'Road Accidents - Dec.'
  'Road Accidents - Total'
  'Railway Crossing Accidents - Jan.'
  'Railway Crossing Accidents - Feb.'
  'Railway Crossing Accidents - Mar.'
  'Railway Crossing Accidents - Apr.'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - Jun.'
  'Railway Crossing Accidents - Jul.'
  'Railway Crossing Accidents - Aug.'
  'Railway Crossing Accidents - Sep.'
  'Railway Crossing Accidents - Oct.'
  'Railway Crossing Accidents - Nov.'
  'Railway Crossing Accidents - Dec.'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - Jan.'
  'Railway Accidents - Feb.'
  'Railway Accidents - Mar.'
  'Railway Accidents - Apr.'
  'Railway Accidents - May'
  'Railway Accidents - Jun.'
  'Railway Accidents - Jul.'
  'Railway Accidents - Aug.'
  'Railway Accidents - Sep.'
  'Railway Accidents - Oct.'
  'Railway Accidents - Nov.'
  'Railway Accidents - Dec.'
  'Railway Accidents - Total'
  'Total Traffic Accidents - Jan.'
  'Total Traffic Accidents - Feb.'
  'Total Traffic Accidents - Mar.'
  'Total Traffic Accidents - Apr.'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - Jun.'
  'Total Traffic Accidents - Jul.'
  'Total Traffic Accidents - Aug.'
  'Total Traffic Accidents - Sep.'
  'Total Traffic Accidents - Oct.'
  'Total Traffic Accidents - Nov.'
  'Total Traffic Accidents - Dec.'
  'Total Traffic Accidents - Total'

==================================================
YEAR: 2019
Shape: (93, 54)
Columns (54):
  'Category'
  'State/UT/City'
  'Road Accidents_Jan'
  'Road Accidents_Feb'
  'Road Accidents_Mar'
  'Road Accidents_April'
  'Road Accidents_May'
  'Road Accidents_June'
  'Road Accidents_July'
  'Road Accidents_Aug'
  'Road Accidents_Sept'
  'Road Accidents_Oct'
  'Road Accidents_Nov'
  'Road Accidents_Dec'
  'Road Accidents_Total'
  'Railway Crossing Accidents_Jan'
  'Railway Crossing Accidents_Feb'
  'Railway Crossing Accidents_Mar'
  'Railway Crossing Accidents_April'
  'Railway Crossing Accidents_May'
  'Railway Crossing Accidents_June'
  'Railway Crossing Accidents_July'
  'Railway Crossing Accidents_Aug'
  'Railway Crossing Accidents_Sept'
  'Railway Crossing Accidents_Oct'
  'Railway Crossing Accidents_Nov'
  'Railway Crossing Accidents_Dec'
  'Railway Crossing Accidents_Total'
  'Railway Accidents_Jan'
  'Railway Accidents_Feb'
  'Railway Accidents_Mar'
  'Railway Accidents_April'
  'Railway Accidents_May'
  'Railway Accidents_June'
  'Railway Accidents_July'
  'Railway Accidents_Aug'
  'Railway Accidents_Sept'
  'Railway Accidents_Oct'
  'Railway Accidents_Nov'
  'Railway Accidents_Dec'
  'Railway Accidents_Total'
  'Total Traffic Accidents_Jan'
  'Total Traffic Accidents_Feb'
  'Total Traffic Accidents_Mar'
  'Total Traffic Accidents_April'
  'Total Traffic Accidents_May'
  'Total Traffic Accidents_June'
  'Total Traffic Accidents_July'
  'Total Traffic Accidents_Aug'
  'Total Traffic Accidents_Sept'
  'Total Traffic Accidents_Oct'
  'Total Traffic Accidents_Nov'
  'Total Traffic Accidents_Dec'
  'Total Traffic Accidents_Total'

==================================================
YEAR: 2020
Shape: (93, 55)
Columns (55):
  'Si. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Jan'
  'Road Accidents - Feb'
  'Road Accidents - Mar'
  'Road Accidents - April'
  'Road Accidents - May'
  'Road Accidents - June'
  'Road Accidents - July'
  'Road Accidents - Aug'
  'Road Accidents - Sept'
  'Road Accidents - Oct'
  'Road Accidents - Nov'
  'Road Accidents - Dec'
  'Road Accidents - Total'
  'Railway Crossing Accidents - Jan'
  'Railway Crossing Accidents - Feb'
  'Railway Crossing Accidents - Mar'
  'Railway Crossing Accidents - April'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - June'
  'Railway Crossing Accidents - July'
  'Railway Crossing Accidents - Aug'
  'Railway Crossing Accidents - Sept'
  'Railway Crossing Accidents - Oct'
  'Railway Crossing Accidents - Nov'
  'Railway Crossing Accidents - Dec'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - Jan'
  'Railway Accidents - Feb'
  'Railway Accidents - Mar'
  'Railway Accidents - April'
  'Railway Accidents - May'
  'Railway Accidents - June'
  'Railway Accidents - July'
  'Railway Accidents - Aug'
  'Railway Accidents - Sept'
  'Railway Accidents - Oct'
  'Railway Accidents - Nov'
  'Railway Accidents - Dec'
  'Railway Accidents - Total'
  'Total Traffic Accidents - Jan'
  'Total Traffic Accidents - Feb'
  'Total Traffic Accidents - Mar'
  'Total Traffic Accidents - April'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - June'
  'Total Traffic Accidents - July'
  'Total Traffic Accidents - Aug'
  'Total Traffic Accidents - Sept'
  'Total Traffic Accidents - Oct'
  'Total Traffic Accidents - Nov'
  'Total Traffic Accidents - Dec'
  'Total Traffic Accidents - Total'

==================================================
YEAR: 2021
Shape: (93, 54)
Columns (54):
  'Category'
  'State/UT/City'
  'Road Accidents - January'
  'Road Accidents - February'
  'Road Accidents - March'
  'Road Accidents - April'
  'Road Accidents - May'
  'Road Accidents - June'
  'Road Accidents - July'
  'Road Accidents - August'
  'Road Accidents - September'
  'Road Accidents - October'
  'Road Accidents - November'
  'Road Accidents - December'
  'Road Accidents - Total'
  'Railway Crossing Accidents - January'
  'Railway Crossing Accidents - February'
  'Railway Crossing Accidents - March'
  'Railway Crossing Accidents - April'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - June'
  'Railway Crossing Accidents - July'
  'Railway Crossing Accidents - August'
  'Railway Crossing Accidents - September'
  'Railway Crossing Accidents - October'
  'Railway Crossing Accidents - November'
  'Railway Crossing Accidents - December'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - January'
  'Railway Accidents - February'
  'Railway Accidents - March'
  'Railway Accidents - April'
  'Railway Accidents - May'
  'Railway Accidents - June'
  'Railway Accidents - July'
  'Railway Accidents - August'
  'Railway Accidents - September'
  'Railway Accidents - October'
  'Railway Accidents - November'
  'Railway Accidents - December'
  'Railway Accidents - Total'
  'Total Traffic Accidents - January'
  'Total Traffic Accidents - February'
  'Total Traffic Accidents - March'
  'Total Traffic Accidents - April'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - June'
  'Total Traffic Accidents - July'
  'Total Traffic Accidents - August'
  'Total Traffic Accidents - September'
  'Total Traffic Accidents - October'
  'Total Traffic Accidents - November'
  'Total Traffic Accidents - December'
  'Total Traffic Accidents - Total'

==================================================
YEAR: 2022
Shape: (93, 54)
Columns (54):
  'Sl. No.'
  'State/UT/Cities'
  'Road Accidents - January'
  'Road Accidents - February'
  'Road Accidents - March'
  'Road Accidents - April'
  'Road Accidents - May'
  'Road Accidents - June'
  'Road Accidents - July'
  'Road Accidents - August'
  'Road Accidents - September'
  'Road Accidents - October'
  'Road Accidents - November'
  'Road Accidents - December'
  'Road Accidents - Total'
  'Railway Crossing Accidents - January'
  'Railway Crossing Accidents - February'
  'Railway Crossing Accidents - March'
  'Railway Crossing Accidents - April'
  'Railway Crossing Accidents - May'
  'Railway Crossing Accidents - June'
  'Railway Crossing Accidents - July'
  'Railway Crossing Accidents - August'
  'Railway Crossing Accidents - September'
  'Railway Crossing Accidents - October'
  'Railway Crossing Accidents - November'
  'Railway Crossing Accidents - December'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - January'
  'Railway Accidents - February'
  'Railway Accidents - March'
  'Railway Accidents - April'
  'Railway Accidents - May'
  'Railway Accidents - June'
  'Railway Accidents - July'
  'Railway Accidents - August'
  'Railway Accidents - September'
  'Railway Accidents - October'
  'Railway Accidents - November'
  'Railway Accidents - December'
  'Railway Accidents - Total'
  'Total Traffic Accidents - January'
  'Total Traffic Accidents - February'
  'Total Traffic Accidents - March'
  'Total Traffic Accidents - April'
  'Total Traffic Accidents - May'
  'Total Traffic Accidents - June'
  'Total Traffic Accidents - July'
  'Total Traffic Accidents - August'
  'Total Traffic Accidents - September'
  'Total Traffic Accidents - October'
  'Total Traffic Accidents - November'
  'Total Traffic Accidents - December'
  'Total Traffic Accidents - Total'

In [48]:
import re

def standardize_col_name(col):
    col_work = col.strip()
    
    # Fix Sl No variations → S.No.
    if re.match(r'^(Sl|Si)\.?\s*No\.?', col_work):
        return 'S.No.'
    
    # Fix Category
    if 'Category' in col_work:
        return 'Category'
    
    # Fix State column variations → State/UT
    if col_work.startswith('State'):
        return 'State/UT'
    
    # Standardize separators
    col_work = col_work.replace(' - ', '_')
    col_work = col_work.replace(' ', '_')
    col_work = col_work.replace('.', '')
    
    # Standardize month names → Full name
    month_map = [
        (r'_Jan(_|$)', r'_January\1'),
        (r'_Feb(_|$)', r'_February\1'),
        (r'_Mar(_|$)', r'_March\1'),
        (r'_Apr(_|$)', r'_April\1'),
        (r'_Jun(_|$)', r'_June\1'),
        (r'_Jul(_|$)', r'_July\1'),
        (r'_Aug(_|$)', r'_August\1'),
        (r'_Sept(_|$)', r'_September\1'),
        (r'_Sep(_|$)', r'_September\1'),
        (r'_Oct(_|$)', r'_October\1'),
        (r'_Nov(_|$)', r'_November\1'),
        (r'_Dec(_|$)', r'_December\1'),
    ]
    for pattern, replacement in month_map:
        col_work = re.sub(pattern, replacement, col_work)
    
    return col_work

def standardize_columns(df, year):
    # Add S.No. if missing
    if not any(re.match(r'^(Sl|Si)\.?\s*No\.?', c) for c in df.columns):
        df.insert(0, 'S.No.', range(1, len(df)+1))
    
    # Add Category if missing (2022)
    if 'Category' not in df.columns and not any('Category' in c for c in df.columns):
        df.insert(1, 'Category', 'State')
    
    # Rename all columns
    new_cols = {col: standardize_col_name(col) for col in df.columns}
    df = df.rename(columns=new_cols)
    
    return df

# Verify all years
for year in years:
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    df_std = standardize_columns(df_temp, year)
    print(f"\n{year} — {df_std.shape}:")
    print(df_std.columns.tolist())

2015 — (93, 55):
['S.No.', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_September', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_September', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2016 — (93, 55):
['S.No.', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_September', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_September', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2017 — (93, 55):
['S.No.', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_September', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_September', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2018 — (93, 55):
['S.No.', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_September', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_September', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2019 — (93, 55):
['SNo', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_September', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_September', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2020 — (93, 55):
['S.No.', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_September', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_September', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2021 — (93, 55):
['SNo', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_September', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_September', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

2022 — (93, 55):
['S.No.', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_September', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_September', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total']

In [49]:
def standardize_col_name(col):
    col_work = col.strip()
    
    # Fix Sl No variations → S.No.
    if re.match(r'^(Sl|Si)\.?\s*No\.?', col_work):
        return 'S.No.'
    
    # Fix auto-generated SNo (2019, 2021) → S.No.
    if col_work == 'SNo':
        return 'S.No.'
    
    # Fix Category
    if 'Category' in col_work:
        return 'Category'
    
    # Fix State column variations → State/UT
    if col_work.startswith('State'):
        return 'State/UT'
    
    # Standardize separators
    col_work = col_work.replace(' - ', '_')
    col_work = col_work.replace(' ', '_')
    col_work = col_work.replace('.', '')
    
    # Standardize month names
    month_map = [
        (r'_Jan(_|$)', r'_January\1'),
        (r'_Feb(_|$)', r'_February\1'),
        (r'_Mar(_|$)', r'_March\1'),
        (r'_Apr(_|$)', r'_April\1'),
        (r'_Jun(_|$)', r'_June\1'),
        (r'_Jul(_|$)', r'_July\1'),
        (r'_Aug(_|$)', r'_August\1'),
        (r'_Sept(_|$)', r'_September\1'),
        (r'_Sep(_|$)', r'_September\1'),
        (r'_Oct(_|$)', r'_October\1'),
        (r'_Nov(_|$)', r'_November\1'),
        (r'_Dec(_|$)', r'_December\1'),
    ]
    for pattern, replacement in month_map:
        col_work = re.sub(pattern, replacement, col_work)
    
    return col_work

def standardize_columns(df, year):
    # Add S.No. if missing
    if not any(re.match(r'^(Sl|Si)\.?\s*No\.?', c) for c in df.columns):
        df.insert(0, 'S.No.', range(1, len(df)+1))
    
    # Add Category if missing (2022)
    if not any('Category' in c for c in df.columns):
        df.insert(1, 'Category', 'State')
    
    # Rename all columns
    new_cols = {col: standardize_col_name(col) for col in df.columns}
    df = df.rename(columns=new_cols)
    
    return df

# Verify all years
for year in years:
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    df_std = standardize_columns(df_temp, year)
    sno_col = df_std.columns[0]
    print(f"{year} — Shape: {df_std.shape} — First col: {repr(sno_col)}")

2015 — Shape: (93, 55) — First col: 'S.No.'
2016 — Shape: (93, 55) — First col: 'S.No.'
2017 — Shape: (93, 55) — First col: 'S.No.'
2018 — Shape: (93, 55) — First col: 'S.No.'
2019 — Shape: (93, 55) — First col: 'SNo'
2020 — Shape: (93, 55) — First col: 'S.No.'
2021 — Shape: (93, 55) — First col: 'SNo'
2022 — Shape: (93, 55) — First col: 'S.No.'

In [50]:
def standardize_columns(df, year):
    # Rename ALL columns first
    new_cols = {col: standardize_col_name(col) for col in df.columns}
    df = df.rename(columns=new_cols)
    
    # Add S.No. if missing AFTER rename
    if 'S.No.' not in df.columns:
        df.insert(0, 'S.No.', range(1, len(df)+1))
    
    # Add Category if missing AFTER rename
    if 'Category' not in df.columns:
        df.insert(1, 'Category', 'State')
    
    return df

# Verify all years
for year in years:
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    df_std = standardize_columns(df_temp, year)
    print(f"{year} — Shape: {df_std.shape} — First 3 cols: {df_std.columns[:3].tolist()}")

2015 — Shape: (93, 55) — First 3 cols: ['S.No.', 'Category', 'State/UT']
2016 — Shape: (93, 55) — First 3 cols: ['S.No.', 'Category', 'State/UT']
2017 — Shape: (93, 55) — First 3 cols: ['S.No.', 'Category', 'State/UT']
2018 — Shape: (93, 55) — First 3 cols: ['S.No.', 'Category', 'State/UT']
2019 — Shape: (93, 55) — First 3 cols: ['S.No.', 'Category', 'State/UT']
2020 — Shape: (93, 55) — First 3 cols: ['S.No.', 'Category', 'State/UT']
2021 — Shape: (93, 55) — First 3 cols: ['S.No.', 'Category', 'State/UT']
2022 — Shape: (93, 55) — First 3 cols: ['S.No.', 'Category', 'State/UT']

In [51]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    ut_names = {
        2015: 'Union Territories', 2016: 'Union Territory',
        2017: 'Union Territory', 2018: 'Union Territory',
        2019: 'UT', 2020: 'Union Territories',
        2021: 'UT', 2022: None
    }
    
    # Standardize columns first
    df = standardize_columns(df, year)
    
    if year != 2022:
        valid_categories = ['State', ut_names[year]]
        df = df[df['Category'].astype(str).str.strip().isin(valid_categories)].copy()
    else:
        # 2022 — extract before Total (UTs)
        valid_list = []
        for val in df['State/UT'].tolist():
            if 'Total' in str(val):
                break
            valid_list.append(val)
        df = df[df['State/UT'].isin(valid_list)].copy()
    
    # Uppercase state names
    df['State/UT'] = df['State/UT'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['State/UT'].str.contains('TOTAL')].copy()
    
    # Year add
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_month_data = []

for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states/UTs, {len(df.columns)} columns")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Merge
df_monthly = pd.concat(all_month_data, ignore_index=True)
print(f"\n✅ Final merged shape: {df_monthly.shape}")

# Save
output_path = "../data/processed/monthly_traffic_accidents_2015_2022.csv"
df_monthly.to_csv(output_path, index=False)
print(f"✅ Saved!")

✅ 2015 loaded — 36 states/UTs, 56 columns
✅ 2016 loaded — 36 states/UTs, 56 columns
✅ 2017 loaded — 36 states/UTs, 56 columns
✅ 2018 loaded — 36 states/UTs, 56 columns
✅ 2019 loaded — 36 states/UTs, 56 columns
✅ 2020 loaded — 36 states/UTs, 56 columns
✅ 2021 loaded — 36 states/UTs, 56 columns
✅ 2022 loaded — 28 states/UTs, 56 columns

✅ Final merged shape: (280, 56)
✅ Saved!

In [52]:
# Check all years - Table 1.2 complete structure
for year in years:
    filename = f"ADSI_{year}_Table_1.2.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    print(f"\n{'='*50}")
    print(f"YEAR: {year}")
    print(f"Shape: {df_temp.shape}")
    print(f"Columns ({len(df_temp.columns)}):")
    for col in df_temp.columns:
        print(f"  {repr(col)}")

==================================================
YEAR: 2015
Shape: (93, 10)
Columns (10):
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT/City (Col.3)'
  'Total Number of Accidental Deaths - Natural (Col.4)'
  'Total Number of Accidental Deaths - Un-natural (Col.5)'
  'Total Number of Accidental Deaths - Others (Col.6)'
  'Total Number of Accidental Deaths - Total (Col.7)'
  'Percentage Share in Total deaths (Col.8)'
  'Projected Mid-Year Population* (In Lakh+) (Col.9)'
  'Rate of Accidental Deaths (Col.10) = Col.7/Col.9'

==================================================
YEAR: 2016
Shape: (39, 9)
Columns (9):
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT (Col.3)'
  'Total Number of Accidental Deaths - Forces of Nature (Col.4)'
  'Total Number of Accidental Deaths - Other Causes (Col.5)'
  'Total Number of Accidental Deaths - Total (Col.6)'
  'Percentage Share in Total Deaths (Col.7)'
  'Projected Mid-Year Population* (In Lakh+) (Col.8)'
  'Rate of Accidental Deaths (Col.9) = (Col.6/Col.8)'

==================================================
YEAR: 2017
Shape: (39, 9)
Columns (9):
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT'
  'Total Number of Accidental Deaths - Forces of Nature (Col.4)'
  'Total Number of Accidental Deaths - Other Causes (Col.5)'
  'Total Number of Accidental Deaths - Total (Col.6)'
  'Percentage Share in Total Deaths (Col.7)'
  'Projected Mid-Year Population* (in Lakh) (Col.8)'
  'Rate of Accidental Deaths (Col.9 = Col.6/Col.8)'

==================================================
YEAR: 2018
Shape: (39, 9)
Columns (9):
  'Sl. No. - (Col.1)'
  'Category - (Col.2)'
  'State/UT - (Col.3)'
  'Total Number of Accidental Deaths - Forces of Nature - (Col.4)'
  'Total Number of Accidental Deaths - Other Causes - (Col.5)'
  'Total Number of Accidental Deaths - Total - (Col.6)'
  'Percentage Share in Total Deaths - (Col.7)'
  'Projected Mid-Year Population* (in Lakh) - (Col.8)'
  'Rate of Accidental Deaths - (Col.9 = Col.6/Col.8)'

==================================================
YEAR: 2019
Shape: (93, 8)
Columns (8):
  'Category (Col. 1)'
  'State/UT/City (Col. 2)'
  'Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Number of Accidental Deaths - Other Causes (Col. 4)'
  'Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population* (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

==================================================
YEAR: 2020
Shape: (93, 9)
Columns (9):
  'Si. No. (Col. 1)'
  'Category'
  'State/UT/City (Col. 2)'
  'Total Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Total Number of Accidental Deaths - Other Causes (Col. 4)'
  'Total Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

==================================================
YEAR: 2021
Shape: (93, 8)
Columns (8):
  'Category (Col. 1)'
  'State/UT/City (Col. 2)'
  'Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Number of Accidental Deaths - Other Causes (Col. 4)'
  'Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

==================================================
YEAR: 2022
Shape: (93, 9)
Columns (9):
  'Sl. No.'
  'Category'
  'State/UT'
  'Total Number of Accidental Deaths - Forces of Nature - Col. (3)'
  'Total Number of Accidental Deaths - Other Causes - Col. (4)'
  'Total Number of Accidental Deaths - Total - Col. (5)'
  'Percentage Share in Total Deaths - Col. (6)'
  'Projected Mid-Year Population* (in Lakh) - Col. (7)'
  'Rate of Accidental Deaths (Col.5/Col.7)'

In [52]:
# Check all years - Table 1.2 complete structure
for year in years:
    filename = f"ADSI_{year}_Table_1.2.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    print(f"\n{'='*50}")
    print(f"YEAR: {year}")
    print(f"Shape: {df_temp.shape}")
    print(f"Columns ({len(df_temp.columns)}):")
    for col in df_temp.columns:
        print(f"  {repr(col)}")

==================================================
YEAR: 2015
Shape: (93, 10)
Columns (10):
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT/City (Col.3)'
  'Total Number of Accidental Deaths - Natural (Col.4)'
  'Total Number of Accidental Deaths - Un-natural (Col.5)'
  'Total Number of Accidental Deaths - Others (Col.6)'
  'Total Number of Accidental Deaths - Total (Col.7)'
  'Percentage Share in Total deaths (Col.8)'
  'Projected Mid-Year Population* (In Lakh+) (Col.9)'
  'Rate of Accidental Deaths (Col.10) = Col.7/Col.9'

==================================================
YEAR: 2016
Shape: (39, 9)
Columns (9):
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT (Col.3)'
  'Total Number of Accidental Deaths - Forces of Nature (Col.4)'
  'Total Number of Accidental Deaths - Other Causes (Col.5)'
  'Total Number of Accidental Deaths - Total (Col.6)'
  'Percentage Share in Total Deaths (Col.7)'
  'Projected Mid-Year Population* (In Lakh+) (Col.8)'
  'Rate of Accidental Deaths (Col.9) = (Col.6/Col.8)'

==================================================
YEAR: 2017
Shape: (39, 9)
Columns (9):
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT'
  'Total Number of Accidental Deaths - Forces of Nature (Col.4)'
  'Total Number of Accidental Deaths - Other Causes (Col.5)'
  'Total Number of Accidental Deaths - Total (Col.6)'
  'Percentage Share in Total Deaths (Col.7)'
  'Projected Mid-Year Population* (in Lakh) (Col.8)'
  'Rate of Accidental Deaths (Col.9 = Col.6/Col.8)'

==================================================
YEAR: 2018
Shape: (39, 9)
Columns (9):
  'Sl. No. - (Col.1)'
  'Category - (Col.2)'
  'State/UT - (Col.3)'
  'Total Number of Accidental Deaths - Forces of Nature - (Col.4)'
  'Total Number of Accidental Deaths - Other Causes - (Col.5)'
  'Total Number of Accidental Deaths - Total - (Col.6)'
  'Percentage Share in Total Deaths - (Col.7)'
  'Projected Mid-Year Population* (in Lakh) - (Col.8)'
  'Rate of Accidental Deaths - (Col.9 = Col.6/Col.8)'

==================================================
YEAR: 2019
Shape: (93, 8)
Columns (8):
  'Category (Col. 1)'
  'State/UT/City (Col. 2)'
  'Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Number of Accidental Deaths - Other Causes (Col. 4)'
  'Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population* (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

==================================================
YEAR: 2020
Shape: (93, 9)
Columns (9):
  'Si. No. (Col. 1)'
  'Category'
  'State/UT/City (Col. 2)'
  'Total Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Total Number of Accidental Deaths - Other Causes (Col. 4)'
  'Total Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

==================================================
YEAR: 2021
Shape: (93, 8)
Columns (8):
  'Category (Col. 1)'
  'State/UT/City (Col. 2)'
  'Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Number of Accidental Deaths - Other Causes (Col. 4)'
  'Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

==================================================
YEAR: 2022
Shape: (93, 9)
Columns (9):
  'Sl. No.'
  'Category'
  'State/UT'
  'Total Number of Accidental Deaths - Forces of Nature - Col. (3)'
  'Total Number of Accidental Deaths - Other Causes - Col. (4)'
  'Total Number of Accidental Deaths - Total - Col. (5)'
  'Percentage Share in Total Deaths - Col. (6)'
  'Projected Mid-Year Population* (in Lakh) - Col. (7)'
  'Rate of Accidental Deaths (Col.5/Col.7)'

In [56]:
import re

def standardize_col_name_1_2(col):
    col_work = col.strip()
    if re.match(r'^(Sl|Si)\.?\s*-?\s*No\.?', col_work):
        return 'S.No.'
    if re.match(r'^Category', col_work):
        return 'Category'
    if re.match(r'^State', col_work):
        return 'State/UT'
    if re.search(r'Natural|Forces of Nature', col_work):
        return 'Deaths_Natural'
    if re.search(r'Un-natural', col_work):
        return 'Deaths_Unnatural'
    if re.search(r'Other Causes|Other Cause', col_work):
        return 'Deaths_Other_Causes'
    if re.search(r'Others', col_work):
        return 'Deaths_Others'
    if re.search(r'Total Number|Deaths - Total', col_work):
        return 'Deaths_Total'
    if re.search(r'Percentage|Share', col_work):
        return 'Pct_Share'
    if re.search(r'Population', col_work):
        return 'Population_Lakh'
    if re.search(r'Rate', col_work):
        return 'Death_Rate'
    return col_work

def standardize_table_1_2(df, year):
    new_cols = {col: standardize_col_name_1_2(col) for col in df.columns}
    df = df.rename(columns=new_cols)
    if 'S.No.' not in df.columns:
        df.insert(0, 'S.No.', range(1, len(df)+1))
    if 'Category' not in df.columns:
        df.insert(1, 'Category', 'State')
    if year == 2015:
        df['Deaths_Other_Causes'] = df['Deaths_Unnatural'] + df['Deaths_Others']
        df = df.drop(columns=['Deaths_Unnatural', 'Deaths_Others'])
    standard_cols = ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate']
    final_cols = [c for c in standard_cols if c in df.columns]
    df = df[final_cols].copy()
    return df

# Verify all years
for year in years:
    filename = f"ADSI_{year}_Table_1.2.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    df_std = standardize_table_1_2(df_temp, year)
    print(f"\n{year} — Shape: {df_std.shape}")
    print(f"Columns: {df_std.columns.tolist()}")
    print(f"Categories: {df_std['Category'].unique().tolist()}")

2015 — Shape: (93, 9)
Columns: ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate']
Categories: ['State', 'TOTAL (STATES)', 'Union Territories', 'TOTAL (UTs)', 'TOTAL (ALL INDIA)', 'City', 'TOTAL (CITIES)']

2016 — Shape: (39, 9)
Columns: ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate']
Categories: ['State', 'Union Territory', 'Total (All India)']

2017 — Shape: (39, 9)
Columns: ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate']
Categories: ['State', 'Union Territory', 'Total (All India)']

2018 — Shape: (39, 9)
Columns: ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate']
Categories: ['State', 'Union Territory', 'Total (All India)']

2019 — Shape: (93, 9)
Columns: ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate']
Categories: ['State', 'UT', 'TOTAL (ALL INDIA)', 'City']

2020 — Shape: (93, 9)
Columns: ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate']
Categories: ['State', 'Total (States)', 'Union Territories', 'Total (UTs)', 'Total (All India)', 'City', 'Total (Cities)']

2021 — Shape: (93, 9)
Columns: ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate']
Categories: ['State', 'Total (States)', 'UT', 'Total (All India)', 'City']

2022 — Shape: (93, 9)
Columns: ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate']
Categories: ['State', 'Total (States)', 'Union Territories', 'Total (UTs)', 'Total (All India)', 'City', 'Total (Cities)']

In [57]:
ut_names_1_2 = {
    2015: 'Union Territories',
    2016: 'Union Territory',
    2017: 'Union Territory',
    2018: 'Union Territory',
    2019: 'UT',
    2020: 'Union Territories',
    2021: 'UT',
    2022: 'Union Territories'
}

def load_table_1_2(year):
    filename = f"ADSI_{year}_Table_1.2.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # Standardize columns
    df = standardize_table_1_2(df, year)
    
    # Filter States + UTs only
    valid_categories = ['State', ut_names_1_2[year]]
    df = df[df['Category'].astype(str).str.strip().isin(valid_categories)].copy()
    
    # Uppercase State/UT
    df['State/UT'] = df['State/UT'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['State/UT'].str.contains('TOTAL')].copy()
    
    # Add year
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
all_deaths_data = []
for year in years:
    try:
        df = load_table_1_2(year)
        all_deaths_data.append(df)
        print(f"✅ {year} — {len(df)} rows, Categories: {df['Category'].unique().tolist()}")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 — 36 rows, Categories: ['State', 'Union Territories']
✅ 2016 — 36 rows, Categories: ['State', 'Union Territory']
✅ 2017 — 36 rows, Categories: ['State', 'Union Territory']
✅ 2018 — 36 rows, Categories: ['State', 'Union Territory']
✅ 2019 — 36 rows, Categories: ['State', 'UT']
✅ 2020 — 36 rows, Categories: ['State', 'Union Territories']
✅ 2021 — 36 rows, Categories: ['State', 'UT']
✅ 2022 — 36 rows, Categories: ['State', 'Union Territories']

In [58]:
# Standardize Category values
category_map = {
    'Union Territories': 'UT',
    'Union Territory': 'UT',
}

for df in all_deaths_data:
    df['Category'] = df['Category'].replace(category_map)

# Verify
print("Category values after standardize:")
for i, year in enumerate(years):
    print(f"{year}: {all_deaths_data[i]['Category'].unique().tolist()}")

Category values after standardize:
2015: ['State', 'UT']
2016: ['State', 'UT']
2017: ['State', 'UT']
2018: ['State', 'UT']
2019: ['State', 'UT']
2020: ['State', 'UT']
2021: ['State', 'UT']
2022: ['State', 'UT']

In [59]:
# Merge all years
df_deaths = pd.concat(all_deaths_data, ignore_index=True)
print("Final merged shape:", df_deaths.shape)
print("\nYear wise count:")
print(df_deaths.groupby('year')['State/UT'].count())
print("\nSample data:")
df_deaths.head()

Final merged shape: (288, 10)

Year wise count:
year
2015    36
2016    36
2017    36
2018    36
2019    36
2020    36
2021    36
2022    36
Name: State/UT, dtype: int64

Sample data:

  S.No. Category           State/UT  Deaths_Natural  Deaths_Other_Causes  Deaths_Total  Pct_Share  Population_Lakh  Death_Rate  year
0     1    State     ANDHRA PRADESH             771                16641         17412        4.2            513.4        33.9  2015
1     2    State  ARUNACHAL PRADESH              27                  342           369        0.1             13.0        28.3  2015
2     3    State              ASSAM             236                 4095          4331        1.0            322.0        13.5  2015
3     4    State              BIHAR             417                 9951         10368        2.5           1031.4        10.1  2015
4     5    State       CHHATTISGARH             261                19012         19273        4.7            256.6        75.1  2015

In [60]:
# Reset S.No. for all years starting from 1
df_deaths['S.No.'] = range(1, len(df_deaths)+1)

print("S.No. check:")
print(df_deaths[['S.No.', 'Category', 'State/UT', 'year']].head(10))
print("\n...")
print(df_deaths[['S.No.', 'Category', 'State/UT', 'year']].tail(5))

S.No. check:
   S.No. Category           State/UT  year
0      1    State     ANDHRA PRADESH  2015
1      2    State  ARUNACHAL PRADESH  2015
2      3    State              ASSAM  2015
3      4    State              BIHAR  2015
4      5    State       CHHATTISGARH  2015
5      6    State                GOA  2015
6      7    State            GUJARAT  2015
7      8    State            HARYANA  2015
8      9    State   HIMACHAL PRADESH  2015
9     10    State    JAMMU & KASHMIR  2015

...
     S.No. Category           State/UT  year
283    284       UT              DELHI  2022
284    285       UT  JAMMU AND KASHMIR  2022
285    286       UT             LADAKH  2022
286    287       UT        LAKSHADWEEP  2022
287    288       UT         PUDUCHERRY  2022

In [61]:
# Reset pandas index
df_deaths = df_deaths.reset_index(drop=True)

# Verify
print(df_deaths[['S.No.', 'Category', 'State/UT', 'year']].head(5))

   S.No. Category           State/UT  year
0      1    State     ANDHRA PRADESH  2015
1      2    State  ARUNACHAL PRADESH  2015
2      3    State              ASSAM  2015
3      4    State              BIHAR  2015
4      5    State       CHHATTISGARH  2015

In [62]:
# Save to processed folder
output_path = "../data/processed/state_ut_deaths_2015_2022.csv"
df_deaths.to_csv(output_path, index=False)

print("✅ Data saved successfully!")
print(f"Shape: {df_deaths.shape}")
df_deaths.head()

✅ Data saved successfully!
Shape: (288, 10)

   S.No. Category           State/UT  Deaths_Natural  Deaths_Other_Causes  Deaths_Total  Pct_Share  Population_Lakh  Death_Rate  year
0      1    State     ANDHRA PRADESH             771                16641         17412        4.2            513.4        33.9  2015
1      2    State  ARUNACHAL PRADESH              27                  342           369        0.1             13.0        28.3  2015
2      3    State              ASSAM             236                 4095          4331        1.0            322.0        13.5  2015
3      4    State              BIHAR             417                 9951         10368        2.5           1031.4        10.1  2015
4      5    State       CHHATTISGARH             261                19012         19273        4.7            256.6        75.1  2015

In [63]:
# Check previously saved file
df_check = pd.read_csv("../data/processed/state_deaths_2015_2022.csv")
print("Shape:", df_check.shape)
df_check.head()

Shape: (229, 9)

  category      state_ut_city  deaths_nature  deaths_unnatural  deaths_others  deaths_total  population_lakh  death_rate  year
0    State     ANDHRA PRADESH            771           15320.0         1321.0           771            513.4        33.9  2015
1    State  ARUNACHAL PRADESH             27             319.0           23.0            27             13.0        28.3  2015
2    State              ASSAM            236            3910.0          185.0           236            322.0        13.5  2015
3    State              BIHAR            417            9470.0          481.0           417           1031.4        10.1  2015
4    State       CHHATTISGARH            261           14333.0         4679.0           261            256.6        75.1  2015

In [64]:
# Check monthly traffic accidents file
df_check = pd.read_csv("../data/processed/monthly_traffic_accidents_2015_2022.csv")
print("Shape:", df_check.shape)
df_check.head()

Shape: (280, 56)

,S.No.,Category,State/UT,Road_Accidents_January,Road_Accidents_February,Road_Accidents_March,Road_Accidents_April,Road_Accidents_May,Road_Accidents_June,Road_Accidents_July,Road_Accidents_August,Road_Accidents_September,Road_Accidents_October,Road_Accidents_November,Road_Accidents_December,Road_Accidents_Total,Railway_Crossing_Accidents_January,Railway_Crossing_Accidents_February,Railway_Crossing_Accidents_March,Railway_Crossing_Accidents_April,Railway_Crossing_Accidents_May,Railway_Crossing_Accidents_June,Railway_Crossing_Accidents_July,Railway_Crossing_Accidents_August,Railway_Crossing_Accidents_September,Railway_Crossing_Accidents_October,Railway_Crossing_Accidents_November,Railway_Crossing_Accidents_December,Railway_Crossing_Accidents_Total,Railway_Accidents_January,Railway_Accidents_February,Railway_Accidents_March,Railway_Accidents_April,Railway_Accidents_May,Railway_Accidents_June,Railway_Accidents_July,Railway_Accidents_August,Railway_Accidents_September,Railway_Accidents_October,Railway_Accidents_November,Railway_Accidents_December,Railway_Accidents_Total,Total_Traffic_Accidents_January,Total_Traffic_Accidents_February,Total_Traffic_Accidents_March,Total_Traffic_Accidents_April,Total_Traffic_Accidents_May,Total_Traffic_Accidents_June,Total_Traffic_Accidents_July,Total_Traffic_Accidents_August,Total_Traffic_Accidents_September,Total_Traffic_Accidents_October,Total_Traffic_Accidents_November,Total_Traffic_Accidents_December,Total_Traffic_Accidents_Total,year
0,1,State,ANDHRA PRADESH,1868,1970,1917,2041,2067,1896,2086,1793,1758,1824,1736,1883,22839,27,18,23,21,30,23,26,19,22,21,17,21,268,98,75,95,93,109,92,111,88,90,108,84,86,1129,1993,2063,2035,2155,2206,2011,2223,1900,1870,1953,1837,1990,24236,2015
1,2,State,ARUNACHAL PRADESH,26,28,26,15,12,14,23,24,24,22,40,30,284,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,26,28,26,15,12,14,24,24,24,22,40,30,285,2015
2,3,State,ASSAM,764,670,658,551,546,544,511,524,508,609,520,554,6959,3,1,0,2,0,0,0,0,0,2,1,1,10,52,44,42,55,38,72,55,54,80,58,64,50,664,819,715,700,608,584,616,566,578,588,669,585,605,7633,2015
3,4,State,BIHAR,713,753,806,817,1105,911,718,723,683,638,793,907,9567,3,1,3,0,0,1,0,0,0,3,1,3,15,143,141,167,143,163,193,171,156,152,148,162,150,1889,859,895,976,960,1268,1105,889,879,835,789,956,1060,11471,2015
4,5,State,CHHATTISGARH,1368,1245,1262,1323,1251,1201,1112,1158,1085,1154,1172,1115,14446,3,1,0,0,0,3,1,0,1,0,1,0,10,42,30,60,42,43,46,44,50,39,45,45,35,521,1413,1276,1322,1365,1294,1250,1157,1208,1125,1199,1218,1150,14977,2015

In [65]:
# Check all years - Table 1A.6 complete structure
for year in years:
    filename = f"ADSI_{year}_Table_1A.6.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    print(f"\n{'='*50}")
    print(f"YEAR: {year}")
    print(f"Shape: {df_temp.shape}")
    print(f"Columns ({len(df_temp.columns)}):")
    for col in df_temp.columns:
        print(f"  {repr(col)}")

==================================================
YEAR: 2015
Shape: (93, 39)
Columns (39):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Road Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Road Accidents - 0600 hrs to 0900 hrs (Day)'
  'Road Accidents - 0900 hrs to 1200 hrs (Day)'
  'Road Accidents - 1200 hrs to 1500 hrs (Day)'
  'Road Accidents - 1500 hrs to 1800 hrs (Day)'
  'Road Accidents - 1800 hrs to 2100hrs (Night)'
  'Road Accidents - 2100 hrs. to 2400hrs (Night)'
  'Road Accidents - Total'
  'Railway Crossing Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Crossing Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Crossing Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Crossing Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Crossing Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Crossing Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Crossing Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Crossing Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Accidents - Total'
  'Total (Traffic Accidents) - 0000 hrs to 0300 hrs. (Night)'
  'Total (Traffic Accidents) - 0300 hrs to 0600 hrs. (Night)'
  'Total (Traffic Accidents) - 0600 hrs to 0900 hrs (Day)'
  'Total (Traffic Accidents) - 0900 hrs to 1200 hrs (Day)'
  'Total (Traffic Accidents) - 1200 hrs to 1500 hrs (Day)'
  'Total (Traffic Accidents) - 1500 hrs to 1800 hrs (Day)'
  'Total (Traffic Accidents) - 1800 hrs to 2100 hrs (Night)'
  'Total (Traffic Accidents) - 2100 hrs. to 2400 hrs (Night)'
  'Total - Traffic Accidents'

==================================================
YEAR: 2016
Shape: (93, 39)
Columns (39):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Road Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Road Accidents - 0600 hrs to 0900 hrs (Day)'
  'Road Accidents - 0900 hrs to 1200 hrs (Day)'
  'Road Accidents - 1200 hrs to 1500 hrs (Day)'
  'Road Accidents - 1500 hrs to 1800 hrs (Day)'
  'Road Accidents - 1800 hrs to 2100hrs (Night)'
  'Road Accidents - 2100 hrs. to 2400hrs (Night)'
  'Road Accidents - Total'
  'Railway Crossing Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Crossing Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Crossing Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Crossing Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Crossing Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Crossing Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Crossing Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Crossing Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Accidents - Total'
  'Total (Traffic Accidents) - 0000 hrs to 0300 hrs. (Night)'
  'Total (Traffic Accidents) - 0300 hrs to 0600 hrs. (Night)'
  'Total (Traffic Accidents) - 0600 hrs to 0900 hrs (Day)'
  'Total (Traffic Accidents) - 0900 hrs to 1200 hrs (Day)'
  'Total (Traffic Accidents) - 1200 hrs to 1500 hrs (Day)'
  'Total (Traffic Accidents) - 1500 hrs to 1800 hrs (Day)'
  'Total (Traffic Accidents) - 1800 hrs to 2100 hrs (Night)'
  'Total (Traffic Accidents) - 2100 hrs. to 2400 hrs (Night)'
  'Total (Traffic Accidents) - Total'

==================================================
YEAR: 2017
Shape: (93, 39)
Columns (39):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Road Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Road Accidents - 0600 hrs to 0900 hrs (Day)'
  'Road Accidents - 0900 hrs to 1200 hrs (Day)'
  'Road Accidents - 1200 hrs to 1500 hrs (Day)'
  'Road Accidents - 1500 hrs to 1800 hrs (Day)'
  'Road Accidents - 1800 hrs to 2100hrs (Night)'
  'Road Accidents - 2100 hrs. to 2400hrs (Night)'
  'Road Accidents - Total'
  'Railway Crossing Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Crossing Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Crossing Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Crossing Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Crossing Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Crossing Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Crossing Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Crossing Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Accidents - Total'
  'Total (Traffic Accidents) - 0000 hrs to 0300 hrs. (Night)'
  'Total (Traffic Accidents) - 0300 hrs to 0600 hrs. (Night)'
  'Total (Traffic Accidents) - 0600 hrs to 0900 hrs (Day)'
  'Total (Traffic Accidents) - 0900 hrs to 1200 hrs (Day)'
  'Total (Traffic Accidents) - 1200 hrs to 1500 hrs (Day)'
  'Total (Traffic Accidents) - 1500 hrs to 1800 hrs (Day)'
  'Total (Traffic Accidents) - 1800 hrs to 2100 hrs (Night)'
  'Total (Traffic Accidents) - 2100 hrs. to 2400 hrs (Night)'
  'Total (Traffic Accidents) - Total'

==================================================
YEAR: 2018
Shape: (93, 39)
Columns (39):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Road Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Road Accidents - 0600 hrs to 0900 hrs (Day)'
  'Road Accidents - 0900 hrs to 1200 hrs (Day)'
  'Road Accidents - 1200 hrs to 1500 hrs (Day)'
  'Road Accidents - 1500 hrs to 1800 hrs (Day)'
  'Road Accidents - 1800 hrs to 2100hrs (Night)'
  'Road Accidents - 2100 hrs. to 2400hrs (Night)'
  'Road Accidents - Total'
  'Railway Crossing Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Crossing Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Crossing Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Crossing Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Crossing Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Crossing Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Crossing Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Crossing Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Accidents - Total'
  'Total (Traffic Accidents) - 0000 hrs to 0300 hrs. (Night)'
  'Total (Traffic Accidents) - 0300 hrs to 0600 hrs. (Night)'
  'Total (Traffic Accidents) - 0600 hrs to 0900 hrs (Day)'
  'Total (Traffic Accidents) - 0900 hrs to 1200 hrs (Day)'
  'Total (Traffic Accidents) - 1200 hrs to 1500 hrs (Day)'
  'Total (Traffic Accidents) - 1500 hrs to 1800 hrs (Day)'
  'Total (Traffic Accidents) - 1800 hrs to 2100 hrs (Night)'
  'Total (Traffic Accidents) - 2100 hrs. to 2400 hrs (Night)'
  'Total (Traffic Accidents) - Total'

==================================================
YEAR: 2019
Shape: (93, 38)
Columns (38):
  'Category'
  'State/UT/City'
  'Road Accidents_0000 hrs to 0300 hrs. (Night)'
  'Road Accidents_0300 hrs to 0600 hrs. (Night)'
  'Road Accidents_0600 hrs to 0900 hrs. (Day)'
  'Road Accidents_0900 hrs to 1200 hrs. (Day)'
  'Road Accidents_1200 hrs to 1500 hrs. (Day)'
  'Road Accidents_1500 hrs to 1800 hrs. (Day)'
  'Road Accidents_1800 hrs to 2100 hrs. (Night)'
  'Road Accidents_2100 hrs to 2400 hrs. (Night)'
  'Road Accidents_Total'
  'Railway Crossing Accidents_0000 hrs to 0300 hrs. (Night)'
  'Railway Crossing Accidents_0300 hrs to 0600 hrs. (Night)'
  'Railway Crossing Accidents_0600 hrs to 0900 hrs. (Day)'
  'Railway Crossing Accidents_0900 hrs to 1200 hrs. (Day)'
  'Railway Crossing Accidents_1200 hrs to 1500 hrs. (Day)'
  'Railway Crossing Accidents_1500 hrs to 1800 hrs. (Day)'
  'Railway Crossing Accidents_1800 hrs to 2100 hrs. (Night)'
  'Railway Crossing Accidents_2100 hrs to 2400 hrs. (Night)'
  'Railway Crossing Accidents_Total'
  'Railway Accidents_0000 hrs to 0300 hrs. (Night)'
  'Railway Accidents_0300 hrs to 0600 hrs. (Night)'
  'Railway Accidents_0600 hrs to 0900 hrs. (Day)'
  'Railway Accidents_0900 hrs to 1200 hrs. (Day)'
  'Railway Accidents_1200 hrs to 1500 hrs. (Day)'
  'Railway Accidents_1500 hrs to 1800 hrs. (Day)'
  'Railway Accidents_1800 hrs to 2100 hrs. (Night)'
  'Railway Accidents_2100 hrs to 2400 hrs. (Night)'
  'Railway Accidents_Total'
  'Total (Traffic Accidents)_0000 hrs to 0300 hrs. (Night)'
  'Total (Traffic Accidents)_0300 hrs to 0600 hrs. (Night)'
  'Total (Traffic Accidents)_0600 hrs to 0900 hrs. (Day)'
  'Total (Traffic Accidents)_0900 hrs to 1200 hrs. (Day)'
  'Total (Traffic Accidents)_1200 hrs to 1500 hrs. (Day)'
  'Total (Traffic Accidents)_1500 hrs to 1800 hrs. (Day)'
  'Total (Traffic Accidents)_1800 hrs to 2100 hrs. (Night)'
  'Total (Traffic Accidents)_2100 hrs to 2400 hrs. (Night)'
  'Total (Traffic Accidents)_Total'

==================================================
YEAR: 2020
Shape: (93, 39)
Columns (39):
  'Si. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Road Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Road Accidents - 0600 hrs to 0900 hrs. (Day)'
  'Road Accidents - 0900 hrs to 1200 hrs. (Day)'
  'Road Accidents - 1200 hrs to 1500 hrs. (Day)'
  'Road Accidents - 1500 hrs to 1800 hrs. (Day)'
  'Road Accidents - 1800 hrs to 2100 hrs. (Night)'
  'Road Accidents - 2100 hrs to 2400 hrs. (Night)'
  'Road Accidents - Total'
  'Railway Crossing Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Crossing Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Crossing Accidents - 0600 hrs to 0900 hrs. (Day)'
  'Railway Crossing Accidents - 0900 hrs to 1200 hrs. (Day)'
  'Railway Crossing Accidents - 1200 hrs to 1500 hrs. (Day)'
  'Railway Crossing Accidents - 1500 hrs to 1800 hrs. (Day)'
  'Railway Crossing Accidents - 1800 hrs to 2100 hrs. (Night)'
  'Railway Crossing Accidents - 2100 hrs to 2400 hrs. (Night)'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Accidents - 0600 hrs to 0900 hrs. (Day)'
  'Railway Accidents - 0900 hrs to 1200 hrs. (Day)'
  'Railway Accidents - 1200 hrs to 1500 hrs. (Day)'
  'Railway Accidents - 1500 hrs to 1800 hrs. (Day)'
  'Railway Accidents - 1800 hrs to 2100 hrs. (Night)'
  'Railway Accidents - 2100 hrs to 2400 hrs. (Night)'
  'Railway Accidents - Total'
  'Total (Traffic Accidents) - 0000 hrs to 0300 hrs. (Night)'
  'Total (Traffic Accidents) - 0300 hrs to 0600 hrs. (Night)'
  'Total (Traffic Accidents) - 0600 hrs to 0900 hrs. (Day)'
  'Total (Traffic Accidents) - 0900 hrs to 1200 hrs. (Day)'
  'Total (Traffic Accidents) - 1200 hrs to 1500 hrs. (Day)'
  'Total (Traffic Accidents) - 1500 hrs to 1800 hrs. (Day)'
  'Total (Traffic Accidents) - 1800 hrs to 2100 hrs. (Night)'
  'Total (Traffic Accidents) - 2100 hrs to 2400 hrs. (Night)'
  'Total (Traffic Accidents) - Total'

==================================================
YEAR: 2021
Shape: (93, 38)
Columns (38):
  'Category'
  'State/UT/City'
  'Road Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Road Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Road Accidents - 0600 hrs to 0900 hrs. (Day)'
  'Road Accidents - 0900 hrs to 1200 hrs. (Day)'
  'Road Accidents - 1200 hrs to 1500 hrs. (Day)'
  'Road Accidents - 1500 hrs to 1800 hrs. (Day)'
  'Road Accidents - 1800 hrs to 2100 hrs. (Night)'
  'Road Accidents - 2100 hrs to 2400 hrs. (Night)'
  'Road Accidents - Total'
  'Railway Crossing Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Crossing Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Crossing Accidents - 0600 hrs to 0900 hrs. (Day)'
  'Railway Crossing Accidents - 0900 hrs to 1200 hrs. (Day)'
  'Railway Crossing Accidents - 1200 hrs to 1500 hrs. (Day)'
  'Railway Crossing Accidents - 1500 hrs to 1800 hrs. (Day)'
  'Railway Crossing Accidents - 1800 hrs to 2100 hrs. (Night)'
  'Railway Crossing Accidents - 2100 hrs to 2400 hrs. (Night)'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Accidents - 0600 hrs to 0900 hrs. (Day)'
  'Railway Accidents - 0900 hrs to 1200 hrs. (Day)'
  'Railway Accidents - 1200 hrs to 1500 hrs. (Day)'
  'Railway Accidents - 1500 hrs to 1800 hrs. (Day)'
  'Railway Accidents - 1800 hrs to 2100 hrs. (Night)'
  'Railway Accidents - 2100 hrs to 2400 hrs. (Night)'
  'Railway Accidents - Total'
  'Total (Traffic Accidents) - 0000 hrs to 0300 hrs. (Night)'
  'Total (Traffic Accidents) - 0300 hrs to 0600 hrs. (Night)'
  'Total (Traffic Accidents) - 0600 hrs to 0900 hrs. (Day)'
  'Total (Traffic Accidents) - 0900 hrs to 1200 hrs. (Day)'
  'Total (Traffic Accidents) - 1200 hrs to 1500 hrs. (Day)'
  'Total (Traffic Accidents) - 1500 hrs to 1800 hrs. (Day)'
  'Total (Traffic Accidents) - 1800 hrs to 2100 hrs. (Night)'
  'Total (Traffic Accidents) - 2100 hrs to 2400 hrs. (Night)'
  'Total (Traffic Accidents) - Total'

==================================================
YEAR: 2022
Shape: (93, 38)
Columns (38):
  'Sl. No.'
  'State/UT'
  'Road Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Road Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Road Accidents - 0600 hrs to 0900 hrs (Day)'
  'Road Accidents - 0900 hrs to 1200 hrs (Day)'
  'Road Accidents - 1200 hrs to 1500 hrs (Day)'
  'Road Accidents - 1500 hrs to 1800 hrs (Day)'
  'Road Accidents - 1800 hrs to 2100hrs (Night)'
  'Road Accidents - 2100 hrs. to 2400hrs(Night)'
  'Road Accidents - Total'
  'Railway Crossing Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Crossing Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Crossing Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Crossing Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Crossing Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Crossing Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Crossing Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Crossing Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Crossing Accidents - Total'
  'Railway Accidents - 0000 hrs to 0300 hrs. (Night)'
  'Railway Accidents - 0300 hrs to 0600 hrs. (Night)'
  'Railway Accidents - 0600 hrs to 0900 hrs (Day)'
  'Railway Accidents - 0900 hrs to 1200 hrs (Day)'
  'Railway Accidents - 1200 hrs to 1500 hrs (Day)'
  'Railway Accidents - 1500 hrs to 1800 hrs (Day)'
  'Railway Accidents - 1800 hrs to 2100 hrs (Night)'
  'Railway Accidents - 2100 hrs. to 2400 hrs (Night)'
  'Railway Accidents - Total'
  'Total (Traffic Accidents) - 0000 hrs to 0300 hrs. (Night)'
  'Total (Traffic Accidents) - 0300 hrs to 0600 hrs. (Night)'
  'Total (Traffic Accidents) - 0600 hrs to 0900 hrs (Day)'
  'Total (Traffic Accidents) - 0900 hrs to 1200 hrs (Day)'
  'Total (Traffic Accidents) - 1200 hrs to 1500 hrs (Day)'
  'Total (Traffic Accidents) - 1500 hrs to 1800 hrs (Day)'
  'Total (Traffic Accidents) - 1800 hrs to 2100 hrs (Night)'
  'Total (Traffic Accidents) - 2100 hrs. to 2400 hrs (Night)'
  'Total (Traffic Accidents) - Total'

In [66]:
import re

def standardize_col_name_1A_6(col):
    col_work = col.strip()
    
    # S.No. variations
    if re.match(r'^(Sl|Si)\.?\s*-?\s*No\.?', col_work):
        return 'S.No.'
    
    # Category
    if re.match(r'^Category', col_work):
        return 'Category'
    
    # State/UT variations
    if re.match(r'^State', col_work):
        return 'State/UT'
    
    # Total column — 2015 special case
    if col_work == 'Total - Traffic Accidents':
        return 'Total_Traffic_Accidents_Total'
    
    # Standardize separators — dash or underscore → underscore
    col_work = col_work.replace(' - ', '_')
    col_work = col_work.replace('_', '_')
    
    # Remove parentheses but keep Day/Night
    col_work = col_work.replace('(Night)', 'Night')
    col_work = col_work.replace('(Day)', 'Day')
    col_work = col_work.replace('(', '').replace(')', '')
    
    # Fix spacing in hrs
    col_work = re.sub(r'(\d+)hrs', r'\1 hrs', col_work)
    
    # Remove dots
    col_work = col_work.replace('.', '')
    
    # Replace spaces with underscore
    col_work = col_work.replace(' ', '_')
    
    # Fix double underscores
    col_work = re.sub(r'_+', '_', col_work)
    
    # Remove trailing underscore
    col_work = col_work.rstrip('_')
    
    return col_work

def standardize_table_1A_6(df, year):
    # Rename all columns first
    new_cols = {col: standardize_col_name_1A_6(col) for col in df.columns}
    df = df.rename(columns=new_cols)
    
    # Add S.No. if missing
    if 'S.No.' not in df.columns:
        df.insert(0, 'S.No.', range(1, len(df)+1))
    
    # Add Category if missing (2022)
    if 'Category' not in df.columns:
        df.insert(1, 'Category', 'State')
    
    return df

# Verify all years
for year in years:
    filename = f"ADSI_{year}_Table_1A.6.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    df_std = standardize_table_1A_6(df_temp, year)
    print(f"\n{year} — Shape: {df_std.shape}")
    print(f"First 3 cols: {df_std.columns[:3].tolist()}")
    print(f"Time cols sample: {[c for c in df_std.columns if 'Road_Accidents' in c]}")

2015 — Shape: (93, 39)
First 3 cols: ['S.No.', 'Category', 'State/UT']
Time cols sample: ['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total']

2016 — Shape: (93, 39)
First 3 cols: ['S.No.', 'Category', 'State/UT']
Time cols sample: ['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total']

2017 — Shape: (93, 39)
First 3 cols: ['S.No.', 'Category', 'State/UT']
Time cols sample: ['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total']

2018 — Shape: (93, 39)
First 3 cols: ['S.No.', 'Category', 'State/UT']
Time cols sample: ['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total']

2019 — Shape: (93, 39)
First 3 cols: ['S.No.', 'Category', 'State/UT']
Time cols sample: ['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total']

2020 — Shape: (93, 39)
First 3 cols: ['S.No.', 'Category', 'State/UT']
Time cols sample: ['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total']

2021 — Shape: (93, 39)
First 3 cols: ['S.No.', 'Category', 'State/UT']
Time cols sample: ['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total']

2022 — Shape: (93, 39)
First 3 cols: ['S.No.', 'Category', 'State/UT']
Time cols sample: ['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrsNight', 'Road_Accidents_Total']

In [67]:
def standardize_col_name_1A_6(col):
    col_work = col.strip()
    
    # S.No. variations
    if re.match(r'^(Sl|Si)\.?\s*-?\s*No\.?', col_work):
        return 'S.No.'
    
    # Category
    if re.match(r'^Category', col_work):
        return 'Category'
    
    # State/UT variations
    if re.match(r'^State', col_work):
        return 'State/UT'
    
    # Total column — 2015 special case
    if col_work == 'Total - Traffic Accidents':
        return 'Total_Traffic_Accidents_Total'
    
    # Fix 2022 special case — 2400hrs(Night) missing space
    col_work = re.sub(r'(\d{4})hrs\(Night\)', r'\1 hrs. (Night)', col_work)
    col_work = re.sub(r'(\d{4})hrs\(Day\)', r'\1 hrs. (Day)', col_work)
    
    # Standardize separators
    col_work = col_work.replace(' - ', '_')
    col_work = col_work.replace('_', '_')
    
    # Remove parentheses but keep Day/Night
    col_work = col_work.replace('(Night)', 'Night')
    col_work = col_work.replace('(Day)', 'Day')
    col_work = col_work.replace('(', '').replace(')', '')
    
    # Fix spacing in hrs
    col_work = re.sub(r'(\d+)hrs', r'\1 hrs', col_work)
    
    # Remove dots
    col_work = col_work.replace('.', '')
    
    # Replace spaces with underscore
    col_work = col_work.replace(' ', '_')
    
    # Fix double underscores
    col_work = re.sub(r'_+', '_', col_work)
    
    # Remove trailing underscore
    col_work = col_work.rstrip('_')
    
    return col_work

def standardize_table_1A_6(df, year):
    new_cols = {col: standardize_col_name_1A_6(col) for col in df.columns}
    df = df.rename(columns=new_cols)
    
    if 'S.No.' not in df.columns:
        df.insert(0, 'S.No.', range(1, len(df)+1))
    
    if 'Category' not in df.columns:
        df.insert(1, 'Category', 'State')
    
    return df

# Verify 2022 fix
df_2022 = pd.read_csv(RAW_DATA_PATH + "ADSI_2022_Table_1A.6.csv")
df_2022_std = standardize_table_1A_6(df_2022, 2022)
print("2022 Road Accidents columns:")
print([c for c in df_2022_std.columns if 'Road_Accidents' in c])

2022 Road Accidents columns:
['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total']

In [68]:
ut_names_1A_6 = {
    2015: 'Union Territories',
    2016: 'Union Territory',
    2017: 'Union Territory',
    2018: 'Union Territory',
    2019: 'UT',
    2020: 'Union Territories',
    2021: 'UT',
    2022: 'Union Territories'
}

def load_table_1A_6(year):
    filename = f"ADSI_{year}_Table_1A.6.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # Standardize columns
    df = standardize_table_1A_6(df, year)
    
    # Filter States + UTs
    valid_categories = ['State', ut_names_1A_6[year]]
    df = df[df['Category'].astype(str).str.strip().isin(valid_categories)].copy()
    
    # Standardize Category values
    df['Category'] = df['Category'].replace({
        'Union Territories': 'UT',
        'Union Territory': 'UT'
    })
    
    # Uppercase State/UT
    df['State/UT'] = df['State/UT'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['State/UT'].str.contains('TOTAL')].copy()
    
    # Reset S.No.
    df['S.No.'] = range(1, len(df)+1)
    
    # Add year
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
all_time_data = []
for year in years:
    try:
        df = load_table_1A_6(year)
        all_time_data.append(df)
        print(f"✅ {year} — {len(df)} rows, Categories: {df['Category'].unique().tolist()}")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Merge
df_time = pd.concat(all_time_data, ignore_index=True)

# Reset S.No.
df_time['S.No.'] = range(1, len(df_time)+1)

print(f"\n✅ Final merged shape: {df_time.shape}")

# Save
output_path = "../data/processed/timewise_traffic_accidents_2015_2022.csv"
df_time.to_csv(output_path, index=False)
print(f"✅ Saved!")

✅ 2015 — 36 rows, Categories: ['State', 'UT']
✅ 2016 — 36 rows, Categories: ['State', 'UT']
✅ 2017 — 36 rows, Categories: ['State', 'UT']
✅ 2018 — 36 rows, Categories: ['State', 'UT']
✅ 2019 — 36 rows, Categories: ['State', 'UT']
✅ 2020 — 36 rows, Categories: ['State', 'UT']
✅ 2021 — 36 rows, Categories: ['State', 'UT']
✅ 2022 — 89 rows, Categories: ['State']

✅ Final merged shape: (341, 40)
✅ Saved!

In [69]:
# Check 2022 categories
df_2022_raw = pd.read_csv(RAW_DATA_PATH + "ADSI_2022_Table_1A.6.csv")
df_2022_std = standardize_table_1A_6(df_2022_raw, 2022)
print("2022 Category column:")
print(df_2022_std['Category'].unique())
print("\nState/UT values:")
print(df_2022_std['State/UT'].tolist())

2022 Category column:
<StringArray>
['State']
Length: 1, dtype: str

State/UT values:
['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Total (States)', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nicobar Haveli and Daman and Diu', 'Delhi (UT)', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry', 'Total (UTs)', 'Total (All India)', 'Agra', 'Ahmedabad', 'Amritsar', 'Asansol', 'Aurangabad', 'Bengaluru', 'Bhopal', 'Chandigarh (City)', 'Chennai', 'Coimbatore', 'Delhi (City)', 'Dhanbad', 'Durg Bhilainagar', 'Faridabad', 'Ghaziabad', 'Gwalior', 'Hyderabad', 'Indore', 'Jabalpur', 'Jaipur', 'Jamshedpur', 'Jodhpur', 'Kannur', 'Kanpur', 'Kochi', 'Kolkata', 'Kollam', 'Kota', 'Kozhikode', 'Lucknow', 'Ludhiana', 'Madurai', 'Malappuram', 'Meerut', 'Mumbai', 'Nagpur', 'Nasik', 'Patna', 'Prayagraj +', 'Pune', 'Raipur', 'Rajkot', 'Ranchi', 'Srinagar', 'Surat', 'Thiruvananthapuram', 'Thrissur', 'Tiruchirappalli', 'Vadodara', 'Varanasi', 'Vasai Virar', 'Vijayawada', 'Vishakhapatnam', 'Total (Cities)']

In [70]:
def load_table_1A_6(year):
    filename = f"ADSI_{year}_Table_1A.6.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # Standardize columns
    df = standardize_table_1A_6(df, year)
    
    ut_names = {
        2015: 'Union Territories', 2016: 'Union Territory',
        2017: 'Union Territory', 2018: 'Union Territory',
        2019: 'UT', 2020: 'Union Territories',
        2021: 'UT', 2022: None
    }
    
    if year != 2022:
        valid_categories = ['State', ut_names[year]]
        df = df[df['Category'].astype(str).str.strip().isin(valid_categories)].copy()
    else:
        # 2022 — extract before Total (UTs)
        valid_list = []
        for val in df['State/UT'].tolist():
            if 'Total (UTs)' in str(val) or 'Total (All India)' in str(val):
                break
            if 'Total' not in str(val):
                valid_list.append(val)
        df = df[df['State/UT'].isin(valid_list)].copy()
        df['Category'] = 'State'
    
    # Standardize Category values
    df['Category'] = df['Category'].replace({
        'Union Territories': 'UT',
        'Union Territory': 'UT'
    })
    
    # 2022 UTs ko UT category deni hai
    if year == 2022:
        uts_2022 = ['ANDAMAN AND NICOBAR ISLANDS', 'CHANDIGARH',
                    'DADRA AND NICOBAR HAVELI AND DAMAN AND DIU',
                    'DELHI (UT)', 'JAMMU AND KASHMIR', 'LADAKH',
                    'LAKSHADWEEP', 'PUDUCHERRY']
        df['State/UT'] = df['State/UT'].str.strip().str.upper()
        df.loc[df['State/UT'].isin(uts_2022), 'Category'] = 'UT'
    
    # Uppercase State/UT
    df['State/UT'] = df['State/UT'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['State/UT'].str.contains('TOTAL')].copy()
    
    # Reset S.No.
    df['S.No.'] = range(1, len(df)+1)
    
    # Add year
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
all_time_data = []
for year in years:
    try:
        df = load_table_1A_6(year)
        all_time_data.append(df)
        print(f"✅ {year} — {len(df)} rows, Categories: {df['Category'].unique().tolist()}")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Merge
df_time = pd.concat(all_time_data, ignore_index=True)
df_time['S.No.'] = range(1, len(df_time)+1)

print(f"\n✅ Final merged shape: {df_time.shape}")

# Save
output_path = "../data/processed/timewise_traffic_accidents_2015_2022.csv"
df_time.to_csv(output_path, index=False)
print(f"✅ Saved!")

✅ 2015 — 36 rows, Categories: ['State', 'UT']
✅ 2016 — 36 rows, Categories: ['State', 'UT']
✅ 2017 — 36 rows, Categories: ['State', 'UT']
✅ 2018 — 36 rows, Categories: ['State', 'UT']
✅ 2019 — 36 rows, Categories: ['State', 'UT']
✅ 2020 — 36 rows, Categories: ['State', 'UT']
✅ 2021 — 36 rows, Categories: ['State', 'UT']
✅ 2022 — 36 rows, Categories: ['State', 'UT']

✅ Final merged shape: (288, 40)
✅ Saved!

In [72]:
# Check all years - Table 1.4 complete structure
for year in years:
    filename = f"ADSI_{year}_Table_1.4.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    print(f"\n{'='*50}")
    print(f"YEAR: {year}")
    print(f"Shape: {df_temp.shape}")
    print(f"Columns ({len(df_temp.columns)}):")
    for col in df_temp.columns:
        print(f"  {repr(col)}")

==================================================
YEAR: 2015
Shape: (93, 31)
Columns (31):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above - Below 18 years - Male'
  '14 and Above - Below 18 years - Female'
  '14 and Above - Below 18 years - Transgender'
  '14 and Above - Below 18 years - Total'
  '18 and Above - Below 30 years - Male'
  '18 and Above - Below 30 years - Female'
  '18 and Above - Below 30 years - Transgender'
  '18 and Above - Below 30 years - Total'
  '30 and Above - Below 45 years - Male'
  '30 and Above - Below 45 years - Female'
  '30 and Above - Below 45 years - Transgender'
  '30 and Above - Below 45 years - Total'
  '45 and Above - Below 60 years - Male'
  '45 and Above - Below 60 years - Female'
  '45 and Above - Below 60 years - Transgender'
  '45 and Above - Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total'

==================================================
YEAR: 2016
Shape: (93, 31)
Columns (31):
  'Sl. No.'
  'Category'
  'State/UT'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above - Below 18 years - Male'
  '14 and Above - Below 18 years - Female'
  '14 and Above - Below 18 years - Transgender'
  '14 and Above - Below 18 years - Total'
  '18 and Above - Below 30 years - Male'
  '18 and Above - Below 30 years - Female'
  '18 and Above - Below 30 years - Transgender'
  '18 and Above - Below 30 years - Total'
  '30 and Above - Below 45 years - Male'
  '30 and Above - Below 45 years - Female'
  '30 and Above - Below 45 years - Transgender'
  '30 and Above - Below 45 years - Total'
  '45 and Above - Below 60 years - Male'
  '45 and Above - Below 60 years - Female'
  '45 and Above - Below 60 years - Transgender'
  '45 and Above - Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total'

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 142: invalid start byte

In [73]:
# Check all years - Table 1.4 with encoding fix
for year in years:
    filename = f"ADSI_{year}_Table_1.4.csv"
    try:
        df_temp = pd.read_csv(RAW_DATA_PATH + filename, encoding='utf-8')
    except UnicodeDecodeError:
        df_temp = pd.read_csv(RAW_DATA_PATH + filename, encoding='latin-1')
    
    print(f"\n{'='*50}")
    print(f"YEAR: {year}")
    print(f"Shape: {df_temp.shape}")
    print(f"Columns ({len(df_temp.columns)}):")
    for col in df_temp.columns:
        print(f"  {repr(col)}")

==================================================
YEAR: 2015
Shape: (93, 31)
Columns (31):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above - Below 18 years - Male'
  '14 and Above - Below 18 years - Female'
  '14 and Above - Below 18 years - Transgender'
  '14 and Above - Below 18 years - Total'
  '18 and Above - Below 30 years - Male'
  '18 and Above - Below 30 years - Female'
  '18 and Above - Below 30 years - Transgender'
  '18 and Above - Below 30 years - Total'
  '30 and Above - Below 45 years - Male'
  '30 and Above - Below 45 years - Female'
  '30 and Above - Below 45 years - Transgender'
  '30 and Above - Below 45 years - Total'
  '45 and Above - Below 60 years - Male'
  '45 and Above - Below 60 years - Female'
  '45 and Above - Below 60 years - Transgender'
  '45 and Above - Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total'

==================================================
YEAR: 2016
Shape: (93, 31)
Columns (31):
  'Sl. No.'
  'Category'
  'State/UT'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above - Below 18 years - Male'
  '14 and Above - Below 18 years - Female'
  '14 and Above - Below 18 years - Transgender'
  '14 and Above - Below 18 years - Total'
  '18 and Above - Below 30 years - Male'
  '18 and Above - Below 30 years - Female'
  '18 and Above - Below 30 years - Transgender'
  '18 and Above - Below 30 years - Total'
  '30 and Above - Below 45 years - Male'
  '30 and Above - Below 45 years - Female'
  '30 and Above - Below 45 years - Transgender'
  '30 and Above - Below 45 years - Total'
  '45 and Above - Below 60 years - Male'
  '45 and Above - Below 60 years - Female'
  '45 and Above - Below 60 years - Transgender'
  '45 and Above - Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total'

==================================================
YEAR: 2017
Shape: (93, 31)
Columns (31):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above \x96 Below 18 years - Male'
  '14 and Above \x96 Below 18 years - Female'
  '14 and Above \x96 Below 18 years - Transgender'
  '14 and Above \x96 Below 18 years - Total'
  '18 and Above \x96 Below 30 years - Male'
  '18 and Above \x96 Below 30 years - Female'
  '18 and Above \x96 Below 30 years - Transgender'
  '18 and Above \x96 Below 30 years - Total'
  '30 and Above \x96 Below 45 years - Male'
  '30 and Above \x96 Below 45 years - Female'
  '30 and Above \x96 Below 45 years - Transgender'
  '30 and Above \x96 Below 45 years - Total'
  '45 and Above \x96 Below 60 years - Male'
  '45 and Above \x96 Below 60 years - Female'
  '45 and Above \x96 Below 60 years - Transgender'
  '45 and Above \x96 Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total - Total'

==================================================
YEAR: 2018
Shape: (93, 31)
Columns (31):
  'Sl. No.'
  'Category - (Col.2)'
  'State/UT/City'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above - Below 18 years - Male'
  '14 and Above - Below 18 years - Female'
  '14 and Above - Below 18 years - Transgender'
  '14 and Above - Below 18 years - Total'
  '18 and Above - Below 30 years - Male'
  '18 and Above - Below 30 years - Female'
  '18 and Above - Below 30 years - Transgender'
  '18 and Above - Below 30 years - Total'
  '30 and Above - Below 45 years - Male'
  '30 and Above - Below 45 years - Female'
  '30 and Above - Below 45 years - Transgender'
  '30 and Above - Below 45 years - Total'
  '45 and Above - Below 60 years - Male'
  '45 and Above - Below 60 years - Female'
  '45 and Above - Below 60 years - Transgender'
  '45 and Above - Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total - Total'

==================================================
YEAR: 2019
Shape: (93, 30)
Columns (30):
  'Category'
  'State/UT'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above-Below 18 years - Male'
  '14 and Above-Below 18 years - Female'
  '14 and Above-Below 18 years - Transgender'
  '14 and Above-Below 18 years - Total'
  '18 and Above-Below 30 years - Male'
  '18 and Above-Below 30 years - Female'
  '18 and Above-Below 30 years - Transgender'
  '18 and Above-Below 30 years - Total'
  '30 and Above-Below 45 years - Male'
  '30 and Above-Below 45 years - Female'
  '30 and Above-Below 45 years - Transgender'
  '30 and Above-Below 45 years - Total'
  '45 and Above-Below 60 years - Male'
  '45 and Above-Below 60 years - Female'
  '45 and Above-Below 60 years - Transgender'
  '45 and Above-Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total - Total'

==================================================
YEAR: 2020
Shape: (93, 31)
Columns (31):
  'Si. No.'
  'Category'
  'State/UT/City'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above-Below 18 years - Male'
  '14 and Above-Below 18 years - Female'
  '14 and Above-Below 18 years - Transgender'
  '14 and Above-Below 18 years - Total'
  '18 and Above-Below 30 years - Male'
  '18 and Above-Below 30 years - Female'
  '18 and Above-Below 30 years - Transgender'
  '18 and Above-Below 30 years - Total'
  '30 and Above-Below 45 years - Male'
  '30 and Above-Below 45 years - Female'
  '30 and Above-Below 45 years - Transgender'
  '30 and Above-Below 45 years - Total'
  '45 and Above-Below 60 years - Male'
  '45 and Above-Below 60 years - Female'
  '45 and Above-Below 60 years - Transgender'
  '45 and Above-Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total - Total'

==================================================
YEAR: 2021
Shape: (93, 30)
Columns (30):
  'Category'
  'State/UT'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above-Below 18 years - Male'
  '14 and Above-Below 18 years - Female'
  '14 and Above-Below 18 years - Transgender'
  '14 and Above-Below 18 years - Total'
  '18 and Above-Below 30 years - Male'
  '18 and Above-Below 30 years - Female'
  '18 and Above-Below 30 years - Transgender'
  '18 and Above-Below 30 years - Total'
  '30 and Above-Below 45 years - Male'
  '30 and Above-Below 45 years - Female'
  '30 and Above-Below 45 years - Transgender'
  '30 and Above-Below 45 years - Total'
  '45 and Above-Below 60 years - Male'
  '45 and Above-Below 60 years - Female'
  '45 and Above-Below 60 years - Transgender'
  '45 and Above-Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total - Total'

==================================================
YEAR: 2022
Shape: (93, 31)
Columns (31):
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Below 14 years - Male'
  'Below 14 years - Female'
  'Below 14 years - Transgender'
  'Below 14 years - Total'
  '14 and Above - Below 18 years - Male'
  '14 and Above - Below 18 years - Female'
  '14 and Above - Below 18 years - Transgender'
  '14 and Above - Below 18 years - Total'
  '18 and Above - Below 30 years - Male'
  '18 and Above - Below 30 years - Female'
  '18 and Above - Below 30 years - Transgender'
  '18 and Above - Below 30 years - Total'
  '30 and Above - Below 45 years - Male'
  '30 and Above - Below 45 years - Female'
  '30 and Above - Below 45 years - Transgender'
  '30 and Above - Below 45 years - Total'
  '45 and Above-Below 60 years - Male'
  '45 and Above-Below 60 years - Female'
  '45 and Above-Below 60 years - Transgender'
  '45 and Above-Below 60 years - Total'
  '60 years & Above - Male'
  '60 years & Above - Female'
  '60 years & Above - Transgender'
  '60 years & Above - Total'
  'Total - Male'
  'Total - Female'
  'Total - Transgender'
  'Total - Total'

In [74]:
def standardize_col_name_1_4(col):
    col_work = col.strip()
    
    # Fix special character \x96 (en-dash) → regular dash
    col_work = col_work.replace('\x96', '-')
    
    # S.No. variations
    if re.match(r'^(Sl|Si)\.?\s*-?\s*No\.?', col_work):
        return 'S.No.'
    
    # Category variations
    if re.match(r'^Category', col_work):
        return 'Category'
    
    # State/UT variations
    if re.match(r'^State', col_work):
        return 'State/UT'
    
    # Age group columns
    age_gender_map = {
        'Below 14 years - Male': 'Age_Below14_Male',
        'Below 14 years - Female': 'Age_Below14_Female',
        'Below 14 years - Transgender': 'Age_Below14_Transgender',
        'Below 14 years - Total': 'Age_Below14_Total',
        '14 and Above - Below 18 years - Male': 'Age_14_18_Male',
        '14 and Above - Below 18 years - Female': 'Age_14_18_Female',
        '14 and Above - Below 18 years - Transgender': 'Age_14_18_Transgender',
        '14 and Above - Below 18 years - Total': 'Age_14_18_Total',
        '14 and Above-Below 18 years - Male': 'Age_14_18_Male',
        '14 and Above-Below 18 years - Female': 'Age_14_18_Female',
        '14 and Above-Below 18 years - Transgender': 'Age_14_18_Transgender',
        '14 and Above-Below 18 years - Total': 'Age_14_18_Total',
        '18 and Above - Below 30 years - Male': 'Age_18_30_Male',
        '18 and Above - Below 30 years - Female': 'Age_18_30_Female',
        '18 and Above - Below 30 years - Transgender': 'Age_18_30_Transgender',
        '18 and Above - Below 30 years - Total': 'Age_18_30_Total',
        '18 and Above-Below 30 years - Male': 'Age_18_30_Male',
        '18 and Above-Below 30 years - Female': 'Age_18_30_Female',
        '18 and Above-Below 30 years - Transgender': 'Age_18_30_Transgender',
        '18 and Above-Below 30 years - Total': 'Age_18_30_Total',
        '30 and Above - Below 45 years - Male': 'Age_30_45_Male',
        '30 and Above - Below 45 years - Female': 'Age_30_45_Female',
        '30 and Above - Below 45 years - Transgender': 'Age_30_45_Transgender',
        '30 and Above - Below 45 years - Total': 'Age_30_45_Total',
        '30 and Above-Below 45 years - Male': 'Age_30_45_Male',
        '30 and Above-Below 45 years - Female': 'Age_30_45_Female',
        '30 and Above-Below 45 years - Transgender': 'Age_30_45_Transgender',
        '30 and Above-Below 45 years - Total': 'Age_30_45_Total',
        '45 and Above - Below 60 years - Male': 'Age_45_60_Male',
        '45 and Above - Below 60 years - Female': 'Age_45_60_Female',
        '45 and Above - Below 60 years - Transgender': 'Age_45_60_Transgender',
        '45 and Above - Below 60 years - Total': 'Age_45_60_Total',
        '45 and Above-Below 60 years - Male': 'Age_45_60_Male',
        '45 and Above-Below 60 years - Female': 'Age_45_60_Female',
        '45 and Above-Below 60 years - Transgender': 'Age_45_60_Transgender',
        '45 and Above-Below 60 years - Total': 'Age_45_60_Total',
        '60 years & Above - Male': 'Age_60Plus_Male',
        '60 years & Above - Female': 'Age_60Plus_Female',
        '60 years & Above - Transgender': 'Age_60Plus_Transgender',
        '60 years & Above - Total': 'Age_60Plus_Total',
        'Total - Male': 'Total_Male',
        'Total - Female': 'Total_Female',
        'Total - Transgender': 'Total_Transgender',
        'Total - Total': 'Total_All',
        'Total': 'Total_All',
    }
    
    if col_work in age_gender_map:
        return age_gender_map[col_work]
    
    return col_work

def standardize_table_1_4(df, year):
    # Fix encoding issues first
    df.columns = [col.replace('\x96', '-') for col in df.columns]
    
    # Rename all columns
    new_cols = {col: standardize_col_name_1_4(col) for col in df.columns}
    df = df.rename(columns=new_cols)
    
    # Add S.No. if missing
    if 'S.No.' not in df.columns:
        df.insert(0, 'S.No.', range(1, len(df)+1))
    
    # Add Category if missing
    if 'Category' not in df.columns:
        df.insert(1, 'Category', 'State')
    
    return df

# Verify all years
for year in years:
    filename = f"ADSI_{year}_Table_1.4.csv"
    try:
        df_temp = pd.read_csv(RAW_DATA_PATH + filename, encoding='utf-8')
    except UnicodeDecodeError:
        df_temp = pd.read_csv(RAW_DATA_PATH + filename, encoding='latin-1')
    
    df_std = standardize_table_1_4(df_temp, year)
    print(f"\n{year} — Shape: {df_std.shape}")
    print(f"First 3 cols: {df_std.columns[:3].tolist()}")
    print(f"All columns: {df_std.columns.tolist()}")

2015 — Shape: (93, 31)
First 3 cols: ['S.No.', 'Category', 'State/UT']
All columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Male', 'Age_Below14_Female', 'Age_Below14_Transgender', 'Age_Below14_Total', 'Age_14_18_Male', 'Age_14_18_Female', 'Age_14_18_Transgender', 'Age_14_18_Total', 'Age_18_30_Male', 'Age_18_30_Female', 'Age_18_30_Transgender', 'Age_18_30_Total', 'Age_30_45_Male', 'Age_30_45_Female', 'Age_30_45_Transgender', 'Age_30_45_Total', 'Age_45_60_Male', 'Age_45_60_Female', 'Age_45_60_Transgender', 'Age_45_60_Total', 'Age_60Plus_Male', 'Age_60Plus_Female', 'Age_60Plus_Transgender', 'Age_60Plus_Total', 'Total_Male', 'Total_Female', 'Total_Transgender', 'Total_All']

2016 — Shape: (93, 31)
First 3 cols: ['S.No.', 'Category', 'State/UT']
All columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Male', 'Age_Below14_Female', 'Age_Below14_Transgender', 'Age_Below14_Total', 'Age_14_18_Male', 'Age_14_18_Female', 'Age_14_18_Transgender', 'Age_14_18_Total', 'Age_18_30_Male', 'Age_18_30_Female', 'Age_18_30_Transgender', 'Age_18_30_Total', 'Age_30_45_Male', 'Age_30_45_Female', 'Age_30_45_Transgender', 'Age_30_45_Total', 'Age_45_60_Male', 'Age_45_60_Female', 'Age_45_60_Transgender', 'Age_45_60_Total', 'Age_60Plus_Male', 'Age_60Plus_Female', 'Age_60Plus_Transgender', 'Age_60Plus_Total', 'Total_Male', 'Total_Female', 'Total_Transgender', 'Total_All']

2017 — Shape: (93, 31)
First 3 cols: ['S.No.', 'Category', 'State/UT']
All columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Male', 'Age_Below14_Female', 'Age_Below14_Transgender', 'Age_Below14_Total', 'Age_14_18_Male', 'Age_14_18_Female', 'Age_14_18_Transgender', 'Age_14_18_Total', 'Age_18_30_Male', 'Age_18_30_Female', 'Age_18_30_Transgender', 'Age_18_30_Total', 'Age_30_45_Male', 'Age_30_45_Female', 'Age_30_45_Transgender', 'Age_30_45_Total', 'Age_45_60_Male', 'Age_45_60_Female', 'Age_45_60_Transgender', 'Age_45_60_Total', 'Age_60Plus_Male', 'Age_60Plus_Female', 'Age_60Plus_Transgender', 'Age_60Plus_Total', 'Total_Male', 'Total_Female', 'Total_Transgender', 'Total_All']

2018 — Shape: (93, 31)
First 3 cols: ['S.No.', 'Category', 'State/UT']
All columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Male', 'Age_Below14_Female', 'Age_Below14_Transgender', 'Age_Below14_Total', 'Age_14_18_Male', 'Age_14_18_Female', 'Age_14_18_Transgender', 'Age_14_18_Total', 'Age_18_30_Male', 'Age_18_30_Female', 'Age_18_30_Transgender', 'Age_18_30_Total', 'Age_30_45_Male', 'Age_30_45_Female', 'Age_30_45_Transgender', 'Age_30_45_Total', 'Age_45_60_Male', 'Age_45_60_Female', 'Age_45_60_Transgender', 'Age_45_60_Total', 'Age_60Plus_Male', 'Age_60Plus_Female', 'Age_60Plus_Transgender', 'Age_60Plus_Total', 'Total_Male', 'Total_Female', 'Total_Transgender', 'Total_All']

2019 — Shape: (93, 31)
First 3 cols: ['S.No.', 'Category', 'State/UT']
All columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Male', 'Age_Below14_Female', 'Age_Below14_Transgender', 'Age_Below14_Total', 'Age_14_18_Male', 'Age_14_18_Female', 'Age_14_18_Transgender', 'Age_14_18_Total', 'Age_18_30_Male', 'Age_18_30_Female', 'Age_18_30_Transgender', 'Age_18_30_Total', 'Age_30_45_Male', 'Age_30_45_Female', 'Age_30_45_Transgender', 'Age_30_45_Total', 'Age_45_60_Male', 'Age_45_60_Female', 'Age_45_60_Transgender', 'Age_45_60_Total', 'Age_60Plus_Male', 'Age_60Plus_Female', 'Age_60Plus_Transgender', 'Age_60Plus_Total', 'Total_Male', 'Total_Female', 'Total_Transgender', 'Total_All']

2020 — Shape: (93, 31)
First 3 cols: ['S.No.', 'Category', 'State/UT']
All columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Male', 'Age_Below14_Female', 'Age_Below14_Transgender', 'Age_Below14_Total', 'Age_14_18_Male', 'Age_14_18_Female', 'Age_14_18_Transgender', 'Age_14_18_Total', 'Age_18_30_Male', 'Age_18_30_Female', 'Age_18_30_Transgender', 'Age_18_30_Total', 'Age_30_45_Male', 'Age_30_45_Female', 'Age_30_45_Transgender', 'Age_30_45_Total', 'Age_45_60_Male', 'Age_45_60_Female', 'Age_45_60_Transgender', 'Age_45_60_Total', 'Age_60Plus_Male', 'Age_60Plus_Female', 'Age_60Plus_Transgender', 'Age_60Plus_Total', 'Total_Male', 'Total_Female', 'Total_Transgender', 'Total_All']

2021 — Shape: (93, 31)
First 3 cols: ['S.No.', 'Category', 'State/UT']
All columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Male', 'Age_Below14_Female', 'Age_Below14_Transgender', 'Age_Below14_Total', 'Age_14_18_Male', 'Age_14_18_Female', 'Age_14_18_Transgender', 'Age_14_18_Total', 'Age_18_30_Male', 'Age_18_30_Female', 'Age_18_30_Transgender', 'Age_18_30_Total', 'Age_30_45_Male', 'Age_30_45_Female', 'Age_30_45_Transgender', 'Age_30_45_Total', 'Age_45_60_Male', 'Age_45_60_Female', 'Age_45_60_Transgender', 'Age_45_60_Total', 'Age_60Plus_Male', 'Age_60Plus_Female', 'Age_60Plus_Transgender', 'Age_60Plus_Total', 'Total_Male', 'Total_Female', 'Total_Transgender', 'Total_All']

2022 — Shape: (93, 31)
First 3 cols: ['S.No.', 'Category', 'State/UT']
All columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Male', 'Age_Below14_Female', 'Age_Below14_Transgender', 'Age_Below14_Total', 'Age_14_18_Male', 'Age_14_18_Female', 'Age_14_18_Transgender', 'Age_14_18_Total', 'Age_18_30_Male', 'Age_18_30_Female', 'Age_18_30_Transgender', 'Age_18_30_Total', 'Age_30_45_Male', 'Age_30_45_Female', 'Age_30_45_Transgender', 'Age_30_45_Total', 'Age_45_60_Male', 'Age_45_60_Female', 'Age_45_60_Transgender', 'Age_45_60_Total', 'Age_60Plus_Male', 'Age_60Plus_Female', 'Age_60Plus_Transgender', 'Age_60Plus_Total', 'Total_Male', 'Total_Female', 'Total_Transgender', 'Total_All']

In [75]:
ut_names_1_4 = {
    2015: 'Union Territories', 2016: 'Union Territory',
    2017: 'Union Territory', 2018: 'Union Territory',
    2019: 'UT', 2020: 'Union Territories',
    2021: 'UT', 2022: 'Union Territories'
}

def load_table_1_4(year):
    filename = f"ADSI_{year}_Table_1.4.csv"
    try:
        df = pd.read_csv(RAW_DATA_PATH + filename, encoding='utf-8')
    except UnicodeDecodeError:
        df = pd.read_csv(RAW_DATA_PATH + filename, encoding='latin-1')
    
    # Standardize columns
    df = standardize_table_1_4(df, year)
    
    # Filter States + UTs
    valid_categories = ['State', ut_names_1_4[year]]
    df = df[df['Category'].astype(str).str.strip().isin(valid_categories)].copy()
    
    # Standardize Category
    df['Category'] = df['Category'].replace({
        'Union Territories': 'UT',
        'Union Territory': 'UT'
    })
    
    # Uppercase State/UT
    df['State/UT'] = df['State/UT'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['State/UT'].str.contains('TOTAL')].copy()
    
    # Reset S.No.
    df['S.No.'] = range(1, len(df)+1)
    
    # Add year
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Load all years
all_age_data = []
for year in years:
    try:
        df = load_table_1_4(year)
        all_age_data.append(df)
        print(f"✅ {year} — {len(df)} rows, Categories: {df['Category'].unique().tolist()}")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Merge
df_age = pd.concat(all_age_data, ignore_index=True)
df_age['S.No.'] = range(1, len(df_age)+1)

print(f"\n✅ Final merged shape: {df_age.shape}")

# Save
output_path = "../data/processed/agewise_deaths_2015_2022.csv"
df_age.to_csv(output_path, index=False)
print(f"✅ Saved!")

✅ 2015 — 29 rows, Categories: ['State']
✅ 2016 — 36 rows, Categories: ['State', 'UT']
✅ 2017 — 36 rows, Categories: ['State', 'UT']
✅ 2018 — 36 rows, Categories: ['State', 'UT']
✅ 2019 — 36 rows, Categories: ['State', 'UT']
✅ 2020 — 36 rows, Categories: ['State', 'UT']
✅ 2021 — 36 rows, Categories: ['State', 'UT']
✅ 2022 — 36 rows, Categories: ['State', 'UT']

✅ Final merged shape: (281, 32)
✅ Saved!

In [76]:
# Check 2015 categories
df_2015_raw = pd.read_csv(RAW_DATA_PATH + "ADSI_2015_Table_1.4.csv")
df_2015_std = standardize_table_1_4(df_2015_raw, 2015)
print("2015 unique categories:")
print(df_2015_std['Category'].unique())
print("\n2015 all State/UT values:")
print(df_2015_std['State/UT'].tolist())

2015 unique categories:
<StringArray>
['State', 'TOTAL (STATES)', 'Union Territorie', 'TOTAL (UTs)', 'TOTAL (ALL INDIA)', 'City', 'TOTAL (CITIES)']
Length: 7, dtype: str

2015 all State/UT values:
['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL', 'TOTAL (STATES)', 'A & N ISLANDS', 'CHANDIGARH', 'D & N HAVELI', 'DAMAN & DIU', 'DELHI (UT)', 'LAKSHADWEEP', 'PUDUCHERRY', 'TOTAL (UTs)', 'TOTAL (ALL INDIA)', 'AGRA', 'AHMEDABAD', 'ALLAHABAD', 'AMRITSAR', 'ASANSOL', 'AURANGABAD', 'BENGALURU', 'BHOPAL', 'CHANDIGARH (CITY)', 'CHENNAI', 'COIMBATORE', 'DELHI (CITY)', 'DHANBAD', 'DURG BHILAINAGAR', 'FARIDABAD', 'GHAZIABAD', 'GWALIOR', 'HYDERABAD', 'INDORE', 'JABALPUR', 'JAIPUR', 'JAMSHEDPUR', 'JODHPUR', 'KANNUR', 'KANPUR', 'KOCHI', 'KOLKATA', 'KOLLAM', 'KOTA', 'KOZHIKODE', 'LUCKNOW', 'LUDHIANA', 'MADURAI', 'MALAPPURAM', 'MEERUT', 'MUMBAI', 'NAGPUR', 'NASIK', 'PATNA', 'PUNE', 'RAIPUR', 'RAJKOT', 'RANCHI', 'SRINAGAR', 'SURAT', 'THIRUVANANTHAPURAM', 'THRISSUR', 'TIRUCHIRAPPALLI', 'VADODARA', 'VARANASI', 'VASAI VIRAR', 'VIJAYAWADA', 'VISHAKHAPATNAM', 'TOTAL (CITIES)']

In [77]:
ut_names_1_4 = {
    2015: 'Union Territorie',  # Typo in original data!
    2016: 'Union Territory',
    2017: 'Union Territory',
    2018: 'Union Territory',
    2019: 'UT',
    2020: 'Union Territories',
    2021: 'UT',
    2022: 'Union Territories'
}

# Reload all years
all_age_data = []
for year in years:
    try:
        df = load_table_1_4(year)
        all_age_data.append(df)
        print(f"✅ {year} — {len(df)} rows, Categories: {df['Category'].unique().tolist()}")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Check before saving
df_age = pd.concat(all_age_data, ignore_index=True)
df_age['S.No.'] = range(1, len(df_age)+1)
print(f"\nFinal merged shape: {df_age.shape}")
print("\nYear wise count:")
print(df_age.groupby('year')['State/UT'].count())

✅ 2015 — 36 rows, Categories: ['State', 'Union Territorie']
✅ 2016 — 36 rows, Categories: ['State', 'UT']
✅ 2017 — 36 rows, Categories: ['State', 'UT']
✅ 2018 — 36 rows, Categories: ['State', 'UT']
✅ 2019 — 36 rows, Categories: ['State', 'UT']
✅ 2020 — 36 rows, Categories: ['State', 'UT']
✅ 2021 — 36 rows, Categories: ['State', 'UT']
✅ 2022 — 36 rows, Categories: ['State', 'UT']

Final merged shape: (288, 32)

Year wise count:
year
2015    36
2016    36
2017    36
2018    36
2019    36
2020    36
2021    36
2022    36
Name: State/UT, dtype: int64

In [78]:
# Standardize Category in all dataframes
category_map = {
    'Union Territories': 'UT',
    'Union Territory': 'UT',
    'Union Territorie': 'UT',  # 2015 typo fix
}

for df in all_age_data:
    df['Category'] = df['Category'].replace(category_map)

# Verify
df_age = pd.concat(all_age_data, ignore_index=True)
df_age['S.No.'] = range(1, len(df_age)+1)

print("Category values after fix:")
for year in years:
    cats = df_age[df_age['year']==year]['Category'].unique().tolist()
    print(f"{year}: {cats}")

print(f"\nFinal shape: {df_age.shape}")
print("\nSample data:")
df_age.head(3)

Category values after fix:
2015: ['State', 'UT']
2016: ['State', 'UT']
2017: ['State', 'UT']
2018: ['State', 'UT']
2019: ['State', 'UT']
2020: ['State', 'UT']
2021: ['State', 'UT']
2022: ['State', 'UT']

Final shape: (288, 32)

Sample data:

   S.No. Category           State/UT  Age_Below14_Male  Age_Below14_Female  Age_Below14_Transgender  Age_Below14_Total  Age_14_18_Male  Age_14_18_Female  Age_14_18_Transgender  Age_14_18_Total  Age_18_30_Male  Age_18_30_Female  Age_18_30_Transgender  Age_18_30_Total  Age_30_45_Male  Age_30_45_Female  Age_30_45_Transgender  Age_30_45_Total  Age_45_60_Male  Age_45_60_Female  Age_45_60_Transgender  Age_45_60_Total  Age_60Plus_Male  Age_60Plus_Female  Age_60Plus_Transgender  Age_60Plus_Total  Total_Male  Total_Female  Total_Transgender  Total_All  year
0      1    State     ANDHRA PRADESH               397                 175                        0                572             606               164                      0              770            3636               824                      0             4460            4886               875                      0             5761            3107               737                      0             3844             1437                568                       0              2005       14069          3343                  0      17412  2015
1      2    State  ARUNACHAL PRADESH                14                   7                        0                 21              18                13                      0               31             100                13                      0              113             126                 9                      0              135              53                 1                      0               54               14                  1                       0                15         325            44                  0        369  2015
2      3    State              ASSAM               140                  43                        0                183             569               104                      0              673            1250               186                      0             1436             947               177                      0             1124             618                91                      0              709              173                 33                       0               206        3697           634                  0       4331  2015

In [79]:
# Save
output_path = "../data/processed/agewise_deaths_2015_2022.csv"
df_age.to_csv(output_path, index=False)
print(f"✅ Saved!")
print(f"Shape: {df_age.shape}")

✅ Saved!
Shape: (288, 32)

In [81]:
# Load saved agewise data
df_age = pd.read_csv("../data/processed/agewise_deaths_2015_2022.csv")

print("Before — columns:", df_age.columns.tolist())
print("Shape:", df_age.shape)

Before — columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Male', 'Age_Below14_Female', 'Age_Below14_Transgender', 'Age_Below14_Total', 'Age_14_18_Male', 'Age_14_18_Female', 'Age_14_18_Transgender', 'Age_14_18_Total', 'Age_18_30_Male', 'Age_18_30_Female', 'Age_18_30_Transgender', 'Age_18_30_Total', 'Age_30_45_Male', 'Age_30_45_Female', 'Age_30_45_Transgender', 'Age_30_45_Total', 'Age_45_60_Male', 'Age_45_60_Female', 'Age_45_60_Transgender', 'Age_45_60_Total', 'Age_60Plus_Male', 'Age_60Plus_Female', 'Age_60Plus_Transgender', 'Age_60Plus_Total', 'Total_Male', 'Total_Female', 'Total_Transgender', 'Total_All', 'year']
Shape: (288, 32)

In [82]:
# Keep only Total columns
cols_to_keep = ['S.No.', 'Category', 'State/UT', 
                'Age_Below14_Total', 'Age_14_18_Total', 
                'Age_18_30_Total', 'Age_30_45_Total',
                'Age_45_60_Total', 'Age_60Plus_Total',
                'Total_All', 'year']

df_age_clean = df_age[cols_to_keep].copy()

print("After — columns:", df_age_clean.columns.tolist())
print("Shape:", df_age_clean.shape)
print("\nSample data:")
df_age_clean.head(3)

After — columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Total', 'Age_14_18_Total', 'Age_18_30_Total', 'Age_30_45_Total', 'Age_45_60_Total', 'Age_60Plus_Total', 'Total_All', 'year']
Shape: (288, 11)

Sample data:

   S.No. Category           State/UT  Age_Below14_Total  Age_14_18_Total  Age_18_30_Total  Age_30_45_Total  Age_45_60_Total  Age_60Plus_Total  Total_All  year
0      1    State     ANDHRA PRADESH                572              770             4460             5761             3844              2005      17412  2015
1      2    State  ARUNACHAL PRADESH                 21               31              113              135               54                15        369  2015
2      3    State              ASSAM                183              673             1436             1124              709               206       4331  2015

In [83]:
# Save cleaned agewise data
output_path = "../data/processed/agewise_deaths_2015_2022.csv"
df_age_clean.to_csv(output_path, index=False)
print("✅ Saved!")
print(f"Shape: {df_age_clean.shape}")

✅ Saved!
Shape: (288, 11)

In [84]:
import os
import pandas as pd

processed_path = "../data/processed/"
files = os.listdir(processed_path)
print("Processed files:")
for f in sorted(files):
    df = pd.read_csv(processed_path + f)
    print(f"\n📁 {f}")
    print(f"   Shape: {df.shape}")
    print(f"   Columns: {df.columns.tolist()}")

Processed files:

📁 agewise_deaths_2015_2022.csv
   Shape: (288, 11)
   Columns: ['S.No.', 'Category', 'State/UT', 'Age_Below14_Total', 'Age_14_18_Total', 'Age_18_30_Total', 'Age_30_45_Total', 'Age_45_60_Total', 'Age_60Plus_Total', 'Total_All', 'year']

📁 monthly_traffic_accidents_2015_2022.csv
   Shape: (280, 56)
   Columns: ['S.No.', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_January', 'Railway_Crossing_Accidents_February', 'Railway_Crossing_Accidents_March', 'Railway_Crossing_Accidents_April', 'Railway_Crossing_Accidents_May', 'Railway_Crossing_Accidents_June', 'Railway_Crossing_Accidents_July', 'Railway_Crossing_Accidents_August', 'Railway_Crossing_Accidents_September', 'Railway_Crossing_Accidents_October', 'Railway_Crossing_Accidents_November', 'Railway_Crossing_Accidents_December', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_January', 'Railway_Accidents_February', 'Railway_Accidents_March', 'Railway_Accidents_April', 'Railway_Accidents_May', 'Railway_Accidents_June', 'Railway_Accidents_July', 'Railway_Accidents_August', 'Railway_Accidents_September', 'Railway_Accidents_October', 'Railway_Accidents_November', 'Railway_Accidents_December', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_January', 'Total_Traffic_Accidents_February', 'Total_Traffic_Accidents_March', 'Total_Traffic_Accidents_April', 'Total_Traffic_Accidents_May', 'Total_Traffic_Accidents_June', 'Total_Traffic_Accidents_July', 'Total_Traffic_Accidents_August', 'Total_Traffic_Accidents_September', 'Total_Traffic_Accidents_October', 'Total_Traffic_Accidents_November', 'Total_Traffic_Accidents_December', 'Total_Traffic_Accidents_Total', 'year']

📁 state_deaths_2015_2022.csv
   Shape: (229, 9)
   Columns: ['category', 'state_ut_city', 'deaths_nature', 'deaths_unnatural', 'deaths_others', 'deaths_total', 'population_lakh', 'death_rate', 'year']

📁 state_ut_deaths_2015_2022.csv
   Shape: (288, 10)
   Columns: ['S.No.', 'Category', 'State/UT', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Pct_Share', 'Population_Lakh', 'Death_Rate', 'year']

📁 timewise_traffic_accidents_2015_2022.csv
   Shape: (288, 40)
   Columns: ['S.No.', 'Category', 'State/UT', 'Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total', 'Railway_Crossing_Accidents_0000_hrs_to_0300_hrs_Night', 'Railway_Crossing_Accidents_0300_hrs_to_0600_hrs_Night', 'Railway_Crossing_Accidents_0600_hrs_to_0900_hrs_Day', 'Railway_Crossing_Accidents_0900_hrs_to_1200_hrs_Day', 'Railway_Crossing_Accidents_1200_hrs_to_1500_hrs_Day', 'Railway_Crossing_Accidents_1500_hrs_to_1800_hrs_Day', 'Railway_Crossing_Accidents_1800_hrs_to_2100_hrs_Night', 'Railway_Crossing_Accidents_2100_hrs_to_2400_hrs_Night', 'Railway_Crossing_Accidents_Total', 'Railway_Accidents_0000_hrs_to_0300_hrs_Night', 'Railway_Accidents_0300_hrs_to_0600_hrs_Night', 'Railway_Accidents_0600_hrs_to_0900_hrs_Day', 'Railway_Accidents_0900_hrs_to_1200_hrs_Day', 'Railway_Accidents_1200_hrs_to_1500_hrs_Day', 'Railway_Accidents_1500_hrs_to_1800_hrs_Day', 'Railway_Accidents_1800_hrs_to_2100_hrs_Night', 'Railway_Accidents_2100_hrs_to_2400_hrs_Night', 'Railway_Accidents_Total', 'Total_Traffic_Accidents_0000_hrs_to_0300_hrs_Night', 'Total_Traffic_Accidents_0300_hrs_to_0600_hrs_Night', 'Total_Traffic_Accidents_0600_hrs_to_0900_hrs_Day', 'Total_Traffic_Accidents_0900_hrs_to_1200_hrs_Day', 'Total_Traffic_Accidents_1200_hrs_to_1500_hrs_Day', 'Total_Traffic_Accidents_1500_hrs_to_1800_hrs_Day', 'Total_Traffic_Accidents_1800_hrs_to_2100_hrs_Night', 'Total_Traffic_Accidents_2100_hrs_to_2400_hrs_Night', 'Total_Traffic_Accidents_Total', 'year']

In [85]:
# Load monthly traffic data
df_monthly = pd.read_csv("../data/processed/monthly_traffic_accidents_2015_2022.csv")

# Keep only Road Accidents columns
road_monthly_cols = ['S.No.', 'Category', 'State/UT'] + \
                    [c for c in df_monthly.columns if 'Road_Accidents' in c] + \
                    ['year']

df_monthly_clean = df_monthly[road_monthly_cols].copy()

print("Monthly — Before:", df_monthly.shape)
print("Monthly — After:", df_monthly_clean.shape)
print("\nColumns:", df_monthly_clean.columns.tolist())

Monthly — Before: (280, 56)
Monthly — After: (280, 17)

Columns: ['S.No.', 'Category', 'State/UT', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'year']

In [86]:
# Load timewise traffic data
df_time = pd.read_csv("../data/processed/timewise_traffic_accidents_2015_2022.csv")

# Keep only Road Accidents columns
road_time_cols = ['S.No.', 'Category', 'State/UT'] + \
                 [c for c in df_time.columns if 'Road_Accidents' in c] + \
                 ['year']

df_time_clean = df_time[road_time_cols].copy()

print("Timewise — Before:", df_time.shape)
print("Timewise — After:", df_time_clean.shape)
print("\nColumns:", df_time_clean.columns.tolist())

Timewise — Before: (288, 40)
Timewise — After: (288, 13)

Columns: ['S.No.', 'Category', 'State/UT', 'Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total', 'year']

In [87]:
# Save monthly
df_monthly_clean.to_csv("../data/processed/monthly_traffic_accidents_2015_2022.csv", index=False)
print("✅ Monthly saved!")

# Save timewise
df_time_clean.to_csv("../data/processed/timewise_traffic_accidents_2015_2022.csv", index=False)
print("✅ Timewise saved!")

# Delete old state_deaths file
import os
old_file = "../data/processed/state_deaths_2015_2022.csv"
if os.path.exists(old_file):
    os.remove(old_file)
    print("✅ Old state_deaths file deleted!")

✅ Monthly saved!
✅ Timewise saved!
✅ Old state_deaths file deleted!

In [88]:
for year in years:
    for table in ['1A.1', '1A.2']:
        filename = f"ADSI_{year}_Table_{table}.csv"
        try:
            df = pd.read_csv(RAW_DATA_PATH + filename, encoding='utf-8')
        except:
            df = pd.read_csv(RAW_DATA_PATH + filename, encoding='latin-1')
        print(f"\n{year} — Table {table} — Shape: {df.shape}")
        for col in df.columns:
            print(f"  {repr(col)}")

2015 — Table 1A.1 — Shape: (93, 16)
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - 2014'
  'Road Accidents - 2015'
  'Road Accidents - % Var.'
  'Railway Accidents - 2014'
  'Railway Accidents - 2015'
  'Railway Accidents - % Var.'
  'Railway Crossing Accidents - 2014'
  'Railway Crossing Accidents - 2015'
  'Railway Crossing Accidents - % Var.'
  'Total Traffic Accidents - 2014'
  'Total Traffic Accidents - 2015'
  'Total Traffic Accidents - % Var.'
  '% Share'

2015 — Table 1A.2 — Shape: (93, 15)
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Cases'
  'Road Accidents - Injured'
  'Road Accidents - Died'
  'Railway Accidents - Cases'
  'Railway Accidents - Injured'
  'Railway Accidents - Died'
  'Railway Crossing Accidents - Cases'
  'Railway Crossing Accidents - Injured'
  'Railway Crossing Accidents - Died'
  'Total Traffic Accidents - Cases'
  'Total Traffic Accidents - Injured'
  'Total Traffic Accidents - Died'

2016 — Table 1A.1 — Shape: (93, 16)
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - 2015'
  'Road Accidents - 2016'
  'Road Accidents - % Var.'
  'Railway Accidents - 2015'
  'Railway Accidents - 2016'
  'Railway Accidents - % Var.'
  'Railway Crossing Accidents - 2015'
  'Railway Crossing Accidents - 2016'
  'Railway Crossing Accidents - % Var.'
  'Total Traffic Accidents - 2015'
  'Total Traffic Accidents - 2016'
  'Total Traffic Accidents - % Var.'
  '% Share'

2016 — Table 1A.2 — Shape: (93, 15)
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Cases'
  'Road Accidents - Injured'
  'Road Accidents - Died'
  'Railway Accidents - Cases'
  'Railway Accidents - Injured'
  'Railway Accidents - Died'
  'Railway Crossing Accidents - Cases'
  'Railway Crossing Accidents - Injured'
  'Railway Crossing Accidents - Died'
  'Total Traffic Accidents - Cases'
  'Total Traffic Accidents - Injured'
  'Total Traffic Accidents - Died'

2017 — Table 1A.1 — Shape: (93, 16)
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - 2016'
  'Road Accidents - 2017'
  'Road Accidents - % Var.'
  'Railway Accidents - 2016'
  'Railway Accidents - 2017'
  'Railway Accidents - % Var.'
  'Railway Crossing Accidents - 2016'
  'Railway Crossing Accidents - 2017'
  'Railway Crossing Accidents - % Var.'
  'Total Traffic Accidents - 2016'
  'Total Traffic Accidents - 2017'
  'Total Traffic Accidents - % Var.'
  '% Share'

2017 — Table 1A.2 — Shape: (93, 15)
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Cases'
  'Road Accidents - Injured'
  'Road Accidents - Died'
  'Railway Accidents - Cases'
  'Railway Accidents - Injured'
  'Railway Accidents - Died'
  'Railway Crossing Accidents - Cases'
  'Railway Crossing Accidents - Injured'
  'Railway Crossing Accidents - Died'
  'Total Traffic Accidents - Cases'
  'Total Traffic Accidents - Injured'
  'Total Traffic Accidents - Died'

2018 — Table 1A.1 — Shape: (93, 16)
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - 2017'
  'Road Accidents - 2018'
  'Road Accidents - % Var.'
  'Railway Accidents - 2017'
  'Railway Accidents - 2018'
  'Railway Accidents - % Var.'
  'Railway Crossing Accidents - 2017'
  'Railway Crossing Accidents - 2018'
  'Railway Crossing Accidents - % Var.'
  'Total Traffic Accidents - 2017'
  'Total Traffic Accidents - 2018'
  'Total Traffic Accidents - % Var.'
  '% Share'

2018 — Table 1A.2 — Shape: (93, 15)
  'Sl. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Cases'
  'Road Accidents - Injured'
  'Road Accidents - Died'
  'Railway Accidents - Cases'
  'Railway Accidents - Injured'
  'Railway Accidents - Died'
  'Railway Crossing Accidents - Cases'
  'Railway Crossing Accidents - Injured'
  'Railway Crossing Accidents - Died'
  'Total Traffic Accidents - Cases'
  'Total Traffic Accidents - Injured'
  'Total Traffic Accidents - Died'

2019 — Table 1A.1 — Shape: (93, 15)
  'Category'
  'State/UT/City'
  'Road Accidents_2018'
  'Road Accidents_2019'
  'Road Accidents_% Var'
  'Railway Accidents_2018'
  'Railway Accidents_2019'
  'Railway Accidents_% Var'
  'Railway Crossing Accidents_2018'
  'Railway Crossing Accidents_2019'
  'Railway Crossing Accidents_% Var'
  'Total Traffic Accidents_2018'
  'Total Traffic Accidents_2019'
  'Total Traffic Accidents_% Var'
  '% Share'

2019 — Table 1A.2 — Shape: (93, 14)
  'Category'
  'State/UT/City'
  'Road Accidents_Case'
  'Road Accidents_Injured'
  'Road Accidents_Died'
  'Railway Accidents_Case'
  'Railway Accidents_Injured'
  'Railway Accidents_Died'
  'Railway Crossing Accidents_Case'
  'Railway Crossing Accidents_Injured'
  'Railway Crossing Accidents_Died'
  'Total Traffic Accidents_Case'
  'Total Traffic Accidents_Injured'
  'Total Traffic Accidents_Died'

2020 — Table 1A.1 — Shape: (93, 16)
  'Si. No.'
  'Category'
  'State/UT'
  'Road Accidents - 2018'
  'Road Accidents - 2019'
  'Road Accidents - % Var'
  'Railway Accidents - 2018'
  'Railway Accidents - 2019'
  'Railway Accidents - % Var'
  'Railway Crossing Accidents - 2018'
  'Railway Crossing Accidents - 2019'
  'Railway Crossing Accidents - % Var'
  'Total Traffic Accidents - 2018'
  'Total Traffic Accidents - 2019'
  'Total Traffic Accidents - % Var'
  '% Share'

2020 — Table 1A.2 — Shape: (93, 15)
  'Si. No.'
  'Category'
  'State/UT/City'
  'Road Accidents - Case'
  'Road Accidents - Injured'
  'Road Accidents - Died'
  'Railway Accidents - Case'
  'Railway Accidents - Injured'
  'Railway Accidents - Died'
  'Railway Crossing Accidents - Case'
  'Railway Crossing Accidents - Injured'
  'Railway Crossing Accidents - Died'
  'Total Traffic Accidents - Case'
  'Total Traffic Accidents - Injured'
  'Total Traffic Accidents - Died'

2021 — Table 1A.1 — Shape: (93, 15)
  'Category'
  'State/UT/City'
  'Road Accidents - 2020'
  'Road Accidents - 2021'
  'Road Accidents - % Var'
  'Railway Accidents - 2020'
  'Railway Accidents - 2021'
  'Railway Accidents - % Var'
  'Railway Crossing Accidents - 2020'
  'Railway Crossing Accidents - 2021'
  'Railway Crossing Accidents - % Var'
  'Total Traffic Accidents - 2020'
  'Total Traffic Accidents - 2021'
  'Total Traffic Accidents - % Var'
  '% Share'

2021 — Table 1A.2 — Shape: (93, 14)
  'Category'
  'State/UT/City'
  'Road Accidents - Case'
  'Road Accidents - Injured'
  'Road Accidents - Died'
  'Railway Accidents - Case'
  'Railway Accidents - Injured'
  'Railway Accidents - Died'
  'Railway Crossing Accidents - Case'
  'Railway Crossing Accidents - Injured'
  'Railway Crossing Accidents - Died'
  'Total Traffic Accidents - Case'
  'Total Traffic Accidents - Injured'
  'Total Traffic Accidents - Died'

2022 — Table 1A.1 — Shape: (93, 15)
  'Sl. No.'
  'State/UT/City'
  'Road Accidents - 2021'
  'Road Accidents - 2022'
  'Road Accidents - % Var.'
  'Railway Accidents - 2021'
  'Railway Accidents - 2022'
  'Railway Accidents - % Var.'
  'Railway Crossing Accidents - 2021'
  'Railway Crossing Accidents - 2022'
  'Railway Crossing Accidents - % Var.'
  'Total Traffic Accidents - 2021'
  'Total Traffic Accidents - 2022'
  'Total Traffic Accidents - % Var.'
  '% Share'

2022 — Table 1A.2 — Shape: (93, 14)
  'Sl. No.'
  'State/UT/City'
  'Road Accidents - Cases'
  'Road Accidents - Injured'
  'Road Accidents - Died'
  'Railway Accidents - Cases'
  'Railway Accidents - Injured'
  'Railway Accidents - Died'
  'Railway Crossing Accidents - Cases'
  'Railway Crossing Accidents - Injured'
  'Railway Crossing Accidents - Died'
  'Total Traffic Accidents - Cases'
  'Total Traffic Accidents - Injured'
  'Total Traffic Accidents - Died'

In [89]:
def load_table_1A_2(year):
    filename = f"ADSI_{year}_Table_1A.2.csv"
    try:
        df = pd.read_csv(RAW_DATA_PATH + filename, encoding='utf-8')
    except:
        df = pd.read_csv(RAW_DATA_PATH + filename, encoding='latin-1')
    
    # Find columns
    cat_cols = [c for c in df.columns if 'Category' in c or c.strip() == 'Category']
    state_cols = [c for c in df.columns if 'State' in c]
    cases_cols = [c for c in df.columns if 'Road' in c and ('Case' in c or 'Cases' in c)]
    injured_cols = [c for c in df.columns if 'Road' in c and 'Injured' in c]
    died_cols = [c for c in df.columns if 'Road' in c and 'Died' in c]
    
    # Rename to standard
    result = pd.DataFrame()
    
    if len(cat_cols) > 0:
        cat_col = cat_cols[0]
        state_col = state_cols[0]
        df = df[df[cat_col].astype(str).str.strip().isin(['State', 'Union Territory', 'Union Territories', 'UT'])].copy()
        result['Category'] = df[cat_col].replace({'Union Territories': 'UT', 'Union Territory': 'UT'})
        result['State/UT'] = df[state_col].str.strip().str.upper()
    else:
        # 2022 - no category
        state_col = state_cols[0]
        valid_list = []
        for val in df[state_col].tolist():
            if 'Total' in str(val):
                break
            valid_list.append(val)
        df = df[df[state_col].isin(valid_list)].copy()
        result['Category'] = 'State'
        result['State/UT'] = df[state_col].str.strip().str.upper()
    
    result['Road_Accidents'] = df[cases_cols[0]].values
    result['Road_Injured'] = df[injured_cols[0]].values
    result['Road_Deaths'] = df[died_cols[0]].values
    result['year'] = year
    
    # Remove TOTAL rows
    result = result[~result['State/UT'].str.contains('TOTAL')].copy()
    result = result.reset_index(drop=True)
    result.insert(0, 'S.No.', range(1, len(result)+1))
    
    return result

# Load all years
all_1A2_data = []
for year in years:
    try:
        df = load_table_1A_2(year)
        all_1A2_data.append(df)
        print(f"✅ {year} — {len(df)} rows, Categories: {df['Category'].unique().tolist()}")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 — 36 rows, Categories: ['State', 'UT']
✅ 2016 — 36 rows, Categories: ['State', 'UT']
✅ 2017 — 36 rows, Categories: ['State', 'UT']
✅ 2018 — 36 rows, Categories: ['State', 'UT']
✅ 2019 — 36 rows, Categories: ['State', 'UT']
✅ 2020 — 36 rows, Categories: ['State', 'UT']
✅ 2021 — 36 rows, Categories: ['State', 'UT']
✅ 2022 — 28 rows, Categories: [nan]

In [90]:
# Check 2022 structure
df_2022 = pd.read_csv(RAW_DATA_PATH + "ADSI_2022_Table_1A.2.csv")
print("Columns:", df_2022.columns.tolist())
print("\nFirst 40 State/UT values:")
print(df_2022['State/UT/City'].tolist()[:40])

Columns: ['Sl. No.', 'State/UT/City', 'Road Accidents - Cases', 'Road Accidents - Injured', 'Road Accidents - Died', 'Railway Accidents - Cases', 'Railway Accidents - Injured', 'Railway Accidents - Died', 'Railway Crossing Accidents - Cases', 'Railway Crossing Accidents - Injured', 'Railway Crossing Accidents - Died', 'Total Traffic Accidents - Cases', 'Total Traffic Accidents - Injured', 'Total Traffic Accidents - Died']

First 40 State/UT values:
['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Total (States)', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nicoabr Haveli and Daman and Diu', 'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry', 'Total (UTs)', 'Total (All India)', 'Agra']

In [91]:
def load_table_1A_2(year):
    filename = f"ADSI_{year}_Table_1A.2.csv"
    try:
        df = pd.read_csv(RAW_DATA_PATH + filename, encoding='utf-8')
    except:
        df = pd.read_csv(RAW_DATA_PATH + filename, encoding='latin-1')
    
    cat_cols = [c for c in df.columns if 'Category' in c or c.strip() == 'Category']
    state_cols = [c for c in df.columns if 'State' in c]
    cases_cols = [c for c in df.columns if 'Road' in c and ('Case' in c or 'Cases' in c)]
    injured_cols = [c for c in df.columns if 'Road' in c and 'Injured' in c]
    died_cols = [c for c in df.columns if 'Road' in c and 'Died' in c]
    
    ut_names = {
        2015: 'Union Territories', 2016: 'Union Territory',
        2017: 'Union Territory', 2018: 'Union Territory',
        2019: 'UT', 2020: 'Union Territories',
        2021: 'UT', 2022: None
    }
    
    result = pd.DataFrame()
    
    if len(cat_cols) > 0:
        cat_col = cat_cols[0]
        state_col = state_cols[0]
        valid_categories = ['State', ut_names[year]]
        df = df[df[cat_col].astype(str).str.strip().isin(valid_categories)].copy()
        result['Category'] = df[cat_col].replace({
            'Union Territories': 'UT', 'Union Territory': 'UT'
        })
        result['State/UT'] = df[state_col].str.strip().str.upper()
    else:
        # 2022 — extract before Total (UTs)
        state_col = state_cols[0]
        valid_list = []
        for val in df[state_col].tolist():
            if 'Total (UTs)' in str(val) or 'Total (All India)' in str(val):
                break
            if 'Total' not in str(val):
                valid_list.append(val)
        df = df[df[state_col].isin(valid_list)].copy()
        
        # Assign category — States vs UTs
        states_2022 = ['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
                       'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
                       'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra',
                       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
                       'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
                       'Uttar Pradesh', 'Uttarakhand', 'West Bengal']
        df['Category'] = df[state_col].apply(
            lambda x: 'State' if x in states_2022 else 'UT'
        )
        result['Category'] = df['Category']
        result['State/UT'] = df[state_col].str.strip().str.upper()
    
    result['Road_Accidents'] = df[cases_cols[0]].values
    result['Road_Injured'] = df[injured_cols[0]].values
    result['Road_Deaths'] = df[died_cols[0]].values
    result['year'] = year
    
    # Remove TOTAL rows
    result = result[~result['State/UT'].str.contains('TOTAL')].copy()
    result = result.reset_index(drop=True)
    result.insert(0, 'S.No.', range(1, len(result)+1))
    
    return result

# Load all years
all_1A2_data = []
for year in years:
    try:
        df = load_table_1A_2(year)
        all_1A2_data.append(df)
        print(f"✅ {year} — {len(df)} rows, Categories: {df['Category'].unique().tolist()}")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 — 36 rows, Categories: ['State', 'UT']
✅ 2016 — 36 rows, Categories: ['State', 'UT']
✅ 2017 — 36 rows, Categories: ['State', 'UT']
✅ 2018 — 36 rows, Categories: ['State', 'UT']
✅ 2019 — 36 rows, Categories: ['State', 'UT']
✅ 2020 — 36 rows, Categories: ['State', 'UT']
✅ 2021 — 36 rows, Categories: ['State', 'UT']
✅ 2022 — 36 rows, Categories: ['State', 'UT']

In [92]:
# Merge all years
df_road = pd.concat(all_1A2_data, ignore_index=True)

# Calculate Pct_Change year over year for each State/UT
df_road = df_road.sort_values(['State/UT', 'year']).reset_index(drop=True)

df_road['Pct_Change'] = df_road.groupby('State/UT')['Road_Accidents'].pct_change() * 100
df_road['Pct_Change'] = df_road['Pct_Change'].round(2)

# Reset S.No.
df_road['S.No.'] = range(1, len(df_road)+1)

print("Final shape:", df_road.shape)
print("\nYear wise count:")
print(df_road.groupby('year')['State/UT'].count())
print("\nSample data:")
df_road.head(10)

Final shape: (288, 8)

Year wise count:
year
2015    36
2016    36
2017    36
2018    36
2019    36
2020    36
2021    36
2022    36
Name: State/UT, dtype: int64

Sample data:

   S.No. Category                     State/UT  Road_Accidents  Road_Injured  Road_Deaths  year  Pct_Change
0      1       UT                A & N ISLANDS             258           331           23  2015         NaN
1      2       UT                A & N ISLANDS             238           323           17  2016       -7.75
2      3       UT                A & N ISLANDS             189           263           21  2017      -20.59
3      4       UT                A & N ISLANDS             254           260           19  2018       34.39
4      5       UT                A & N ISLANDS             141           145           14  2020      -44.49
5      6       UT                 A & NISLANDS             230           207           20  2019         NaN
6      7       UT  ANDAMAN AND NICOBAR ISLANDS             117            97           22  2021         NaN
7      8       UT  ANDAMAN AND NICOBAR ISLANDS             141           136           19  2022       20.51
8      9    State               ANDHRA PRADESH           22839         29439         8297  2015         NaN
9     10    State               ANDHRA PRADESH           23658         30051         8541  2016        3.59

In [93]:
# Check all unique State/UT names across all years
all_states = set()
for df in all_1A2_data:
    all_states.update(df['State/UT'].unique())

print("All unique State/UT names:")
for s in sorted(all_states):
    print(f"  {repr(s)}")

All unique State/UT names:
  'A & N ISLANDS'
  'A & NISLANDS'
  'ANDAMAN AND NICOBAR ISLANDS'
  'ANDHRA PRADESH'
  'ARUNACHAL PRADESH'
  'ASSAM'
  'BIHAR'
  'CHANDIGARH'
  'CHHATTISGARH'
  'D & N HAVELI'
  'D & N HAVELI AND DAMAN & DIU'
  'DADRA AND NAGAR HAVELI AND DAMAN AND DIU'
  'DADRA AND NICOABR HAVELI AND DAMAN AND DIU'
  'DAMAN & DIU'
  'DELHI'
  'DELHI (UT)'
  'GOA'
  'GUJARAT'
  'HARYANA'
  'HIMACHAL PRADESH'
  'JAMMU & KASHMIR'
  'JAMMU AND KASHMIR'
  'JHARKHAND'
  'KARNATAKA'
  'KERALA'
  'LADAKH'
  'LAKSHADWEEP'
  'MADHYA PRADESH'
  'MAHARASHTRA'
  'MANIPUR'
  'MEGHALAYA'
  'MIZORAM'
  'NAGALAND'
  'ODISHA'
  'PUDUCHERRY'
  'PUNJAB'
  'RAJASTHAN'
  'SIKKIM'
  'TAMIL NADU'
  'TELANGANA'
  'TRIPURA'
  'UTTAR PRADESH'
  'UTTARAKHAND'
  'WEST BENGAL'

In [94]:
# Standard name mapping
name_map = {
    'A & N ISLANDS': 'ANDAMAN AND NICOBAR ISLANDS',
    'A & NISLANDS': 'ANDAMAN AND NICOBAR ISLANDS',
    'D & N HAVELI': 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
    'D & N HAVELI AND DAMAN & DIU': 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
    'DADRA AND NICOABR HAVELI AND DAMAN AND DIU': 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
    'DAMAN & DIU': 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
    'DELHI (UT)': 'DELHI',
    'JAMMU & KASHMIR': 'JAMMU AND KASHMIR',
}

# Numeric columns to sum when merging
num_cols = ['Road_Accidents', 'Road_Injured', 'Road_Deaths']

def fix_names_and_merge(df):
    # Apply name mapping
    df['State/UT'] = df['State/UT'].replace(name_map)
    
    # Merge duplicate rows (DADRA + DAMAN, J&K + LADAKH)
    df = df.groupby(['Category', 'State/UT', 'year'], as_index=False)[num_cols].sum()
    
    # Fix Category for merged UTs
    ut_list = ['ANDAMAN AND NICOBAR ISLANDS', 'CHANDIGARH',
               'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
               'DELHI', 'JAMMU AND KASHMIR', 'LADAKH',
               'LAKSHADWEEP', 'PUDUCHERRY']
    df['Category'] = df['State/UT'].apply(
        lambda x: 'UT' if x in ut_list else 'State'
    )
    
    df = df.sort_values(['year', 'Category', 'State/UT']).reset_index(drop=True)
    df.insert(0, 'S.No.', range(1, len(df)+1))
    
    return df

# Apply to 1A.2 data
df_road = pd.concat(all_1A2_data, ignore_index=True)
df_road = fix_names_and_merge(df_road)

print("Final shape:", df_road.shape)
print("\nYear wise count:")
print(df_road.groupby('year')['State/UT'].count())
print("\nUnique State/UT names:")
print(sorted(df_road['State/UT'].unique()))

Final shape: (283, 7)

Year wise count:
year
2015    35
2016    35
2017    35
2018    35
2019    35
2020    36
2021    36
2022    36
Name: State/UT, dtype: int64

Unique State/UT names:
['ANDAMAN AND NICOBAR ISLANDS', 'ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH', 'CHHATTISGARH', 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'DELHI', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU AND KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'LADAKH', 'LAKSHADWEEP', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUDUCHERRY', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL']

In [95]:
def fix_names_and_merge(df):
    # Apply name mapping
    df['State/UT'] = df['State/UT'].replace(name_map)
    
    # Merge LADAKH into JAMMU AND KASHMIR
    df['State/UT'] = df['State/UT'].replace({'LADAKH': 'JAMMU AND KASHMIR'})
    
    # Merge duplicate rows
    df = df.groupby(['State/UT', 'year'], as_index=False)[num_cols].sum()
    
    # Fix Category
    ut_list = ['ANDAMAN AND NICOBAR ISLANDS', 'CHANDIGARH',
               'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
               'DELHI', 'JAMMU AND KASHMIR',
               'LAKSHADWEEP', 'PUDUCHERRY']
    df['Category'] = df['State/UT'].apply(
        lambda x: 'UT' if x in ut_list else 'State'
    )
    
    df = df.sort_values(['year', 'Category', 'State/UT']).reset_index(drop=True)
    df.insert(0, 'S.No.', range(1, len(df)+1))
    
    return df

# Apply again
df_road = pd.concat(all_1A2_data, ignore_index=True)
df_road = fix_names_and_merge(df_road)

print("Final shape:", df_road.shape)
print("\nYear wise count:")
print(df_road.groupby('year')['State/UT'].count())
print("\nUnique State/UT names:")
print(sorted(df_road['State/UT'].unique()))

Final shape: (280, 7)

Year wise count:
year
2015    35
2016    35
2017    35
2018    35
2019    35
2020    35
2021    35
2022    35
Name: State/UT, dtype: int64

Unique State/UT names:
['ANDAMAN AND NICOBAR ISLANDS', 'ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH', 'CHHATTISGARH', 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'DELHI', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU AND KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'LAKSHADWEEP', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUDUCHERRY', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL']

In [96]:
# Sort alphabetically within each year
df_road = df_road.sort_values(['year', 'State/UT']).reset_index(drop=True)
df_road['S.No.'] = range(1, len(df_road)+1)

print("Final shape:", df_road.shape)
print("\nYear wise count:")
print(df_road.groupby('year')['State/UT'].count())
print("\n2015 States/UTs in order:")
print(df_road[df_road['year']==2015]['State/UT'].tolist())

Final shape: (280, 7)

Year wise count:
year
2015    35
2016    35
2017    35
2018    35
2019    35
2020    35
2021    35
2022    35
Name: State/UT, dtype: int64

2015 States/UTs in order:
['ANDAMAN AND NICOBAR ISLANDS', 'ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH', 'CHHATTISGARH', 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'DELHI', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU AND KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'LAKSHADWEEP', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUDUCHERRY', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL']

In [97]:
# Save road accidents data
output_path = "../data/processed/road_accidents_2015_2022.csv"
df_road.to_csv(output_path, index=False)
print("✅ Saved!")
print(f"Shape: {df_road.shape}")
print(f"\nColumns: {df_road.columns.tolist()}")

✅ Saved!
Shape: (280, 7)

Columns: ['S.No.', 'State/UT', 'year', 'Road_Accidents', 'Road_Injured', 'Road_Deaths', 'Category']

In [98]:
def fix_all_files(df, num_cols):
    # Apply name mapping
    df['State/UT'] = df['State/UT'].replace(name_map)
    
    # Merge LADAKH into JAMMU AND KASHMIR
    df['State/UT'] = df['State/UT'].replace({'LADAKH': 'JAMMU AND KASHMIR'})
    
    # Group and sum numeric columns
    group_cols = ['State/UT', 'year']
    df = df.groupby(group_cols, as_index=False)[num_cols].sum()
    
    # Fix Category
    ut_list = ['ANDAMAN AND NICOBAR ISLANDS', 'CHANDIGARH',
               'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
               'DELHI', 'JAMMU AND KASHMIR',
               'LAKSHADWEEP', 'PUDUCHERRY']
    df['Category'] = df['State/UT'].apply(
        lambda x: 'UT' if x in ut_list else 'State'
    )
    
    # Sort alphabetically
    df = df.sort_values(['year', 'State/UT']).reset_index(drop=True)
    df.insert(0, 'S.No.', range(1, len(df)+1))
    
    return df

# 1. state_ut_deaths
df1 = pd.read_csv("../data/processed/state_ut_deaths_2015_2022.csv")
df1 = df1.rename(columns={'State/UT': 'State/UT'})
num_cols_1 = ['Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Population_Lakh']
df1 = fix_all_files(df1, num_cols_1)
print("state_ut_deaths:", df1.shape)
print(df1.groupby('year')['State/UT'].count())

state_ut_deaths: (280, 8)
year
2015    35
2016    35
2017    35
2018    35
2019    35
2020    35
2021    35
2022    35
Name: State/UT, dtype: int64

In [99]:
# 2. agewise_deaths
df2 = pd.read_csv("../data/processed/agewise_deaths_2015_2022.csv")
num_cols_2 = ['Age_Below14_Total', 'Age_14_18_Total', 'Age_18_30_Total',
              'Age_30_45_Total', 'Age_45_60_Total', 'Age_60Plus_Total', 'Total_All']
df2 = fix_all_files(df2, num_cols_2)
print("agewise_deaths:", df2.shape)
print(df2.groupby('year')['State/UT'].count())

# 3. monthly_traffic
df3 = pd.read_csv("../data/processed/monthly_traffic_accidents_2015_2022.csv")
num_cols_3 = ['Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March',
              'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June',
              'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September',
              'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December',
              'Road_Accidents_Total']
df3 = fix_all_files(df3, num_cols_3)
print("\nmonthly_traffic:", df3.shape)
print(df3.groupby('year')['State/UT'].count())

# 4. timewise_traffic
df4 = pd.read_csv("../data/processed/timewise_traffic_accidents_2015_2022.csv")
num_cols_4 = ['Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night',
              'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day',
              'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day',
              'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night',
              'Road_Accidents_Total']
df4 = fix_all_files(df4, num_cols_4)
print("\ntimewise_traffic:", df4.shape)
print(df4.groupby('year')['State/UT'].count())

agewise_deaths: (280, 11)
year
2015    35
2016    35
2017    35
2018    35
2019    35
2020    35
2021    35
2022    35
Name: State/UT, dtype: int64

monthly_traffic: (273, 17)
year
2015    35
2016    35
2017    35
2018    35
2019    35
2020    35
2021    35
2022    28
Name: State/UT, dtype: int64

timewise_traffic: (280, 13)
year
2015    35
2016    35
2017    35
2018    35
2019    35
2020    35
2021    35
2022    35
Name: State/UT, dtype: int64

In [100]:
# Check 2022 monthly traffic State/UT names
df3_raw = pd.read_csv("../data/processed/monthly_traffic_accidents_2015_2022.csv")
print("2022 State/UT values:")
print(df3_raw[df3_raw['year']==2022]['State/UT'].tolist())

2022 State/UT values:
['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL']

In [101]:
# Check 2022 raw Table 1A.5
df_raw_2022 = pd.read_csv(RAW_DATA_PATH + "ADSI_2022_Table_1A.5.csv")
print("All values:")
print(df_raw_2022['State/UT/Cities'].tolist())

All values:
['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Total (States)', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi (UT)', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry', 'Total (UTs)', 'Total (All India)', 'Agra', 'Ahmedabad', 'Amritsar', 'Asansol', 'Aurangabad', 'Bengaluru', 'Bhopal', 'Chandigarh (City)', 'Chennai', 'Coimbatore', 'Delhi (City)', 'Dhanbad', 'Durg Bhilainagar', 'Faridabad', 'Ghaziabad', 'Gwalior', 'Hyderabad', 'Indore', 'Jabalpur', 'Jaipur', 'Jamshedpur', 'Jodhpur', 'Kannur', 'Kanpur', 'Kochi', 'Kolkata', 'Kollam', 'Kota', 'Kozhikode', 'Lucknow', 'Ludhiana', 'Madurai', 'Malappuram', 'Meerut', 'Mumbai', 'Nagpur', 'Nasik', 'Patna', 'Prayagraj +', 'Pune', 'Raipur', 'Rajkot', 'Ranchi', 'Srinagar', 'Surat', 'Thiruvananthapuram', 'Thrissur', 'Tiruchirappalli', 'Vadodara', 'Varanasi', 'Vasai Virar', 'Vijayawada', 'Vishakhapatnam', 'Total (Cities)']

In [102]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    ut_names = {
        2015: 'Union Territories', 2016: 'Union Territory',
        2017: 'Union Territory', 2018: 'Union Territory',
        2019: 'UT', 2020: 'Union Territories',
        2021: 'UT', 2022: None
    }
    
    cat_cols = [c for c in df.columns if 'Category' in c or c.strip() == 'Category']
    state_cols = [c for c in df.columns if 'State' in c]
    
    if len(cat_cols) > 0:
        cat_col = cat_cols[0]
        state_col = state_cols[0]
        valid_categories = ['State', ut_names[year]]
        df = df[df[cat_col].astype(str).str.strip().isin(valid_categories)].copy()
        df = df.rename(columns={cat_col: 'category', state_col: 'state_ut_city'})
    else:
        # 2022 — extract before Total (Cities)
        state_col = state_cols[0]
        valid_list = []
        for val in df[state_col].tolist():
            if 'Total (UTs)' in str(val) or 'Total (All India)' in str(val):
                break
            if 'Total' not in str(val):
                valid_list.append(val)
        df = df[df[state_col].isin(valid_list)].copy()
        df['category'] = 'State/UT'
        df = df.rename(columns={state_col: 'state_ut_city'})
    
    # Standardize columns
    df = standardize_columns(df, year)
    
    # Uppercase
    df['State/UT'] = df['State/UT'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['State/UT'].str.contains('TOTAL')].copy()
    
    # Year add
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Reload all years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_month_data = []

for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states/UTs")
    except Exception as e:
        print(f"❌ {year} error — {e}")

❌ 2015 error — 'State/UT'
❌ 2016 error — 'State/UT'
❌ 2017 error — 'State/UT'
❌ 2018 error — 'State/UT'
❌ 2019 error — 'State/UT'
❌ 2020 error — 'State/UT'
❌ 2021 error — 'State/UT'
❌ 2022 error — 'State/UT'

In [103]:
def load_table_1A_5(year):
    filename = f"ADSI_{year}_Table_1A.5.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    ut_names = {
        2015: 'Union Territories', 2016: 'Union Territory',
        2017: 'Union Territory', 2018: 'Union Territory',
        2019: 'UT', 2020: 'Union Territories',
        2021: 'UT', 2022: None
    }
    
    # Standardize columns FIRST
    df = standardize_columns(df, year)
    
    # Now filter
    if year != 2022:
        valid_categories = ['State', ut_names[year]]
        df = df[df['Category'].astype(str).str.strip().isin(valid_categories)].copy()
    else:
        # 2022 — extract before Total (UTs)
        valid_list = []
        for val in df['State/UT'].tolist():
            if 'Total (UTs)' in str(val) or 'Total (All India)' in str(val):
                break
            if 'Total' not in str(val):
                valid_list.append(val)
        df = df[df['State/UT'].isin(valid_list)].copy()
        df['Category'] = 'State/UT'
    
    # Uppercase
    df['State/UT'] = df['State/UT'].str.strip().str.upper()
    
    # Remove TOTAL rows
    df = df[~df['State/UT'].str.contains('TOTAL')].copy()
    
    # Year add
    df['year'] = year
    df = df.reset_index(drop=True)
    
    return df

# Reload all years
all_month_data = []
for year in years:
    try:
        df = load_table_1A_5(year)
        all_month_data.append(df)
        print(f"✅ {year} — {len(df)} states/UTs")
    except Exception as e:
        print(f"❌ {year} error — {e}")

✅ 2015 — 36 states/UTs
✅ 2016 — 36 states/UTs
✅ 2017 — 36 states/UTs
✅ 2018 — 36 states/UTs
✅ 2019 — 36 states/UTs
✅ 2020 — 36 states/UTs
✅ 2021 — 36 states/UTs
✅ 2022 — 36 states/UTs

In [104]:
# Merge all years
df_monthly_new = pd.concat(all_month_data, ignore_index=True)

# Keep only Road Accidents columns
road_monthly_cols = ['State/UT', 'year'] + \
                    [c for c in df_monthly_new.columns if 'Road_Accidents' in c]
df_monthly_new = df_monthly_new[road_monthly_cols].copy()

# Apply fix
num_cols_3 = ['Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March',
              'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June',
              'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September',
              'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December',
              'Road_Accidents_Total']
df_monthly_new = fix_all_files(df_monthly_new, num_cols_3)

print("Monthly shape:", df_monthly_new.shape)
print("\nYear wise count:")
print(df_monthly_new.groupby('year')['State/UT'].count())

Monthly shape: (280, 17)

Year wise count:
year
2015    35
2016    35
2017    35
2018    35
2019    35
2020    35
2021    35
2022    35
Name: State/UT, dtype: int64

In [105]:
# Save all fixed files
df1.to_csv("../data/processed/state_ut_deaths_2015_2022.csv", index=False)
print("✅ state_ut_deaths saved!")

df2.to_csv("../data/processed/agewise_deaths_2015_2022.csv", index=False)
print("✅ agewise_deaths saved!")

df_monthly_new.to_csv("../data/processed/monthly_traffic_accidents_2015_2022.csv", index=False)
print("✅ monthly_traffic saved!")

df4.to_csv("../data/processed/timewise_traffic_accidents_2015_2022.csv", index=False)
print("✅ timewise_traffic saved!")

df_road.to_csv("../data/processed/road_accidents_2015_2022.csv", index=False)
print("✅ road_accidents saved!")

✅ state_ut_deaths saved!
✅ agewise_deaths saved!
✅ monthly_traffic saved!
✅ timewise_traffic saved!
✅ road_accidents saved!

In [106]:
# Check all processed file names and columns
import os
processed_path = "../data/processed/"
for f in sorted(os.listdir(processed_path)):
    df = pd.read_csv(processed_path + f)
    print(f"\n📁 {f}")
    print(f"   Columns: {df.columns.tolist()}")

📁 agewise_deaths_2015_2022.csv
   Columns: ['S.No.', 'State/UT', 'year', 'Age_Below14_Total', 'Age_14_18_Total', 'Age_18_30_Total', 'Age_30_45_Total', 'Age_45_60_Total', 'Age_60Plus_Total', 'Total_All', 'Category']

📁 monthly_traffic_accidents_2015_2022.csv
   Columns: ['S.No.', 'State/UT', 'year', 'Road_Accidents_January', 'Road_Accidents_February', 'Road_Accidents_March', 'Road_Accidents_April', 'Road_Accidents_May', 'Road_Accidents_June', 'Road_Accidents_July', 'Road_Accidents_August', 'Road_Accidents_September', 'Road_Accidents_October', 'Road_Accidents_November', 'Road_Accidents_December', 'Road_Accidents_Total', 'Category']

📁 road_accidents_2015_2022.csv
   Columns: ['S.No.', 'State/UT', 'year', 'Road_Accidents', 'Road_Injured', 'Road_Deaths', 'Category']

📁 state_ut_deaths_2015_2022.csv
   Columns: ['S.No.', 'State/UT', 'year', 'Deaths_Natural', 'Deaths_Other_Causes', 'Deaths_Total', 'Population_Lakh', 'Category']

📁 timewise_traffic_accidents_2015_2022.csv
   Columns: ['S.No.', 'State/UT', 'year', 'Road_Accidents_0000_hrs_to_0300_hrs_Night', 'Road_Accidents_0300_hrs_to_0600_hrs_Night', 'Road_Accidents_0600_hrs_to_0900_hrs_Day', 'Road_Accidents_0900_hrs_to_1200_hrs_Day', 'Road_Accidents_1200_hrs_to_1500_hrs_Day', 'Road_Accidents_1500_hrs_to_1800_hrs_Day', 'Road_Accidents_1800_hrs_to_2100_hrs_Night', 'Road_Accidents_2100_hrs_to_2400_hrs_Night', 'Road_Accidents_Total', 'Category']

In [107]:
import os

# Drop agewise file
os.remove("../data/processed/agewise_deaths_2015_2022.csv")
print("✅ agewise_deaths_2015_2022.csv deleted!")

# Rename traffic files to road
os.rename("../data/processed/monthly_traffic_accidents_2015_2022.csv",
          "../data/processed/monthly_road_accidents_2015_2022.csv")
print("✅ monthly_traffic renamed to monthly_road!")

os.rename("../data/processed/timewise_traffic_accidents_2015_2022.csv",
          "../data/processed/timewise_road_accidents_2015_2022.csv")
print("✅ timewise_traffic renamed to timewise_road!")

# Verify
print("\nFinal processed files:")
for f in sorted(os.listdir("../data/processed/")):
    df = pd.read_csv("../data/processed/" + f)
    print(f"  📁 {f} — {df.shape}")

✅ agewise_deaths_2015_2022.csv deleted!
✅ monthly_traffic renamed to monthly_road!
✅ timewise_traffic renamed to timewise_road!

Final processed files:
  📁 monthly_road_accidents_2015_2022.csv — (280, 17)
  📁 road_accidents_2015_2022.csv — (280, 7)
  📁 state_ut_deaths_2015_2022.csv — (280, 8)
  📁 timewise_road_accidents_2015_2022.csv — (280, 13)