# 🌑 Dark Hours of India
## Notebook 1 — Data Cleaning & Exploration

**Objective:** Load all 64 NCRB ADSI CSV files (2015-2022), 
understand their structure, clean them, and prepare for analysis.

**Tables in this notebook:**
- Table 1.2 — State/UT wise Accidental Deaths
- Table 1.4 — Age & Gender wise Deaths
- Table 1.9 / 1.10 — Cause wise Deaths
- Table 1.11 / 1.12 — Fire Accidents
- Table 1A.1 — Traffic Accidents Overview
- Table 1A.2 — Traffic Injuries & Deaths
- Table 1A.5 — Month wise Traffic Accidents
- Table 1A.6 — Time wise Traffic Accidents

In [1]:
# Importing all required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import glob

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.width', 1000)

print("✅ All libraries imported successfully!")
print(f"Pandas version: {pd.__version__}")
print(f"Numpy version: {np.__version__}")

Matplotlib is building the font cache; this may take a moment.

✅ All libraries imported successfully!
Pandas version: 3.0.2
Numpy version: 2.4.4

In [2]:
# Setting up data path
import os

# Path to raw data
RAW_DATA_PATH = "../data/raw/"

# List all files
all_files = sorted(os.listdir(RAW_DATA_PATH))
print(f"✅ Total files found: {len(all_files)}")
print("\n📁 All files:")
for f in all_files:
    print(f"  {f}")

✅ Total files found: 64

📁 All files:
  ADSI_2015_Table_1.11.csv
  ADSI_2015_Table_1.2.csv
  ADSI_2015_Table_1.4.csv
  ADSI_2015_Table_1.9.csv
  ADSI_2015_Table_1A.1.csv
  ADSI_2015_Table_1A.2.csv
  ADSI_2015_Table_1A.5.csv
  ADSI_2015_Table_1A.6.csv
  ADSI_2016_Table_1.11.csv
  ADSI_2016_Table_1.2.csv
  ADSI_2016_Table_1.4.csv
  ADSI_2016_Table_1.9.csv
  ADSI_2016_Table_1A.1.csv
  ADSI_2016_Table_1A.2.csv
  ADSI_2016_Table_1A.5.csv
  ADSI_2016_Table_1A.6.csv
  ADSI_2017_Table_1.11.csv
  ADSI_2017_Table_1.2.csv
  ADSI_2017_Table_1.4.csv
  ADSI_2017_Table_1.9.csv
  ADSI_2017_Table_1A.1.csv
  ADSI_2017_Table_1A.2.csv
  ADSI_2017_Table_1A.5.csv
  ADSI_2017_Table_1A.6.csv
  ADSI_2018_Table_1.11.csv
  ADSI_2018_Table_1.2.csv
  ADSI_2018_Table_1.4.csv
  ADSI_2018_Table_1.9.csv
  ADSI_2018_Table_1A.1.csv
  ADSI_2018_Table_1A.2.csv
  ADSI_2018_Table_1A.5.csv
  ADSI_2018_Table_1A.6.csv
  ADSI_2019_Table_1.11.csv
  ADSI_2019_Table_1.2.csv
  ADSI_2019_Table_1.4.csv
  ADSI_2019_Table_1.9.csv
  ADSI_2019_Table_1A.1.csv
  ADSI_2019_Table_1A.2.csv
  ADSI_2019_Table_1A.5.csv
  ADSI_2019_Table_1A.6.csv
  ADSI_2020_Table_1.10.csv
  ADSI_2020_Table_1.12.csv
  ADSI_2020_Table_1.2.csv
  ADSI_2020_Table_1.4.csv
  ADSI_2020_Table_1A.1.csv
  ADSI_2020_Table_1A.2.csv
  ADSI_2020_Table_1A.5.csv
  ADSI_2020_Table_1A.6.csv
  ADSI_2021_Table_1.10.csv
  ADSI_2021_Table_1.12.csv
  ADSI_2021_Table_1.2.csv
  ADSI_2021_Table_1.4.csv
  ADSI_2021_Table_1A.1.csv
  ADSI_2021_Table_1A.2.csv
  ADSI_2021_Table_1A.5.csv
  ADSI_2021_Table_1A.6.csv
  ADSI_2022_Table_1.10.csv
  ADSI_2022_Table_1.12.csv
  ADSI_2022_Table_1.2.csv
  ADSI_2022_Table_1.4.csv
  ADSI_2022_Table_1A.1.csv
  ADSI_2022_Table_1A.2.csv
  ADSI_2022_Table_1A.5.csv
  ADSI_2022_Table_1A.6.csv

In [3]:
# Pehli file explore karte hain - Table 1.2 (State wise deaths) 2015
df = pd.read_csv(RAW_DATA_PATH + "ADSI_2015_Table_1.2.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

Shape: (93, 10)

Columns:
['Sl. No. (Col.1)', 'Category (Col.2)', 'State/UT/City (Col.3)', 'Total Number of Accidental Deaths - Natural (Col.4)', 'Total Number of Accidental Deaths - Un-natural (Col.5)', 'Total Number of Accidental Deaths - Others (Col.6)', 'Total Number of Accidental Deaths - Total (Col.7)', 'Percentage Share in Total deaths (Col.8)', 'Projected Mid-Year Population* (In Lakh+) (Col.9)', 'Rate of Accidental Deaths (Col.10) = Col.7/Col.9']

First 5 rows:

  Sl. No. (Col.1) Category (Col.2) State/UT/City (Col.3)  Total Number of Accidental Deaths - Natural (Col.4)  Total Number of Accidental Deaths - Un-natural (Col.5)  Total Number of Accidental Deaths - Others (Col.6)  Total Number of Accidental Deaths - Total (Col.7)  Percentage Share in Total deaths (Col.8)  Projected Mid-Year Population* (In Lakh+) (Col.9)  Rate of Accidental Deaths (Col.10) = Col.7/Col.9
0               1            State        ANDHRA PRADESH                                                771                                                15320                                                    1321                                               17412                                       4.2                                              513.4                                              33.9
1               2            State     ARUNACHAL PRADESH                                                 27                                                  319                                                      23                                                 369                                       0.1                                               13.0                                              28.3
2               3            State                 ASSAM                                                236                                                 3910                                                     185                                                4331                                       1.0                                              322.0                                              13.5
3               4            State                 BIHAR                                                417                                                 9470                                                     481                                               10368                                       2.5                                             1031.4                                              10.1
4               5            State          CHHATTISGARH                                                261                                                14333                                                    4679                                               19273                                       4.7                                              256.6                                              75.1

In [4]:
print("Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nUnique Categories:")
print(df['Category\n(Col.2)'].unique())

Shape: (93, 10)

Data Types:
Sl. No. (Col.1)                                               str
Category (Col.2)                                              str
State/UT/City (Col.3)                                         str
Total Number of Accidental Deaths - Natural (Col.4)         int64
Total Number of Accidental Deaths - Un-natural (Col.5)      int64
Total Number of Accidental Deaths - Others (Col.6)          int64
Total Number of Accidental Deaths - Total (Col.7)           int64
Percentage Share in Total deaths (Col.8)                  float64
Projected Mid-Year Population* (In Lakh+) (Col.9)         float64
Rate of Accidental Deaths (Col.10) = Col.7/Col.9          float64
dtype: object

Missing Values:
Sl. No. (Col.1)                                           0
Category (Col.2)                                          0
State/UT/City (Col.3)                                     0
Total Number of Accidental Deaths - Natural (Col.4)       0
Total Number of Accidental Deaths - Un-natural (Col.5)    0
Total Number of Accidental Deaths - Others (Col.6)        0
Total Number of Accidental Deaths - Total (Col.7)         0
Percentage Share in Total deaths (Col.8)                  0
Projected Mid-Year Population* (In Lakh+) (Col.9)         0
Rate of Accidental Deaths (Col.10) = Col.7/Col.9          0
dtype: int64

Unique Categories:

KeyError: 'Category\n(Col.2)'

In [5]:
# Exact column names dekhte hain
for col in df.columns:
    print(repr(col))

'Sl. No. (Col.1)'
'Category (Col.2)'
'State/UT/City (Col.3)'
'Total Number of Accidental Deaths - Natural (Col.4)'
'Total Number of Accidental Deaths - Un-natural (Col.5)'
'Total Number of Accidental Deaths - Others (Col.6)'
'Total Number of Accidental Deaths - Total (Col.7)'
'Percentage Share in Total deaths (Col.8)'
'Projected Mid-Year Population* (In Lakh+) (Col.9)'
'Rate of Accidental Deaths (Col.10) = Col.7/Col.9'

In [6]:
# Unique categories dekhte hain
print("Unique Categories:")
print(df['Category (Col.2)'].unique())

print("\nTotal rows:", len(df))
print("\nState wise rows:", len(df[df['Category (Col.2)'] == 'State']))
print("UT wise rows:", len(df[df['Category (Col.2)'] == 'UT']))
print("City wise rows:", len(df[df['Category (Col.2)'] == 'City']))

Unique Categories:
<StringArray>
['State', 'TOTAL (STATES)', 'Union Territories', 'TOTAL (UTs)', 'TOTAL (ALL INDIA)', 'City', 'TOTAL (CITIES)']
Length: 7, dtype: str

Total rows: 93

State wise rows: 29
UT wise rows: 0
City wise rows: 53

In [7]:
# Column names clean karte hain
df.columns = [
    'sl_no', 'category', 'state_ut_city',
    'deaths_natural', 'deaths_unnatural', 'deaths_others',
    'deaths_total', 'pct_share', 'population_lakh', 'death_rate'
]

# Sirf State level data filter karte hain
df_states = df[df['category'] == 'State'].copy()

print("State level data shape:", df_states.shape)
print("\nStates list:")
print(df_states['state_ut_city'].tolist())

State level data shape: (29, 10)

States list:
['ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL']

In [8]:
# Year column add karo
df_states['year'] = 2015

# Final clean dataframe dekhte hain
print("Final shape:", df_states.shape)
df_states.head()

Final shape: (29, 11)

  sl_no category      state_ut_city  deaths_natural  deaths_unnatural  deaths_others  deaths_total  pct_share  population_lakh  death_rate  year
0     1    State     ANDHRA PRADESH             771             15320           1321         17412        4.2            513.4        33.9  2015
1     2    State  ARUNACHAL PRADESH              27               319             23           369        0.1             13.0        28.3  2015
2     3    State              ASSAM             236              3910            185          4331        1.0            322.0        13.5  2015
3     4    State              BIHAR             417              9470            481         10368        2.5           1031.4        10.1  2015
4     5    State       CHHATTISGARH             261             14333           4679         19273        4.7            256.6        75.1  2015

In [9]:
# Function banate hain jo har year ki Table 1.2 file load aur clean kare
def load_table_1_2(year):
    # 2020 aur uske baad table number alag hai
    if year >= 2020:
        filename = f"ADSI_{year}_Table_1.2.csv"
    else:
        filename = f"ADSI_{year}_Table_1.2.csv"
    
    filepath = RAW_DATA_PATH + filename
    df = pd.read_csv(filepath)
    
    # Column names clean karo
    df.columns = [
        'sl_no', 'category', 'state_ut_city',
        'deaths_natural', 'deaths_unnatural', 'deaths_others',
        'deaths_total', 'pct_share', 'population_lakh', 'death_rate'
    ]
    
    # Sirf State data
    df = df[df['category'] == 'State'].copy()
    
    # Year add karo
    df['year'] = year
    
    return df

# Saare years ke liye load karo aur merge karo
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_data = []

for year in years:
    try:
        df = load_table_1_2(year)
        all_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Sab merge karo
df_deaths = pd.concat(all_data, ignore_index=True)
print(f"\n✅ Final merged shape: {df_deaths.shape}")

✅ 2015 loaded — 29 states
❌ 2016 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements
❌ 2017 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements
❌ 2018 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements
❌ 2019 error — Length mismatch: Expected axis has 8 elements, new values have 10 elements
❌ 2020 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements
❌ 2021 error — Length mismatch: Expected axis has 8 elements, new values have 10 elements
❌ 2022 error — Length mismatch: Expected axis has 9 elements, new values have 10 elements

✅ Final merged shape: (29, 11)

In [10]:
# Har year ki file ke columns dekhte hain
for year in years:
    filename = f"ADSI_{year}_Table_1.2.csv"
    df_temp = pd.read_csv(RAW_DATA_PATH + filename)
    print(f"\n{year} — {len(df_temp.columns)} columns:")
    for col in df_temp.columns:
        print(f"  {repr(col)}")

2015 — 10 columns:
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT/City (Col.3)'
  'Total Number of Accidental Deaths - Natural (Col.4)'
  'Total Number of Accidental Deaths - Un-natural (Col.5)'
  'Total Number of Accidental Deaths - Others (Col.6)'
  'Total Number of Accidental Deaths - Total (Col.7)'
  'Percentage Share in Total deaths (Col.8)'
  'Projected Mid-Year Population* (In Lakh+) (Col.9)'
  'Rate of Accidental Deaths (Col.10) = Col.7/Col.9'

2016 — 9 columns:
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT (Col.3)'
  'Total Number of Accidental Deaths - Forces of Nature (Col.4)'
  'Total Number of Accidental Deaths - Other Causes (Col.5)'
  'Total Number of Accidental Deaths - Total (Col.6)'
  'Percentage Share in Total Deaths (Col.7)'
  'Projected Mid-Year Population* (In Lakh+) (Col.8)'
  'Rate of Accidental Deaths (Col.9) = (Col.6/Col.8)'

2017 — 9 columns:
  'Sl. No. (Col.1)'
  'Category (Col.2)'
  'State/UT'
  'Total Number of Accidental Deaths - Forces of Nature (Col.4)'
  'Total Number of Accidental Deaths - Other Causes (Col.5)'
  'Total Number of Accidental Deaths - Total (Col.6)'
  'Percentage Share in Total Deaths (Col.7)'
  'Projected Mid-Year Population* (in Lakh) (Col.8)'
  'Rate of Accidental Deaths (Col.9 = Col.6/Col.8)'

2018 — 9 columns:
  'Sl. No. - (Col.1)'
  'Category - (Col.2)'
  'State/UT - (Col.3)'
  'Total Number of Accidental Deaths - Forces of Nature - (Col.4)'
  'Total Number of Accidental Deaths - Other Causes - (Col.5)'
  'Total Number of Accidental Deaths - Total - (Col.6)'
  'Percentage Share in Total Deaths - (Col.7)'
  'Projected Mid-Year Population* (in Lakh) - (Col.8)'
  'Rate of Accidental Deaths - (Col.9 = Col.6/Col.8)'

2019 — 8 columns:
  'Category (Col. 1)'
  'State/UT/City (Col. 2)'
  'Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Number of Accidental Deaths - Other Causes (Col. 4)'
  'Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population* (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

2020 — 9 columns:
  'Si. No. (Col. 1)'
  'Category'
  'State/UT/City (Col. 2)'
  'Total Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Total Number of Accidental Deaths - Other Causes (Col. 4)'
  'Total Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

2021 — 8 columns:
  'Category (Col. 1)'
  'State/UT/City (Col. 2)'
  'Number of Accidental Deaths - Forces of Nature (Col. 3)'
  'Number of Accidental Deaths - Other Causes (Col. 4)'
  'Number of Accidental Deaths - Total (Col. 5)'
  'Percentage Share in Total Deaths (Col. 6)'
  'Projected Mid-Year Population (in Lakh) (Col. 7)'
  'Rate of Accidental Deaths (Col. 8) = (Col.5/ Col.7)'

2022 — 9 columns:
  'Sl. No.'
  'Category'
  'State/UT'
  'Total Number of Accidental Deaths - Forces of Nature - Col. (3)'
  'Total Number of Accidental Deaths - Other Causes - Col. (4)'
  'Total Number of Accidental Deaths - Total - Col. (5)'
  'Percentage Share in Total Deaths - Col. (6)'
  'Projected Mid-Year Population* (in Lakh) - Col. (7)'
  'Rate of Accidental Deaths (Col.5/Col.7)'

In [11]:
def load_table_1_2_smart(year):
    filename = f"ADSI_{year}_Table_1.2.csv"
    df = pd.read_csv(RAW_DATA_PATH + filename)
    
    # Common columns jo hamesha chahiye
    result = pd.DataFrame()
    
    if year == 2015:
        # 2015 mein 3 death columns hain
        cat_col = [c for c in df.columns if 'Category' in c][0]
        state_col = [c for c in df.columns if 'State' in c][0]
        nat_col = [c for c in df.columns if 'Natural' in c and 'Un' not in c][0]
        unnat_col = [c for c in df.columns if 'Un-natural' in c][0]
        other_col = [c for c in df.columns if 'Others' in c][0]
        total_col = [c for c in df.columns if 'Total' in c][0]
        pop_col = [c for c in df.columns if 'Population' in c][0]
        rate_col = [c for c in df.columns if 'Rate' in c][0]
        
        df = df[df[cat_col] == 'State'].copy()
        result['category'] = df[cat_col]
        result['state_ut_city'] = df[state_col]
        result['deaths_nature'] = df[nat_col]
        result['deaths_unnatural'] = df[unnat_col]
        result['deaths_others'] = df[other_col]
        result['deaths_total'] = df[total_col]
        result['population_lakh'] = df[pop_col]
        result['death_rate'] = df[rate_col]
        
    else:
        # 2016-2022 mein 2 death columns hain
        cat_col = [c for c in df.columns if 'Category' in c or c.strip() == 'Category'][0]
        state_col = [c for c in df.columns if 'State' in c][0]
        nature_col = [c for c in df.columns if 'Nature' in c or 'Forces' in c][0]
        other_col = [c for c in df.columns if 'Other' in c][0]
        total_col = [c for c in df.columns if 'Total' in c][0]
        pop_col = [c for c in df.columns if 'Population' in c][0]
        rate_col = [c for c in df.columns if 'Rate' in c][0]
        
        df = df[df[cat_col].astype(str).str.strip() == 'State'].copy()
        result['category'] = df[cat_col]
        result['state_ut_city'] = df[state_col]
        result['deaths_nature'] = df[nature_col]
        result['deaths_unnatural'] = None
        result['deaths_others'] = None
        result['deaths_total'] = df[total_col]
        result['population_lakh'] = df[pop_col]
        result['death_rate'] = df[rate_col]
    
    result['year'] = year
    return result

# Test karte hain saare years
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
all_data = []

for year in years:
    try:
        df = load_table_1_2_smart(year)
        all_data.append(df)
        print(f"✅ {year} loaded — {len(df)} states")
    except Exception as e:
        print(f"❌ {year} error — {e}")

# Merge karo
df_deaths = pd.concat(all_data, ignore_index=True)
print(f"\n✅ Final merged shape: {df_deaths.shape}")
df_deaths.head()

✅ 2015 loaded — 29 states
✅ 2016 loaded — 30 states
✅ 2017 loaded — 30 states
✅ 2018 loaded — 30 states
✅ 2019 loaded — 30 states
✅ 2020 loaded — 28 states
✅ 2021 loaded — 28 states
✅ 2022 loaded — 28 states

✅ Final merged shape: (233, 9)

  category      state_ut_city  deaths_nature deaths_unnatural deaths_others  deaths_total  population_lakh  death_rate  year
0    State     ANDHRA PRADESH            771            15320          1321           771            513.4        33.9  2015
1    State  ARUNACHAL PRADESH             27              319            23            27             13.0        28.3  2015
2    State              ASSAM            236             3910           185           236            322.0        13.5  2015
3    State              BIHAR            417             9470           481           417           1031.4        10.1  2015
4    State       CHHATTISGARH            261            14333          4679           261            256.6        75.1  2015

In [12]:
# Har year mein kitne states hain
print("Year wise state count:")
print(df_deaths.groupby('year')['state_ut_city'].count())

print("\n2015 states jo baad mein nahi hain:")
states_2015 = set(df_deaths[df_deaths['year']==2015]['state_ut_city'])
states_2022 = set(df_deaths[df_deaths['year']==2022]['state_ut_city'])
print(states_2015 - states_2022)

print("\n2022 mein naye states:")
print(states_2022 - states_2015)

Year wise state count:
year
2015    29
2016    30
2017    30
2018    30
2019    30
2020    28
2021    28
2022    28
Name: state_ut_city, dtype: int64

2015 states jo baad mein nahi hain:
{'TRIPURA', 'ASSAM', 'ANDHRA PRADESH', 'MIZORAM', 'UTTARAKHAND', 'MADHYA PRADESH', 'TELANGANA', 'BIHAR', 'JAMMU & KASHMIR', 'RAJASTHAN', 'MAHARASHTRA', 'NAGALAND', 'HIMACHAL PRADESH', 'UTTAR PRADESH', 'MEGHALAYA', 'HARYANA', 'KARNATAKA', 'MANIPUR', 'WEST BENGAL', 'CHHATTISGARH', 'GOA', 'PUNJAB', 'JHARKHAND', 'GUJARAT', 'TAMIL NADU', 'ODISHA', 'ARUNACHAL PRADESH', 'KERALA', 'SIKKIM'}

2022 mein naye states:
{'Jharkhand', 'Odisha', 'Sikkim', 'West Bengal', 'Gujarat', 'Goa', 'Bihar', 'Karnataka', 'Rajasthan', 'Haryana', 'Mizoram', 'Punjab', 'Madhya Pradesh', 'Assam', 'Chhattisgarh', 'Andhra Pradesh', 'Maharashtra', 'Tamil Nadu', 'Manipur', 'Himachal Pradesh', 'Tripura', 'Arunachal Pradesh', 'Telangana', 'Uttar Pradesh', 'Nagaland', 'Kerala', 'Uttarakhand', 'Meghalaya'}

In [13]:
# Saare state names uppercase kar do — consistency ke liye
df_deaths['state_ut_city'] = df_deaths['state_ut_city'].str.strip().str.upper()

# Ab check karo
print("Year wise state count:")
print(df_deaths.groupby('year')['state_ut_city'].count())

print("\n2015 vs 2022 difference:")
states_2015 = set(df_deaths[df_deaths['year']==2015]['state_ut_city'])
states_2022 = set(df_deaths[df_deaths['year']==2022]['state_ut_city'])
print("2015 mein hai, 2022 mein nahi:", states_2015 - states_2022)
print("2022 mein hai, 2015 mein nahi:", states_2022 - states_2015)

Year wise state count:
year
2015    29
2016    30
2017    30
2018    30
2019    30
2020    28
2021    28
2022    28
Name: state_ut_city, dtype: int64

2015 vs 2022 difference:
2015 mein hai, 2022 mein nahi: {'JAMMU & KASHMIR'}
2022 mein hai, 2015 mein nahi: set()

In [14]:
# Check - 2016 mein kaun sa extra state tha
states_2016 = set(df_deaths[df_deaths['year']==2016]['state_ut_city'])
print("Extra state in 2016 vs 2015:")
print(states_2016 - states_2015)

# J&K ko 2020 ke baad data mein note karo
print("\nJ&K data availability:")
jk = df_deaths[df_deaths['state_ut_city'] == 'JAMMU & KASHMIR']
print(jk[['year', 'state_ut_city', 'deaths_total']])

Extra state in 2016 vs 2015:
{'TOTAL (STATES)'}

J&K data availability:
     year    state_ut_city  deaths_total
9    2015  JAMMU & KASHMIR           387
38   2016  JAMMU & KASHMIR           280
68   2017  JAMMU & KASHMIR           127
98   2018  JAMMU & KASHMIR           131
128  2019  JAMMU & KASHMIR          1451

In [15]:
# Remove TOTAL rows jo filter mein ghus gayi hain
df_deaths = df_deaths[~df_deaths['state_ut_city'].str.contains('TOTAL')].copy()

# Reset index
df_deaths = df_deaths.reset_index(drop=True)

# Final check
print("Final shape:", df_deaths.shape)
print("\nYear wise state count after fix:")
print(df_deaths.groupby('year')['state_ut_city'].count())

Final shape: (229, 9)

Year wise state count after fix:
year
2015    29
2016    29
2017    29
2018    29
2019    29
2020    28
2021    28
2022    28
Name: state_ut_city, dtype: int64

In [16]:
# Save cleaned data
output_path = "../data/processed/state_deaths_2015_2022.csv"
df_deaths.to_csv(output_path, index=False)

print("✅ Data saved successfully!")
print(f"Location: {output_path}")
print(f"Shape: {df_deaths.shape}")
print("\nSample data:")
df_deaths.head()

✅ Data saved successfully!
Location: ../data/processed/state_deaths_2015_2022.csv
Shape: (229, 9)

Sample data:

  category      state_ut_city  deaths_nature deaths_unnatural deaths_others  deaths_total  population_lakh  death_rate  year
0    State     ANDHRA PRADESH            771            15320          1321           771            513.4        33.9  2015
1    State  ARUNACHAL PRADESH             27              319            23            27             13.0        28.3  2015
2    State              ASSAM            236             3910           185           236            322.0        13.5  2015
3    State              BIHAR            417             9470           481           417           1031.4        10.1  2015
4    State       CHHATTISGARH            261            14333          4679           261            256.6        75.1  2015